---
version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      NuGet:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: "/Alidade.Map"
    schedule:
      interval: "daily"
    groups:
      NPM:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      Pipeline:
        patterns:
          - "*"
