using System.Text;
using System.Text.Json;

namespace Alidade.OsmGen.Generators;

/// <summary>
///   Reads the name-suggestion-index iD-preset file and emits C# source files for
///   brand/operator suggestions. Each region is a standalone static class so that
///   loading one region never triggers initialization of others.
///
///   Output files:
///   - NsiGlobalData.g.cs
///       - worldwide items (no region dependency)
///   - NsiRegion_XX.g.cs
///       - per-region items as standalone classes
///   - NsiRegionDispatcher.g.cs
///       - switch-based dispatcher; only the accessed region initializes
///   - NsiRegionBounds.g.cs
///       - precomputed bounding boxes for geojson regions (no NsiItem refs)
/// </summary>
internal static class NsiGenerator
{
    private const string WorldwideCode = "001";

    public static void Generate(string nodeModulesDir, string outputDir)
    {
        Console.WriteLine("NsiGenerator: reading nsi-id-presets.min.json...");

        string nsiPath = Path.Combine(nodeModulesDir, "name-suggestion-index", "dist", "presets", "nsi-id-presets.min.json");
        using JsonDocument doc = JsonDocument.Parse(File.ReadAllText(nsiPath));

        if (!doc.RootElement.TryGetProperty("presets", out JsonElement presetsEl))
        {
            Console.Error.WriteLine("  ERROR: nsi-id-presets.min.json missing top-level 'presets' property");
            return;
        }

        Dictionary<string, List<NsiRawItem>> byRegion = new(StringComparer.OrdinalIgnoreCase);
        List<NsiRawItem> global = [];

        int totalItems = 0;
        foreach (JsonProperty entry in presetsEl.EnumerateObject())
        {
            string presetKey = entry.Name;
            string id = presetKey.Contains('/') ? presetKey[(presetKey.LastIndexOf('/') + 1)..] : presetKey;

            NsiRawItem? raw = ParseItem(id, entry.Value);
            if (raw is null) continue;

            totalItems++;
            List<string> include = GetLocationSetInclude(entry.Value);

            if (include.Count == 0 || include.Contains(WorldwideCode))
            {
                global.Add(raw);
            }
            else
            {
                foreach (string code in include)
                {
                    if (!byRegion.TryGetValue(code, out List<NsiRawItem>? bucket))
                    {
                        byRegion[code] = bucket = [];
                    }

                    bucket.Add(raw);
                }
            }
        }

        Console.WriteLine($"  {totalItems} total items → {global.Count} global, {byRegion.Count} regional buckets");

        EmitGlobalFile(outputDir, global);

        List<(string Code, string ClassName)> regions = [];
        foreach ((string code, List<NsiRawItem> items) in byRegion.OrderBy(kv => kv.Key))
        {
            string className = RegionClassName(code);
            EmitRegionFile(outputDir, code, className, items);
            regions.Add((code, className));
        }

        EmitDispatcherFile(outputDir, regions);

        // Bounding boxes, load featureCollection separately (no NsiItem references)
        string fcPath = Path.Combine(nodeModulesDir, "name-suggestion-index", "dist", "json", "featureCollection.min.json");
        EmitBoundsFile(outputDir, fcPath);
    }

    private static void EmitGlobalFile(string outputDir, List<NsiRawItem> global)
    {
        StringBuilder sb = new();
        sb.AppendLine(CodeGenHelper.AutoGeneratedHeader);
        sb.AppendLine("using Alidade.Osm.Models.Nsi;");
        sb.AppendLine();
        sb.AppendLine("namespace Alidade.Osm.NameSuggestions;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("///   Worldwide (non-region-specific) NSI entries.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class NsiGlobalData");
        sb.AppendLine("{");
        sb.AppendLine("    public static IReadOnlyList<NsiItem> Items { get; } =");
        sb.AppendLine("    [");
        EmitItems(sb, global);
        sb.AppendLine("    ];");
        sb.AppendLine("}");

        CodeGenHelper.WriteFile(Path.Combine(outputDir, "NsiGlobalData.g.cs"), sb.ToString());
    }

    private static void EmitRegionFile(string outputDir, string code, string className, List<NsiRawItem> items)
    {
        StringBuilder sb = new();
        sb.AppendLine(CodeGenHelper.AutoGeneratedHeader);
        sb.AppendLine("using Alidade.Osm.Models.Nsi;");
        sb.AppendLine();
        sb.AppendLine("namespace Alidade.Osm.NameSuggestions;");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>NSI entries for region '{code}'.</summary>");
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");
        sb.AppendLine("    public static IReadOnlyList<NsiItem> Items { get; } =");
        sb.AppendLine("    [");
        EmitItems(sb, items);
        sb.AppendLine("    ];");
        sb.AppendLine("}");

        CodeGenHelper.WriteFile(Path.Combine(outputDir, $"{className}.g.cs"), sb.ToString());
    }

    private static void EmitDispatcherFile(string outputDir, List<(string Code, string ClassName)> regions)
    {
        StringBuilder sb = new();
        sb.AppendLine(CodeGenHelper.AutoGeneratedHeader);
        sb.AppendLine("using Alidade.Osm.Models.Nsi;");
        sb.AppendLine();
        sb.AppendLine("namespace Alidade.Osm.NameSuggestions;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("///   Returns region-specific NSI items on demand.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class NsiRegionDispatcher");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    ///   Returns the NSI items for <paramref name=\"countryCode\"/>,");
        sb.AppendLine("    ///   or <see langword=\"null\"/> if no region data exists for that code.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IReadOnlyList<NsiItem>? GetForRegion(string countryCode) =>");
        sb.AppendLine("        countryCode.ToLowerInvariant() switch");
        sb.AppendLine("        {");
        foreach ((string code, string className) in regions)
        {
            sb.AppendLine($"            \"{code}\" => {className}.Items,");
        }
        sb.AppendLine("            _ => null");
        sb.AppendLine("        };");
        sb.AppendLine("}");

        CodeGenHelper.WriteFile(Path.Combine(outputDir, "NsiRegionDispatcher.g.cs"), sb.ToString());
    }

    private static void EmitBoundsFile(string outputDir, string featureCollectionPath)
    {
        using JsonDocument fc = JsonDocument.Parse(File.ReadAllText(featureCollectionPath));
        if (!fc.RootElement.TryGetProperty("features", out JsonElement featuresEl))
        {
            Console.Error.WriteLine("  WARN: featureCollection.min.json missing 'features'");
            return;
        }

        List<(string Id, double W, double S, double E, double N)> bounds = [];
        foreach (JsonElement feature in featuresEl.EnumerateArray())
        {
            if (!feature.TryGetProperty("id", out JsonElement idEl))
            {
                continue;
            }

            string id = idEl.GetString() ?? string.Empty;
            if (string.IsNullOrEmpty(id))
            {
                continue;
            }

            if (!feature.TryGetProperty("geometry", out JsonElement geom))
            {
                continue;
            }

            string geomType = geom.TryGetProperty("type", out JsonElement typeEl)
                ? (typeEl.GetString() ?? string.Empty)
                : string.Empty;

            if (!geom.TryGetProperty("coordinates", out JsonElement coordsEl))
            {
                continue;
            }

            double w = double.MaxValue, s = double.MaxValue, e = double.MinValue, n = double.MinValue;

            if (geomType == "Polygon")
            {
                ExtendBoundsFromRings(coordsEl, ref w, ref s, ref e, ref n);
            }
            else if (geomType == "MultiPolygon")
            {
                foreach (JsonElement polygon in coordsEl.EnumerateArray())
                {
                    ExtendBoundsFromRings(polygon, ref w, ref s, ref e, ref n);
                }
            }

            if (w < double.MaxValue)
            {
                bounds.Add((id, w, s, e, n));
            }
        }

        StringBuilder sb = new();
        sb.AppendLine(CodeGenHelper.AutoGeneratedHeader);
        sb.AppendLine();
        sb.AppendLine("namespace Alidade.Osm.NameSuggestions;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("///   Precomputed bounding boxes for NSI GeoJSON regions.");
        sb.AppendLine("///   Used for fast point-in-region checks without loading polygon geometry at runtime.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class NsiRegionBounds");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Bounding box (West, South, East, North) per GeoJSON region ID.</summary>");
        sb.AppendLine("    public static IReadOnlyDictionary<string, (double W, double S, double E, double N)> All { get; } =");
        sb.AppendLine("        new Dictionary<string, (double, double, double, double)>(" + bounds.Count + ")");
        sb.AppendLine("        {");
        foreach ((string id, double bw, double bs, double be, double bn) in bounds)
        {
            sb.AppendLine($"            [\"{id}\"] = ({bw:F6}, {bs:F6}, {be:F6}, {bn:F6}),");
        }
        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    ///   Returns GeoJSON region IDs whose bounding box contains the given point.");
        sb.AppendLine("    ///   Results are conservative (bbox may include points outside the actual polygon).");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IEnumerable<string> GetRegionsForPoint(double lat, double lon)");
        sb.AppendLine("    {");
        sb.AppendLine("        foreach ((string id, (double w, double s, double e, double n)) in All)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (lon >= w && lon <= e && lat >= s && lat <= n)");
        sb.AppendLine("                yield return id;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        CodeGenHelper.WriteFile(Path.Combine(outputDir, "NsiRegionBounds.g.cs"), sb.ToString());
        Console.WriteLine($"  wrote NsiRegionBounds.g.cs ({bounds.Count} regions)");
    }

    private static void ExtendBoundsFromRings(JsonElement rings, ref double w, ref double s, ref double e, ref double n)
    {
        foreach (JsonElement ring in rings.EnumerateArray())
        {
            foreach (JsonElement point in ring.EnumerateArray())
            {
                if (point.ValueKind != JsonValueKind.Array)
                {
                    continue;
                }

                JsonElement[] coords = [.. point.EnumerateArray()];
                if (coords.Length < 2)
                {
                    continue;
                }

                double lon = coords[0].GetDouble();
                double lat = coords[1].GetDouble();

                if (lat > n)
                {
                    n = lat;
                }

                if (lon > e)
                {
                    e = lon;
                }

                if (lat < s)
                {
                    s = lat;
                }

                if (lon < w)
                {
                    w = lon;
                }
            }
        }
    }

    private static void EmitItems(StringBuilder sb, IEnumerable<NsiRawItem> items)
    {
        foreach (NsiRawItem item in items)
        {
            string tags = CodeGenHelper.StringDictionary(item.Tags.Select(kv => new KeyValuePair<string, string>(kv.Key, kv.Value)));
            string addTags = CodeGenHelper.StringDictionary(item.AddTags.Select(kv => new KeyValuePair<string, string>(kv.Key, kv.Value)));
            string terms = CodeGenHelper.StringArray(item.Terms);

            sb.AppendLine($"        new NsiItem(");
            sb.AppendLine($"            DisplayName: {CodeGenHelper.StringLiteral(item.DisplayName)},");
            sb.AppendLine($"            Id: {CodeGenHelper.StringLiteral(item.Id)},");
            sb.AppendLine($"            Tags: {tags},");
            sb.AppendLine($"            AddTags: {addTags},");
            sb.AppendLine($"            Terms: {terms}),");
        }
    }

    private static NsiRawItem? ParseItem(string id, JsonElement item)
    {
        if (!item.TryGetProperty("name", out JsonElement nameEl))
        {
            return null;
        }

        string displayName = nameEl.GetString() ?? string.Empty;
        if (string.IsNullOrEmpty(displayName))
        {
            return null;
        }

        Dictionary<string, string> tags = ParseStringDict(item, "tags");
        Dictionary<string, string> addTags = ParseStringDict(item, "addTags");

        List<string> terms = [];
        if (item.TryGetProperty("terms", out JsonElement termsEl) && termsEl.ValueKind == JsonValueKind.Array)
        {
            foreach (JsonElement t in termsEl.EnumerateArray())
            {
                string? s = t.GetString();
                if (s is not null)
                {
                    terms.Add(s);
                }
            }
        }

        if (!terms.Contains(displayName, StringComparer.OrdinalIgnoreCase))
        {
            terms.Insert(0, displayName);
        }

        return new NsiRawItem(displayName, id, tags, addTags, terms);
    }

    private static Dictionary<string, string> ParseStringDict(JsonElement parent, string propertyName)
    {
        Dictionary<string, string> result = [];
        if (parent.TryGetProperty(propertyName, out JsonElement el) && el.ValueKind == JsonValueKind.Object)
        {
            foreach (JsonProperty p in el.EnumerateObject())
            {
                result[p.Name] = p.Value.GetString() ?? string.Empty;
            }
        }
        return result;
    }

    private static List<string> GetLocationSetInclude(JsonElement item)
    {
        if (!item.TryGetProperty("locationSet", out JsonElement ls))
        {
            return [];
        }

        if (!ls.TryGetProperty("include", out JsonElement inc) || inc.ValueKind != JsonValueKind.Array)
        {
            return [];
        }

        List<string> result = [];
        foreach (JsonElement el in inc.EnumerateArray())
        {
            if (el.ValueKind != JsonValueKind.String)
            {
                continue;
            }

            string? s = el.GetString();
            if (s is not null)
            {
                result.Add(s.TrimStart('+').ToLowerInvariant());
            }
        }
        return result;
    }

    private static string RegionClassName(string code)
    {
        StringBuilder sb = new("NsiRegion_");
        foreach (char c in code.ToUpperInvariant())
        {
            sb.Append(char.IsLetterOrDigit(c) ? c : '_');
        }

        return sb.ToString();
    }

    private sealed record NsiRawItem(string DisplayName, string Id, Dictionary<string, string> Tags, Dictionary<string, string> AddTags, List<string> Terms);
}
