// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'es-ma.geojson'.</summary>
public static class NsiRegion_ES_MA_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"Junta de Andalucía",
            Id: @"juntadeandalucia-2d561d",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"clinic", [@"operator:wikidata"] = @"Q2743342", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"clinic", [@"healthcare"] = @"clinic", [@"operator"] = @"Junta de Andalucía", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q2743342", },
            Terms: [@"junta de andalucía"]),
        new NsiItem(
            DisplayName: @"Servicio Andaluz de Salud",
            Id: @"servicioandaluzdesalud-2d561d",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"clinic", [@"operator:wikidata"] = @"Q4753529", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"clinic", [@"healthcare"] = @"clinic", [@"operator"] = @"Servicio Andaluz de Salud", [@"operator:short"] = @"SAS", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q4753529", },
            Terms: [@"sas", @"servicio andaluz de salud"]),
        new NsiItem(
            DisplayName: @"Ayuntamiento de Málaga",
            Id: @"ayuntamientodemalaga-b7b38c",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"community_centre", [@"operator:wikidata"] = @"Q5714892", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"community_centre", [@"operator"] = @"Ayuntamiento de Málaga", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q5714892", },
            Terms: [@"ayuntamiento de málaga"]),
        new NsiItem(
            DisplayName: @"Junta de Andalucía",
            Id: @"juntadeandalucia-d0ed78",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"community_centre", [@"operator:wikidata"] = @"Q2743342", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"community_centre", [@"operator"] = @"Junta de Andalucía", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q2743342", },
            Terms: [@"junta de andalucía"]),
        new NsiItem(
            DisplayName: @"Servicio Andaluz de Salud",
            Id: @"servicioandaluzdesalud-0e8970",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"hospital", [@"operator:wikidata"] = @"Q4753529", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"hospital", [@"healthcare"] = @"hospital", [@"operator"] = @"Servicio Andaluz de Salud", [@"operator:short"] = @"SAS", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q4753529", },
            Terms: [@"sas", @"servicio andaluz de salud"]),
        new NsiItem(
            DisplayName: @"Ayuntamiento de Málaga",
            Id: @"ayuntamientodemalaga-b732f6",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"library", [@"operator:wikidata"] = @"Q5714892", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"library", [@"operator"] = @"Ayuntamiento de Málaga", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q5714892", },
            Terms: [@"ayuntamiento de málaga"]),
        new NsiItem(
            DisplayName: @"Junta de Andalucía",
            Id: @"juntadeandalucia-4c814c",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"library", [@"operator:wikidata"] = @"Q2743342", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"library", [@"operator"] = @"Junta de Andalucía", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q2743342", },
            Terms: [@"junta de andalucía"]),
        new NsiItem(
            DisplayName: @"Universidad de Málaga",
            Id: @"universidaddemalaga-b732f6",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"library", [@"operator:wikidata"] = @"Q958650", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"library", [@"operator"] = @"Universidad de Málaga", [@"operator:type"] = @"university", [@"operator:wikidata"] = @"Q958650", },
            Terms: [@"universidad de málaga"]),
        new NsiItem(
            DisplayName: @"Ayuntamiento de Málaga",
            Id: @"ayuntamientodemalaga-5b9350",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"recycling", [@"operator:wikidata"] = @"Q5714892", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"recycling", [@"operator"] = @"Ayuntamiento de Málaga", [@"operator:wikidata"] = @"Q5714892", },
            Terms: [@"ayuntamiento de málaga"]),
        new NsiItem(
            DisplayName: @"Junta de Andalucía",
            Id: @"juntadeandalucia-683909",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q2743342", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Junta de Andalucía", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q2743342", },
            Terms: [@"junta de andalucía"]),
        new NsiItem(
            DisplayName: @"Junta de Andalucía",
            Id: @"juntadeandalucia-26a1e8",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"social_facility", [@"operator:wikidata"] = @"Q2743342", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"social_facility", [@"operator"] = @"Junta de Andalucía", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q2743342", },
            Terms: [@"junta de andalucía"]),
        new NsiItem(
            DisplayName: @"Junta de Andalucía",
            Id: @"juntadeandalucia-2ab393",
            Tags: new Dictionary<string, string> { [@"boundary"] = @"protected_area", [@"operator:wikidata"] = @"Q2743342", },
            AddTags: new Dictionary<string, string> { [@"boundary"] = @"protected_area", [@"operator"] = @"Junta de Andalucía", [@"operator:wikidata"] = @"Q2743342", },
            Terms: [@"junta de andalucía"]),
        new NsiItem(
            DisplayName: @"Ayuntamiento de Málaga",
            Id: @"ayuntamientodemalaga-af5f77",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator:wikidata"] = @"Q5714892", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator"] = @"Ayuntamiento de Málaga", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q5714892", },
            Terms: [@"ayuntamiento de málaga"]),
        new NsiItem(
            DisplayName: @"Ayuntamiento de Málaga",
            Id: @"ayuntamientodemalaga-5098b8",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator:wikidata"] = @"Q5714892", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator"] = @"Ayuntamiento de Málaga", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q5714892", },
            Terms: [@"ayuntamiento de málaga"]),
        new NsiItem(
            DisplayName: @"Ayuntamiento de Málaga",
            Id: @"ayuntamientodemalaga-761383",
            Tags: new Dictionary<string, string> { [@"office"] = @"government", [@"operator:wikidata"] = @"Q5714892", },
            AddTags: new Dictionary<string, string> { [@"office"] = @"government", [@"operator"] = @"Ayuntamiento de Málaga", [@"operator:wikidata"] = @"Q5714892", },
            Terms: [@"ayuntamiento de málaga"]),
        new NsiItem(
            DisplayName: @"Junta de Andalucía",
            Id: @"juntadeandalucia-47b5b9",
            Tags: new Dictionary<string, string> { [@"office"] = @"government", [@"operator:wikidata"] = @"Q2743342", },
            AddTags: new Dictionary<string, string> { [@"office"] = @"government", [@"operator"] = @"Junta de Andalucía", [@"operator:wikidata"] = @"Q2743342", },
            Terms: [@"junta de andalucía"]),
        new NsiItem(
            DisplayName: @"Autobuses Urbanos de Vélez-Málaga",
            Id: @"autobusesurbanosdevelezmalaga-9990f5",
            Tags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"network:wikidata"] = @"Q5712433", [@"public_transport"] = @"platform", },
            AddTags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"highway"] = @"bus_stop", [@"network"] = @"Autobuses Urbanos de Vélez-Málaga", [@"network:wikidata"] = @"Q5712433", [@"public_transport"] = @"platform", },
            Terms: [@"autobuses urbanos de vélez-málaga"]),
        new NsiItem(
            DisplayName: @"Consorcio de Transporte Metropolitano del Área de Málaga",
            Id: @"consorciodetransportemetropolitanodelareademalaga-9990f5",
            Tags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"network:wikidata"] = @"Q6949617", [@"public_transport"] = @"platform", },
            AddTags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"highway"] = @"bus_stop", [@"network"] = @"Consorcio de Transporte Metropolitano del Área de Málaga", [@"network:short"] = @"CTMAM", [@"network:wikidata"] = @"Q6949617", [@"public_transport"] = @"platform", },
            Terms: [@"consorcio de transporte metropolitano del área de málaga", @"ctmam"]),
        new NsiItem(
            DisplayName: @"Cercanías Málaga",
            Id: @"cercaniasmalaga-e70f76",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q167503", [@"railway"] = @"station", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Cercanías Málaga", [@"network:wikidata"] = @"Q167503", [@"operator"] = @"Renfe", [@"operator:wikidata"] = @"Q2476154", [@"public_transport"] = @"station", [@"railway"] = @"station", [@"train"] = @"yes", },
            Terms: [@"cercanías málaga", @"renfe"]),
        new NsiItem(
            DisplayName: @"Autobuses Urbanos de Vélez-Málaga",
            Id: @"autobusesurbanosdevelezmalaga-a00b01",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q5712433", [@"route"] = @"bus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Autobuses Urbanos de Vélez-Málaga", [@"network:wikidata"] = @"Q5712433", [@"route"] = @"bus", [@"type"] = @"route", },
            Terms: [@"autobuses urbanos de vélez-málaga"]),
        new NsiItem(
            DisplayName: @"Consorcio de Transporte Metropolitano del Área de Málaga",
            Id: @"consorciodetransportemetropolitanodelareademalaga-a00b01",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q6949617", [@"route"] = @"bus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Consorcio de Transporte Metropolitano del Área de Málaga", [@"network:short"] = @"CTMAM", [@"network:wikidata"] = @"Q6949617", [@"route"] = @"bus", [@"type"] = @"route", },
            Terms: [@"consorcio de transporte metropolitano del área de málaga", @"ctmam"]),
        new NsiItem(
            DisplayName: @"Cercanías Málaga",
            Id: @"cercaniasmalaga-b25b91",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q167503", [@"route"] = @"train", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Cercanías Málaga", [@"network:wikidata"] = @"Q167503", [@"operator"] = @"Renfe", [@"operator:wikidata"] = @"Q2476154", [@"route"] = @"train", [@"type"] = @"route", },
            Terms: [@"cercanías málaga", @"renfe"]),
    ];
}
