// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'us-il-cook_county.geojson'.</summary>
public static class NsiRegion_US_IL_COOK_COUNTY_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"Divvy",
            Id: @"divvy-c25c95",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bicycle_rental", [@"brand:wikidata"] = @"Q16973938", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bicycle_rental", [@"brand"] = @"Divvy", [@"brand:wikidata"] = @"Q16973938", [@"fee"] = @"yes", [@"network"] = @"Divvy", [@"network:wikidata"] = @"Q16973938", [@"operator"] = @"Lyft", [@"operator:type"] = @"private", [@"operator:wikidata"] = @"Q17077936", },
            Terms: [@"divvy", @"lyft", @"lyft bike"]),
        new NsiItem(
            DisplayName: @"Stan's Donuts & Coffee",
            Id: @"stansdonutsandcoffee-f14bdc",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"cafe", [@"brand:wikidata"] = @"Q120985884", [@"cuisine"] = @"coffee_shop", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"cafe", [@"brand"] = @"Stan's Donuts & Coffee", [@"brand:wikidata"] = @"Q120985884", [@"cuisine"] = @"coffee_shop", [@"name"] = @"Stan's Donuts & Coffee", [@"takeaway"] = @"yes", },
            Terms: [@"stan's donuts & coffee"]),
        new NsiItem(
            DisplayName: @"Al's Beef",
            Id: @"alsbeef-6bb90c",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"fast_food", [@"brand:wikidata"] = @"Q110609570", [@"cuisine"] = @"sandwich", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"fast_food", [@"brand"] = @"Al's Beef", [@"brand:wikidata"] = @"Q110609570", [@"cuisine"] = @"sandwich", [@"name"] = @"Al's Beef", [@"takeaway"] = @"yes", },
            Terms: [@"al's beef"]),
        new NsiItem(
            DisplayName: @"Cook County Health",
            Id: @"cookcountyhealth-920795",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"clinic", [@"operator:wikidata"] = @"Q30286975", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"clinic", [@"healthcare"] = @"clinic", [@"operator"] = @"Cook County Health", [@"operator:short"] = @"CCH", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q30286975", },
            Terms: [@"cch", @"cook county health"]),
        new NsiItem(
            DisplayName: @"Chicago Park District",
            Id: @"chicagoparkdistrict-a2bb95",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"community_centre", [@"operator:wikidata"] = @"Q2963322", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"community_centre", [@"operator"] = @"Chicago Park District", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q2963322", },
            Terms: [@"chicago park district"]),
        new NsiItem(
            DisplayName: @"Circuit Court of Cook County",
            Id: @"circuitcourtofcookcounty-57b598",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"courthouse", [@"operator:wikidata"] = @"Q5121577", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"courthouse", [@"operator"] = @"Circuit Court of Cook County", [@"operator:wikidata"] = @"Q5121577", },
            Terms: [@"circuit court of cook county"]),
        new NsiItem(
            DisplayName: @"Chicago Public Schools",
            Id: @"chicagopublicschools-d33682",
            Tags: new Dictionary<string, string> { [@"education"] = @"kindergarten", [@"operator:wikidata"] = @"Q2963340", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"kindergarten", [@"education"] = @"kindergarten", [@"operator"] = @"Chicago Public Schools", [@"operator:short"] = @"CPS", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q2963340", },
            Terms: [@"chicago public schools", @"cps"]),
        new NsiItem(
            DisplayName: @"Chicago Public Library",
            Id: @"chicagopubliclibrary-508b9c",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"library", [@"operator:wikidata"] = @"Q1060421", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"library", [@"operator"] = @"Chicago Public Library", [@"operator:short"] = @"CPL", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q1060421", },
            Terms: [@"chicago public library", @"cpl"]),
        new NsiItem(
            DisplayName: @"Arlington Heights School District 25",
            Id: @"arlingtonheightsschooldistrict25-4aef52",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q4792334", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Arlington Heights School District 25", [@"operator:short"] = @"AHSD25", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q4792334", },
            Terms: [@"ahsd25", @"arlington heights school district 25"]),
        new NsiItem(
            DisplayName: @"Berwyn North School District 98",
            Id: @"berwynnorthschooldistrict98-4aef52",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q4896040", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Berwyn North School District 98", [@"operator:short"] = @"BN98", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q4896040", },
            Terms: [@"berwyn north school district 98", @"bn98"]),
        new NsiItem(
            DisplayName: @"Berwyn South School District 100",
            Id: @"berwynsouthschooldistrict100-4aef52",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q4896043", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Berwyn South School District 100", [@"operator:short"] = @"BSD100", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q4896043", },
            Terms: [@"berwyn south school district 100", @"bsd100"]),
        new NsiItem(
            DisplayName: @"Chicago Heights School District 170",
            Id: @"chicagoheightsschooldistrict170-4aef52",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q107645994", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Chicago Heights School District 170", [@"operator:short"] = @"CHSD170", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q107645994", },
            Terms: [@"chicago heights school district 170", @"chsd170"]),
        new NsiItem(
            DisplayName: @"Chicago Public Schools",
            Id: @"chicagopublicschools-4aef52",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q2963340", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Chicago Public Schools", [@"operator:short"] = @"CPS", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q2963340", },
            Terms: [@"chicago public schools", @"cps"]),
        new NsiItem(
            DisplayName: @"Cicero School District 99",
            Id: @"ciceroschooldistrict99-4aef52",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q5119369", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Cicero School District 99", [@"operator:short"] = @"D99", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q5119369", },
            Terms: [@"cicero school district 99", @"d99"]),
        new NsiItem(
            DisplayName: @"Community Consolidated School District 15",
            Id: @"communityconsolidatedschooldistrict15-4aef52",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q16959009", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Community Consolidated School District 15", [@"operator:short"] = @"CCSD15", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q16959009", },
            Terms: [@"ccsd15", @"community consolidated school district 15", @"district 15"]),
        new NsiItem(
            DisplayName: @"Community Consolidated School District 54",
            Id: @"communityconsolidatedschooldistrict54-4aef52",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q5154701", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Community Consolidated School District 54", [@"operator:short"] = @"CCSD54", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q5154701", },
            Terms: [@"ccsd54", @"community consolidated school district 54", @"district 54"]),
        new NsiItem(
            DisplayName: @"Community Consolidated School District 59",
            Id: @"communityconsolidatedschooldistrict59-4aef52",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q5154702", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Community Consolidated School District 59", [@"operator:short"] = @"CCSD59", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q5154702", },
            Terms: [@"ccsd59", @"community consolidated school district 59"]),
        new NsiItem(
            DisplayName: @"Community Consolidated School District 62",
            Id: @"communityconsolidatedschooldistrict62-4aef52",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q5154703", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Community Consolidated School District 62", [@"operator:short"] = @"CCSD62", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q5154703", },
            Terms: [@"ccsd62", @"community consolidated school district 62", @"district 62"]),
        new NsiItem(
            DisplayName: @"Cook County School District 130",
            Id: @"cookcountyschooldistrict130-4aef52",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q134522608", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Cook County School District 130", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q134522608", },
            Terms: [@"cook county school district 130"]),
        new NsiItem(
            DisplayName: @"Elmwood Park Community Unit School District 401",
            Id: @"elmwoodparkcommunityunitschooldistrict401-4aef52",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q96377175", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Elmwood Park Community Unit School District 401", [@"operator:short"] = @"EPCUSD 401", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q96377175", },
            Terms: [@"elmwood park community unit school district 401", @"epcusd 401"]),
        new NsiItem(
            DisplayName: @"Evanston/Skokie School District 65",
            Id: @"evanstonskokieschooldistrict65-4aef52",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q16992798", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Evanston/Skokie School District 65", [@"operator:short"] = @"D65", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q16992798", },
            Terms: [@"d65", @"evanston school district 65", @"evanston/skokie school district 65"]),
        new NsiItem(
            DisplayName: @"Glenview School District 34",
            Id: @"glenviewschooldistrict34-4aef52",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q5569395", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Glenview School District 34", [@"operator:short"] = @"DSD34", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q5569395", },
            Terms: [@"dsd34", @"glenview school district 34"]),
        new NsiItem(
            DisplayName: @"Oak Park Elementary School District 97",
            Id: @"oakparkelementaryschooldistrict97-4aef52",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q7073660", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Oak Park Elementary School District 97", [@"operator:short"] = @"OPESD97", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q7073660", },
            Terms: [@"oak park elementary school district", @"oak park elementary school district 97", @"opesd97"]),
        new NsiItem(
            DisplayName: @"Township High School District 211",
            Id: @"townshiphighschooldistrict211-4aef52",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q7830251", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Township High School District 211", [@"operator:short"] = @"D211", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q7830251", },
            Terms: [@"d211", @"township high school district 211"]),
        new NsiItem(
            DisplayName: @"Township High School District 214",
            Id: @"townshiphighschooldistrict214-4aef52",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q7830252", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Township High School District 214", [@"operator:short"] = @"D214", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q7830252", },
            Terms: [@"d214", @"township high school district 214"]),
        new NsiItem(
            DisplayName: @"Wheeling Community Consolidated School District 21",
            Id: @"wheelingcommunityconsolidatedschooldistrict21-4aef52",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q17091399", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Wheeling Community Consolidated School District 21", [@"operator:short"] = @"CCSD21", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q17091399", },
            Terms: [@"ccsd21", @"wheeling community consolidated school district 21"]),
        new NsiItem(
            DisplayName: @"Wilmette Public Schools District 39",
            Id: @"wilmettepublicschoolsdistrict39-4aef52",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q5757923", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Wilmette Public Schools District 39", [@"operator:short"] = @"WPSD39", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q5757923", },
            Terms: [@"wilmette public schools district 39", @"wpsd39"]),
        new NsiItem(
            DisplayName: @"Forest Preserve District of Cook County",
            Id: @"forestpreservedistrictofcookcounty-b265e6",
            Tags: new Dictionary<string, string> { [@"boundary"] = @"protected_area", [@"operator:wikidata"] = @"Q5469080", },
            AddTags: new Dictionary<string, string> { [@"boundary"] = @"protected_area", [@"operator"] = @"Forest Preserve District of Cook County", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q5469080", },
            Terms: [@"forest preserve district of cook county"]),
        new NsiItem(
            DisplayName: @"Arlington Heights Park District",
            Id: @"arlingtonheightsparkdistrict-40d9aa",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator:wikidata"] = @"Q4792332", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator"] = @"Arlington Heights Park District", [@"operator:short"] = @"AHPD", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q4792332", },
            Terms: [@"ahpd", @"arlington heights park district"]),
        new NsiItem(
            DisplayName: @"Calumet Memorial Park District",
            Id: @"calumetmemorialparkdistrict-40d9aa",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator:wikidata"] = @"Q118594118", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator"] = @"Calumet Memorial Park District", [@"operator:short"] = @"CMPD", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q118594118", },
            Terms: [@"calumet memorial park district", @"cmpd"]),
        new NsiItem(
            DisplayName: @"Chicago Park District",
            Id: @"chicagoparkdistrict-40d9aa",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator:wikidata"] = @"Q2963322", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator"] = @"Chicago Park District", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q2963322", },
            Terms: [@"chicago park district", @"chicago parks district"]),
        new NsiItem(
            DisplayName: @"Clyde Park District",
            Id: @"clydeparkdistrict-40d9aa",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator:wikidata"] = @"Q112220888", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator"] = @"Clyde Park District", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q112220888", },
            Terms: [@"clyde park district"]),
        new NsiItem(
            DisplayName: @"Evanston Parks & Recreation",
            Id: @"evanstonparksandrecreation-40d9aa",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator:wikidata"] = @"Q110064075", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator"] = @"Evanston Parks & Recreation", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q110064075", },
            Terms: [@"evanston park district", @"evanston parks & recreation"]),
        new NsiItem(
            DisplayName: @"Forest Preserve District of Cook County",
            Id: @"forestpreservedistrictofcookcounty-40d9aa",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator:wikidata"] = @"Q5469080", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator"] = @"Forest Preserve District of Cook County", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q5469080", },
            Terms: [@"forest preserve district of cook county"]),
        new NsiItem(
            DisplayName: @"Glencoe Park District",
            Id: @"glencoeparkdistrict-40d9aa",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator:wikidata"] = @"Q112220906", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator"] = @"Glencoe Park District", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q112220906", },
            Terms: [@"glencoe park district"]),
        new NsiItem(
            DisplayName: @"Glenview Park District",
            Id: @"glenviewparkdistrict-40d9aa",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator:wikidata"] = @"Q110064219", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator"] = @"Glenview Park District", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q110064219", },
            Terms: [@"glenview park district"]),
        new NsiItem(
            DisplayName: @"Lincolnwood Parks and Recreation",
            Id: @"lincolnwoodparksandrecreation-40d9aa",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator:wikidata"] = @"Q110072249", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator"] = @"Lincolnwood Parks and Recreation", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q110072249", },
            Terms: [@"lincolnwood park district", @"lincolnwood parks and recreation"]),
        new NsiItem(
            DisplayName: @"Morton Grove Park District",
            Id: @"mortongroveparkdistrict-40d9aa",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator:wikidata"] = @"Q110072677", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator"] = @"Morton Grove Park District", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q110072677", },
            Terms: [@"morton grove park district"]),
        new NsiItem(
            DisplayName: @"Niles Park District",
            Id: @"nilesparkdistrict-40d9aa",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator:wikidata"] = @"Q110073017", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator"] = @"Niles Park District", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q110073017", },
            Terms: [@"niles park district"]),
        new NsiItem(
            DisplayName: @"Palatine Park District",
            Id: @"palatineparkdistrict-40d9aa",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator:wikidata"] = @"Q112220961", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator"] = @"Palatine Park District", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q112220961", },
            Terms: [@"palatine park district"]),
        new NsiItem(
            DisplayName: @"Park District of Oak Park",
            Id: @"parkdistrictofoakpark-40d9aa",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator:wikidata"] = @"Q112220982", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator"] = @"Park District of Oak Park", [@"operator:short"] = @"PDOP", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q112220982", },
            Terms: [@"park district of oak park", @"pdop"]),
        new NsiItem(
            DisplayName: @"Park Ridge Park District",
            Id: @"parkridgeparkdistrict-40d9aa",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator:wikidata"] = @"Q112221067", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator"] = @"Park Ridge Park District", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q112221067", },
            Terms: [@"park ridge park district"]),
        new NsiItem(
            DisplayName: @"Skokie Park District",
            Id: @"skokieparkdistrict-40d9aa",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator:wikidata"] = @"Q112228684", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator"] = @"Skokie Park District", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q112228684", },
            Terms: [@"skokie park district"]),
        new NsiItem(
            DisplayName: @"Village of South Holland",
            Id: @"villageofsouthholland-40d9aa",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator:wikidata"] = @"Q404614", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator"] = @"Village of South Holland", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q404614", },
            Terms: [@"village of south holland"]),
        new NsiItem(
            DisplayName: @"Western Springs Park District",
            Id: @"westernspringsparkdistrict-40d9aa",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator:wikidata"] = @"Q112228971", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator"] = @"Western Springs Park District", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q112228971", },
            Terms: [@"western springs park district"]),
        new NsiItem(
            DisplayName: @"Wilmette Park District",
            Id: @"wilmetteparkdistrict-40d9aa",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator:wikidata"] = @"Q112228979", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator"] = @"Wilmette Park District", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q112228979", },
            Terms: [@"wilmette park district"]),
        new NsiItem(
            DisplayName: @"Winnetka Park District",
            Id: @"winnetkaparkdistrict-40d9aa",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator:wikidata"] = @"Q112228982", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator"] = @"Winnetka Park District", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q112228982", },
            Terms: [@"winnetka park district"]),
        new NsiItem(
            DisplayName: @"Arlington Heights Park District",
            Id: @"arlingtonheightsparkdistrict-d1b6fa",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator:wikidata"] = @"Q4792332", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator"] = @"Arlington Heights Park District", [@"operator:short"] = @"AHPD", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q4792332", },
            Terms: [@"ahpd", @"arlington heights park district"]),
        new NsiItem(
            DisplayName: @"Calumet Memorial Park District",
            Id: @"calumetmemorialparkdistrict-d1b6fa",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator:wikidata"] = @"Q118594118", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator"] = @"Calumet Memorial Park District", [@"operator:short"] = @"CMPD", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q118594118", },
            Terms: [@"calumet memorial park district", @"cmpd"]),
        new NsiItem(
            DisplayName: @"Chicago Park District",
            Id: @"chicagoparkdistrict-d1b6fa",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator:wikidata"] = @"Q2963322", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator"] = @"Chicago Park District", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q2963322", },
            Terms: [@"chicago park district", @"chicago parks district"]),
        new NsiItem(
            DisplayName: @"Clyde Park District",
            Id: @"clydeparkdistrict-d1b6fa",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator:wikidata"] = @"Q112220888", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator"] = @"Clyde Park District", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q112220888", },
            Terms: [@"clyde park district"]),
        new NsiItem(
            DisplayName: @"Evanston Parks & Recreation",
            Id: @"evanstonparksandrecreation-d1b6fa",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator:wikidata"] = @"Q110064075", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator"] = @"Evanston Parks & Recreation", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q110064075", },
            Terms: [@"evanston park district", @"evanston parks & recreation"]),
        new NsiItem(
            DisplayName: @"Forest Preserve District of Cook County",
            Id: @"forestpreservedistrictofcookcounty-d1b6fa",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator:wikidata"] = @"Q5469080", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator"] = @"Forest Preserve District of Cook County", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q5469080", },
            Terms: [@"forest preserve district of cook county"]),
        new NsiItem(
            DisplayName: @"Glencoe Park District",
            Id: @"glencoeparkdistrict-d1b6fa",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator:wikidata"] = @"Q112220906", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator"] = @"Glencoe Park District", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q112220906", },
            Terms: [@"glencoe park district"]),
        new NsiItem(
            DisplayName: @"Glenview Park District",
            Id: @"glenviewparkdistrict-d1b6fa",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator:wikidata"] = @"Q110064219", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator"] = @"Glenview Park District", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q110064219", },
            Terms: [@"glenview park district"]),
        new NsiItem(
            DisplayName: @"Lincolnwood Parks and Recreation",
            Id: @"lincolnwoodparksandrecreation-d1b6fa",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator:wikidata"] = @"Q110072249", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator"] = @"Lincolnwood Parks and Recreation", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q110072249", },
            Terms: [@"lincolnwood park district", @"lincolnwood parks and recreation"]),
        new NsiItem(
            DisplayName: @"Morton Grove Park District",
            Id: @"mortongroveparkdistrict-d1b6fa",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator:wikidata"] = @"Q110072677", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator"] = @"Morton Grove Park District", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q110072677", },
            Terms: [@"morton grove park district"]),
        new NsiItem(
            DisplayName: @"Niles Park District",
            Id: @"nilesparkdistrict-d1b6fa",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator:wikidata"] = @"Q110073017", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator"] = @"Niles Park District", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q110073017", },
            Terms: [@"niles park district"]),
        new NsiItem(
            DisplayName: @"Palatine Park District",
            Id: @"palatineparkdistrict-d1b6fa",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator:wikidata"] = @"Q112220961", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator"] = @"Palatine Park District", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q112220961", },
            Terms: [@"palatine park district"]),
        new NsiItem(
            DisplayName: @"Park District of Oak Park",
            Id: @"parkdistrictofoakpark-d1b6fa",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator:wikidata"] = @"Q112220982", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator"] = @"Park District of Oak Park", [@"operator:short"] = @"PDOP", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q112220982", },
            Terms: [@"park district of oak park", @"pdop"]),
        new NsiItem(
            DisplayName: @"Park Ridge Park District",
            Id: @"parkridgeparkdistrict-d1b6fa",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator:wikidata"] = @"Q112221067", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator"] = @"Park Ridge Park District", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q112221067", },
            Terms: [@"park ridge park district"]),
        new NsiItem(
            DisplayName: @"Skokie Park District",
            Id: @"skokieparkdistrict-d1b6fa",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator:wikidata"] = @"Q112228684", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator"] = @"Skokie Park District", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q112228684", },
            Terms: [@"skokie park district"]),
        new NsiItem(
            DisplayName: @"Village of South Holland",
            Id: @"villageofsouthholland-d1b6fa",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator:wikidata"] = @"Q404614", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator"] = @"Village of South Holland", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q404614", },
            Terms: [@"village of south holland"]),
        new NsiItem(
            DisplayName: @"Western Springs Park District",
            Id: @"westernspringsparkdistrict-d1b6fa",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator:wikidata"] = @"Q112228971", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator"] = @"Western Springs Park District", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q112228971", },
            Terms: [@"western springs park district"]),
        new NsiItem(
            DisplayName: @"Wilmette Park District",
            Id: @"wilmetteparkdistrict-d1b6fa",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator:wikidata"] = @"Q112228979", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator"] = @"Wilmette Park District", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q112228979", },
            Terms: [@"wilmette park district"]),
        new NsiItem(
            DisplayName: @"Winnetka Park District",
            Id: @"winnetkaparkdistrict-d1b6fa",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator:wikidata"] = @"Q112228982", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator"] = @"Winnetka Park District", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q112228982", },
            Terms: [@"winnetka park district"]),
        new NsiItem(
            DisplayName: @"Chicago Police Department",
            Id: @"chicagopolicedepartment-8853b4",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"surveillance", [@"operator:wikidata"] = @"Q1340186", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"surveillance", [@"operator"] = @"Chicago Police Department", [@"operator:wikidata"] = @"Q1340186", },
            Terms: [@"chicago police department"]),
        new NsiItem(
            DisplayName: @"Chicago Transit Authority",
            Id: @"chicagotransitauthority-bdf128",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q117309", [@"power"] = @"substation", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Chicago Transit Authority", [@"operator:short"] = @"CTA", [@"operator:wikidata"] = @"Q117309", [@"power"] = @"substation", },
            Terms: [@"chicago transit authority", @"cta"]),
        new NsiItem(
            DisplayName: @"Chicago Transit Authority",
            Id: @"chicagotransitauthority-f47ddb",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q117309", [@"power"] = @"transformer", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Chicago Transit Authority", [@"operator:short"] = @"CTA", [@"operator:wikidata"] = @"Q117309", [@"power"] = @"transformer", },
            Terms: [@"chicago transit authority", @"cta"]),
    ];
}
