// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'be-wlx.geojson'.</summary>
public static class NsiRegion_BE_WLX_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"Zone de Secours Luxembourg",
            Id: @"zonedesecoursluxembourg-1d5b26",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"fire_station", [@"operator:wikidata"] = @"Q3575880", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"fire_station", [@"operator"] = @"Zone de Secours Luxembourg", [@"operator:wikidata"] = @"Q3575880", },
            Terms: [@"zone de secours luxembourg"]),
        new NsiItem(
            DisplayName: @"Service public fédéral Justice",
            Id: @"servicepublicfederaljustice-923d72",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"prison", [@"operator:wikidata"] = @"Q1469956", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"prison", [@"operator"] = @"Service public fédéral Justice", [@"operator:fr"] = @"Service public fédéral Justice", [@"operator:nl"] = @"Federale Overheidsdienst Justitie", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q1469956", },
            Terms: [@"federale overheidsdienst justitie", @"service public fédéral justice"]),
        new NsiItem(
            DisplayName: @"IDELUX Environnement",
            Id: @"ideluxenvironnement-723093",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"recycling", [@"operator:wikidata"] = @"Q3146578", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"recycling", [@"operator"] = @"IDELUX Environnement", [@"operator:wikidata"] = @"Q3146578", },
            Terms: [@"idélux", @"idelux environnement"]),
        new NsiItem(
            DisplayName: @"RGTR",
            Id: @"rgtr-087930",
            Tags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"network:wikidata"] = @"Q3274984", [@"public_transport"] = @"platform", },
            AddTags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"highway"] = @"bus_stop", [@"network"] = @"RGTR", [@"network:wikidata"] = @"Q3274984", [@"public_transport"] = @"platform", },
            Terms: [@"rgtr"]),
        new NsiItem(
            DisplayName: @"TECX (Luxembourg)",
            Id: @"tecx-c29e65",
            Tags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"network:wikidata"] = @"Q3512080", [@"public_transport"] = @"platform", },
            AddTags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"highway"] = @"bus_stop", [@"network"] = @"TECX", [@"network:wikidata"] = @"Q3512080", [@"operator"] = @"TEC", [@"operator:wikidata"] = @"Q366922", [@"public_transport"] = @"platform", },
            Terms: [@"TECX (Luxembourg)", @"tec", @"tecx"]),
        new NsiItem(
            DisplayName: @"Société Nationale des Chemins de fer Luxembourgeois",
            Id: @"societenationaledescheminsdeferluxembourgeois-9294e8",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q525359", [@"railway"] = @"station", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Société Nationale des Chemins de fer Luxembourgeois", [@"network:short"] = @"CFL", [@"network:wikidata"] = @"Q525359", [@"public_transport"] = @"station", [@"railway"] = @"station", [@"train"] = @"yes", },
            Terms: [@"cfl", @"chemins de fer luxembourgeois", @"luxemburgische eisenbahnen", @"nationale gesellschaft der luxemburgischen eisenbahnen", @"société nationale des chemins de fer luxembourgeois"]),
        new NsiItem(
            DisplayName: @"RGTR",
            Id: @"rgtr-0ca4bf",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q3274984", [@"route"] = @"bus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"RGTR", [@"network:wikidata"] = @"Q3274984", [@"route"] = @"bus", [@"type"] = @"route", },
            Terms: [@"rgtr"]),
        new NsiItem(
            DisplayName: @"TECX (Luxembourg)",
            Id: @"tecx-57636e",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q3512080", [@"route"] = @"bus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"TECX", [@"network:wikidata"] = @"Q3512080", [@"operator"] = @"TEC", [@"operator:wikidata"] = @"Q366922", [@"route"] = @"bus", [@"type"] = @"route", },
            Terms: [@"TECX (Luxembourg)", @"tec", @"tecx"]),
        new NsiItem(
            DisplayName: @"Société Nationale des Chemins de fer Luxembourgeois",
            Id: @"societenationaledescheminsdeferluxembourgeois-aaa49e",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q525359", [@"route"] = @"train", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Société Nationale des Chemins de fer Luxembourgeois", [@"network:short"] = @"CFL", [@"network:wikidata"] = @"Q525359", [@"route"] = @"train", [@"type"] = @"route", },
            Terms: [@"cfl", @"chemins de fer luxembourgeois", @"luxemburgische eisenbahnen", @"nationale gesellschaft der luxemburgischen eisenbahnen", @"société nationale des chemins de fer luxembourgeois"]),
    ];
}
