// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'br-ro.geojson'.</summary>
public static class NsiRegion_BR_RO_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"Polícia Militar do Estado de Rondônia",
            Id: @"policiamilitardoestadoderondonia-200a68",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"police", [@"operator:wikidata"] = @"Q10351021", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"police", [@"operator"] = @"Polícia Militar do Estado de Rondônia", [@"operator:short"] = @"PMRO", [@"operator:wikidata"] = @"Q10351021", },
            Terms: [@"pmro", @"polícia militar do estado de rondônia"]),
        new NsiItem(
            DisplayName: @"Energisa Rondônia",
            Id: @"energisarondonia-1bb79e",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q10271730", [@"power"] = @"line", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Energisa Rondônia", [@"operator:wikidata"] = @"Q10271730", [@"power"] = @"line", },
            Terms: [@"energisa rondônia"]),
        new NsiItem(
            DisplayName: @"Energisa Rondônia",
            Id: @"energisarondonia-c5142b",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q10271730", [@"power"] = @"minor_line", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Energisa Rondônia", [@"operator:wikidata"] = @"Q10271730", [@"power"] = @"minor_line", },
            Terms: [@"energisa rondônia"]),
        new NsiItem(
            DisplayName: @"Energisa Rondônia",
            Id: @"energisarondonia-abf7ba",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q10271730", [@"power"] = @"pole", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Energisa Rondônia", [@"operator:wikidata"] = @"Q10271730", [@"power"] = @"pole", },
            Terms: [@"energisa rondônia"]),
        new NsiItem(
            DisplayName: @"Energisa Rondônia",
            Id: @"energisarondonia-31617d",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q10271730", [@"power"] = @"substation", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Energisa Rondônia", [@"operator:wikidata"] = @"Q10271730", [@"power"] = @"substation", },
            Terms: [@"energisa rondônia"]),
        new NsiItem(
            DisplayName: @"Energisa Rondônia",
            Id: @"energisarondonia-c6e174",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q10271730", [@"power"] = @"tower", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Energisa Rondônia", [@"operator:wikidata"] = @"Q10271730", [@"power"] = @"tower", },
            Terms: [@"energisa rondônia"]),
        new NsiItem(
            DisplayName: @"Energisa Rondônia",
            Id: @"energisarondonia-5d2728",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q10271730", [@"power"] = @"transformer", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Energisa Rondônia", [@"operator:wikidata"] = @"Q10271730", [@"power"] = @"transformer", },
            Terms: [@"energisa rondônia"]),
    ];
}
