// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'mx-chh.geojson'.</summary>
public static class NsiRegion_MX_CHH_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"Tacotote",
            Id: @"tacotote-fcf6d2",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"restaurant", [@"brand:wikidata"] = @"Q16992316", [@"cuisine"] = @"mexican", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"restaurant", [@"brand"] = @"Tacotote", [@"brand:wikidata"] = @"Q16992316", [@"cuisine"] = @"mexican", [@"name"] = @"Tacotote", },
            Terms: [@"el taco tote", @"tacotote"]),
    ];
}
