// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'es-bu.geojson'.</summary>
public static class NsiRegion_ES_BU_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"SACYL",
            Id: @"sacyl-ce0d6c",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"clinic", [@"operator:wikidata"] = @"Q6116740", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"clinic", [@"healthcare"] = @"clinic", [@"operator"] = @"SACYL", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q6116740", },
            Terms: [@"sacyl"]),
        new NsiItem(
            DisplayName: @"SACYL",
            Id: @"sacyl-850ed8",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"hospital", [@"operator:wikidata"] = @"Q6116740", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"hospital", [@"healthcare"] = @"hospital", [@"operator"] = @"SACYL", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q6116740", },
            Terms: [@"sacyl"]),
        new NsiItem(
            DisplayName: @"Ayuntamiento de Villarcayo de Merindad de Castilla la Vieja",
            Id: @"ayuntamientodevillarcayodemerindaddecastillalavieja-109043",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"recycling", [@"operator:wikidata"] = @"Q60052649", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"recycling", [@"operator"] = @"Ayuntamiento de Villarcayo de Merindad de Castilla la Vieja", [@"operator:wikidata"] = @"Q60052649", },
            Terms: [@"ayto villarcayo mcv", @"ayuntamiento de villarcayo de merindad de castilla la vieja", @"ayuntamiento de villarcayo mcv"]),
        new NsiItem(
            DisplayName: @"Consejería de Educación de la Junta de Castilla y León",
            Id: @"consejeriadeeducaciondelajuntadecastillayleon-5f247a",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q30297363", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Consejería de Educación de la Junta de Castilla y León", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q30297363", },
            Terms: [@"consejería de educación de la junta de castilla y león"]),
        new NsiItem(
            DisplayName: @"Junta de Castilla y León",
            Id: @"juntadecastillayleon-5f247a",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q3314606", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Junta de Castilla y León", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q3314606", },
            Terms: [@"junta de castilla y león"]),
        new NsiItem(
            DisplayName: @"Junta de Castilla y León",
            Id: @"juntadecastillayleon-ce34c9",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"social_facility", [@"operator:wikidata"] = @"Q3314606", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"social_facility", [@"operator"] = @"Junta de Castilla y León", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q3314606", },
            Terms: [@"junta de castilla y león"]),
        new NsiItem(
            DisplayName: @"Junta de Castilla y León",
            Id: @"juntadecastillayleon-4cd933",
            Tags: new Dictionary<string, string> { [@"office"] = @"government", [@"operator:wikidata"] = @"Q3314606", },
            AddTags: new Dictionary<string, string> { [@"office"] = @"government", [@"operator"] = @"Junta de Castilla y León", [@"operator:wikidata"] = @"Q3314606", },
            Terms: [@"junta de castilla y león"]),
        new NsiItem(
            DisplayName: @"Viesgo Distribución Eléctrica",
            Id: @"viesgodistribucionelectrica-3aff86",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q5829004", [@"power"] = @"line", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Viesgo Distribución Eléctrica", [@"operator:wikidata"] = @"Q5829004", [@"power"] = @"line", },
            Terms: [@"viesgo", @"viesgo distribución eléctrica", @"viesgo distribución eléctrica, s.l"]),
        new NsiItem(
            DisplayName: @"Viesgo Distribución Eléctrica",
            Id: @"viesgodistribucionelectrica-cf4a46",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q5829004", [@"power"] = @"minor_line", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Viesgo Distribución Eléctrica", [@"operator:wikidata"] = @"Q5829004", [@"power"] = @"minor_line", },
            Terms: [@"viesgo", @"viesgo distribución eléctrica", @"viesgo distribución eléctrica, s.l"]),
        new NsiItem(
            DisplayName: @"Viesgo Distribución Eléctrica",
            Id: @"viesgodistribucionelectrica-2771ba",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q5829004", [@"power"] = @"pole", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Viesgo Distribución Eléctrica", [@"operator:wikidata"] = @"Q5829004", [@"power"] = @"pole", },
            Terms: [@"viesgo", @"viesgo distribución eléctrica", @"viesgo distribución eléctrica, s.l"]),
        new NsiItem(
            DisplayName: @"Viesgo Distribución Eléctrica",
            Id: @"viesgodistribucionelectrica-f5fe9f",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q5829004", [@"power"] = @"substation", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Viesgo Distribución Eléctrica", [@"operator:wikidata"] = @"Q5829004", [@"power"] = @"substation", },
            Terms: [@"viesgo", @"viesgo distribución eléctrica"]),
        new NsiItem(
            DisplayName: @"Viesgo Distribución Eléctrica",
            Id: @"viesgodistribucionelectrica-77857c",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q5829004", [@"power"] = @"tower", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Viesgo Distribución Eléctrica", [@"operator:wikidata"] = @"Q5829004", [@"power"] = @"tower", },
            Terms: [@"viesgo", @"viesgo distribución eléctrica", @"viesgo distribución eléctrica, s.l"]),
        new NsiItem(
            DisplayName: @"Viesgo Distribución Eléctrica",
            Id: @"viesgodistribucionelectrica-9029f9",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q5829004", [@"power"] = @"transformer", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Viesgo Distribución Eléctrica", [@"operator:wikidata"] = @"Q5829004", [@"power"] = @"transformer", },
            Terms: [@"viesgo", @"viesgo distribución eléctrica"]),
        new NsiItem(
            DisplayName: @"Transporte urbano de Burgos",
            Id: @"transporteurbanodeburgos-804e67",
            Tags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"network:wikidata"] = @"Q6391113", [@"public_transport"] = @"platform", },
            AddTags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"highway"] = @"bus_stop", [@"network"] = @"Transporte urbano de Burgos", [@"network:wikidata"] = @"Q6391113", [@"operator"] = @"Servicio Municipalizado de Movilidad y Transportes", [@"operator:short"] = @"SMYT", [@"public_transport"] = @"platform", },
            Terms: [@"servicio municipalizado de movilidad y transportes", @"smyt", @"transporte urbano de burgos"]),
        new NsiItem(
            DisplayName: @"Transporte urbano de Burgos",
            Id: @"transporteurbanodeburgos-751492",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q6391113", [@"route"] = @"bus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Transporte urbano de Burgos", [@"network:wikidata"] = @"Q6391113", [@"operator"] = @"Servicio Municipalizado de Movilidad y Transportes", [@"operator:short"] = @"SMYT", [@"route"] = @"bus", [@"type"] = @"route", },
            Terms: [@"servicio municipalizado de movilidad y transportes", @"smyt", @"transporte urbano de burgos"]),
    ];
}
