// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'pt-18.geojson'.</summary>
public static class NsiRegion_PT_18_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"BORA!",
            Id: @"bora-60b39f",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bicycle_rental", [@"brand:wikidata"] = @"Q135900830", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bicycle_rental", [@"brand"] = @"BORA!", [@"brand:wikidata"] = @"Q135900830", [@"name"] = @"BORA!", [@"network"] = @"BORA!", [@"network:wikidata"] = @"Q135900830", [@"operator"] = @"CIM Viseu Dão Lafões", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q265402", },
            Terms: [@"bora!", @"cim viseu dão lafões"]),
        new NsiItem(
            DisplayName: @"Agrupamento de Escolas de Tondela Cândido de Figueiredo",
            Id: @"agrupamentodeescolasdetondelacandidodefigueiredo-64d503",
            Tags: new Dictionary<string, string> { [@"education"] = @"kindergarten", [@"operator:wikidata"] = @"Q131463152", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"kindergarten", [@"education"] = @"kindergarten", [@"operator"] = @"Agrupamento de Escolas de Tondela Cândido de Figueiredo", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q131463152", },
            Terms: [@"agrupamento de escolas de tondela cândido de figueiredo"]),
        new NsiItem(
            DisplayName: @"Agrupamento de Escolas de Castro Daire",
            Id: @"agrupamentodeescolasdecastrodaire-349a25",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q131446689", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Agrupamento de Escolas de Castro Daire", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q131446689", },
            Terms: [@"agrupamento de escolas de castro daire"]),
        new NsiItem(
            DisplayName: @"Agrupamento de Escolas Grão Vasco",
            Id: @"agrupamentodeescolasgraovasco-349a25",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q131446712", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Agrupamento de Escolas Grão Vasco", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q131446712", },
            Terms: [@"agrupamento de escolas grão vasco", @"agrupamento de escolas grão vasco, viseu"]),
        new NsiItem(
            DisplayName: @"Agrupamento de Escolas Infante D. Henrique (Viseu)",
            Id: @"agrupamentodeescolasinfantedhenrique-349a25",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q131446714", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Agrupamento de Escolas Infante D. Henrique", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q131446714", },
            Terms: [@"Agrupamento de Escolas Infante D. Henrique (Viseu)", @"agrupamento de escolas infante d. henrique", @"agrupamento de escolas infante d. henrique, repeses, viseu"]),
        new NsiItem(
            DisplayName: @"Agrupamento de Escolas Viseu Norte",
            Id: @"agrupamentodeescolasviseunorte-349a25",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q131446727", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Agrupamento de Escolas Viseu Norte", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q131446727", },
            Terms: [@"agrupamento de escolas viseu norte"]),
        new NsiItem(
            DisplayName: @"MobiViseuDãoLafões",
            Id: @"mobiviseudaolafoes-0e98a5",
            Tags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"network:wikidata"] = @"Q134717606", [@"public_transport"] = @"platform", },
            AddTags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"highway"] = @"bus_stop", [@"network"] = @"MobiViseuDãoLafões", [@"network:wikidata"] = @"Q134717606", [@"public_transport"] = @"platform", },
            Terms: [@"mobiviseudãolafões"]),
        new NsiItem(
            DisplayName: @"MUV",
            Id: @"muv-9b939b",
            Tags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"network:wikidata"] = @"Q63247817", [@"public_transport"] = @"platform", },
            AddTags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"highway"] = @"bus_stop", [@"network"] = @"MUV", [@"network:wikidata"] = @"Q63247817", [@"public_transport"] = @"platform", },
            Terms: [@"muv"]),
        new NsiItem(
            DisplayName: @"Transportes Públicos de Lamego",
            Id: @"transportespublicosdelamego-a22ca9",
            Tags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"network:wikidata"] = @"Q133523138", [@"public_transport"] = @"platform", },
            AddTags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"highway"] = @"bus_stop", [@"network"] = @"Transportes Públicos de Lamego", [@"network:wikidata"] = @"Q133523138", [@"public_transport"] = @"platform", },
            Terms: [@"transportes públicos de lamego"]),
        new NsiItem(
            DisplayName: @"MobiViseuDãoLafões",
            Id: @"mobiviseudaolafoes-ff232b",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q134717606", [@"route"] = @"bus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"MobiViseuDãoLafões", [@"network:wikidata"] = @"Q134717606", [@"route"] = @"bus", [@"type"] = @"route", },
            Terms: [@"mobiviseudãolafões"]),
        new NsiItem(
            DisplayName: @"MUV",
            Id: @"muv-fdc094",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q63247817", [@"route"] = @"bus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"MUV", [@"network:wikidata"] = @"Q63247817", [@"route"] = @"bus", [@"type"] = @"route", },
            Terms: [@"muv"]),
        new NsiItem(
            DisplayName: @"Transportes Públicos de Lamego",
            Id: @"transportespublicosdelamego-4f8cb1",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q133523138", [@"route"] = @"bus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Transportes Públicos de Lamego", [@"network:wikidata"] = @"Q133523138", [@"route"] = @"bus", [@"type"] = @"route", },
            Terms: [@"transportes públicos de lamego"]),
    ];
}
