// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'ch-ge.geojson'.</summary>
public static class NsiRegion_CH_GE_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"Banque Cantonale de Genève",
            Id: @"banquecantonaledegeneve-097ff6",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand:wikidata"] = @"Q650629", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand"] = @"Banque Cantonale de Genève", [@"brand:wikidata"] = @"Q650629", [@"operator"] = @"Banque Cantonale de Genève", [@"operator:wikidata"] = @"Q650629", },
            Terms: [@"banque cantonale de genève"]),
        new NsiItem(
            DisplayName: @"Banque Cantonale de Genève",
            Id: @"banquecantonaledegeneve-e338fc",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand:wikidata"] = @"Q650629", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand"] = @"Banque Cantonale de Genève", [@"brand:wikidata"] = @"Q650629", [@"name"] = @"Banque Cantonale de Genève", [@"short_name"] = @"BCGE", },
            Terms: [@"banque cantonale de genève", @"bcge"]),
        new NsiItem(
            DisplayName: @"Ville de Genève",
            Id: @"villedegeneve-68bbbd",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"library", [@"operator:wikidata"] = @"Q71", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"library", [@"operator"] = @"Ville de Genève", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q71", },
            Terms: [@"ville de genève"]),
        new NsiItem(
            DisplayName: @"Ville de Genève",
            Id: @"villedegeneve-4d3bc7",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"recycling", [@"operator:wikidata"] = @"Q71", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"recycling", [@"operator"] = @"Ville de Genève", [@"operator:wikidata"] = @"Q71", },
            Terms: [@"ville de genève"]),
        new NsiItem(
            DisplayName: @"Gaznat SA",
            Id: @"gaznatsa-f9727e",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"pipeline", [@"operator:wikidata"] = @"Q1496670", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"pipeline", [@"operator"] = @"Gaznat SA", [@"operator:wikidata"] = @"Q1496670", },
            Terms: [@"gaznat sa"]),
        new NsiItem(
            DisplayName: @"SAPPRO",
            Id: @"sappro-1b588c",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"pipeline", [@"operator:wikidata"] = @"Q105037820", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"pipeline", [@"operator"] = @"SAPPRO", [@"operator:wikidata"] = @"Q105037820", },
            Terms: [@"sappro"]),
        new NsiItem(
            DisplayName: @"Ville de Genève",
            Id: @"villedegeneve-9dfc74",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"surveillance", [@"operator:wikidata"] = @"Q71", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"surveillance", [@"operator"] = @"Ville de Genève", [@"operator:wikidata"] = @"Q71", },
            Terms: [@"ville de genève", @"ville/etat de genève"]),
        new NsiItem(
            DisplayName: @"Gaznat SA",
            Id: @"gaznatsa-17e5f5",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q1496670", [@"pipeline"] = @"substation", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Gaznat SA", [@"operator:wikidata"] = @"Q1496670", [@"pipeline"] = @"substation", },
            Terms: [@"gaznat sa"]),
        new NsiItem(
            DisplayName: @"SAPPRO",
            Id: @"sappro-3e2612",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q105037820", [@"pipeline"] = @"substation", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"SAPPRO", [@"operator:wikidata"] = @"Q105037820", [@"pipeline"] = @"substation", },
            Terms: [@"sappro"]),
        new NsiItem(
            DisplayName: @"CERN",
            Id: @"cern-68daa6",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q42944", [@"power"] = @"line", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"CERN", [@"operator:wikidata"] = @"Q42944", [@"power"] = @"line", },
            Terms: [@"cern"]),
        new NsiItem(
            DisplayName: @"SIG",
            Id: @"sig-27ed5d",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q3480520", [@"power"] = @"line", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"SIG", [@"operator:wikidata"] = @"Q3480520", [@"power"] = @"line", },
            Terms: [@"sig"]),
        new NsiItem(
            DisplayName: @"CERN",
            Id: @"cern-db1f4d",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q42944", [@"power"] = @"minor_line", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"CERN", [@"operator:wikidata"] = @"Q42944", [@"power"] = @"minor_line", },
            Terms: [@"cern"]),
        new NsiItem(
            DisplayName: @"SIG",
            Id: @"sig-28e447",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q3480520", [@"power"] = @"minor_line", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"SIG", [@"operator:wikidata"] = @"Q3480520", [@"power"] = @"minor_line", },
            Terms: [@"sig"]),
        new NsiItem(
            DisplayName: @"CERN",
            Id: @"cern-b7887d",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q42944", [@"power"] = @"pole", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"CERN", [@"operator:wikidata"] = @"Q42944", [@"power"] = @"pole", },
            Terms: [@"cern"]),
        new NsiItem(
            DisplayName: @"SIG",
            Id: @"sig-3c01da",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q3480520", [@"power"] = @"pole", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"SIG", [@"operator:wikidata"] = @"Q3480520", [@"power"] = @"pole", },
            Terms: [@"sig"]),
        new NsiItem(
            DisplayName: @"CERN",
            Id: @"cern-ed9688",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q42944", [@"power"] = @"tower", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"CERN", [@"operator:wikidata"] = @"Q42944", [@"power"] = @"tower", },
            Terms: [@"cern"]),
        new NsiItem(
            DisplayName: @"SIG",
            Id: @"sig-c495cc",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q3480520", [@"power"] = @"tower", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"SIG", [@"operator:wikidata"] = @"Q3480520", [@"power"] = @"tower", },
            Terms: [@"sig"]),
        new NsiItem(
            DisplayName: @"Cars Région Haute-Savoie",
            Id: @"carsregionhautesavoie-32e168",
            Tags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"network:wikidata"] = @"Q3456845", [@"public_transport"] = @"platform", },
            AddTags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"highway"] = @"bus_stop", [@"network"] = @"Cars Région Haute-Savoie", [@"network:wikidata"] = @"Q3456845", [@"public_transport"] = @"platform", },
            Terms: [@"cars région haute-savoie"]),
        new NsiItem(
            DisplayName: @"Unireso",
            Id: @"unireso-8be2d1",
            Tags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"network:wikidata"] = @"Q1312883", [@"public_transport"] = @"platform", },
            AddTags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"highway"] = @"bus_stop", [@"network"] = @"Unireso", [@"network:wikidata"] = @"Q1312883", [@"public_transport"] = @"platform", },
            Terms: [@"ctge", @"tarifverbund genf", @"unireso"]),
        new NsiItem(
            DisplayName: @"Léman Express",
            Id: @"lemanexpress-0c1f90",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q7885274", [@"railway"] = @"station", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Léman Express", [@"network:short"] = @"LEX", [@"network:wikidata"] = @"Q7885274", [@"public_transport"] = @"station", [@"railway"] = @"station", [@"train"] = @"yes", },
            Terms: [@"léman express", @"lex"]),
        new NsiItem(
            DisplayName: @"TGV",
            Id: @"tgv-6ad4d6",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q129337", [@"railway"] = @"station", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"TGV", [@"network:wikidata"] = @"Q129337", [@"operator"] = @"SNCF Voyageurs", [@"operator:wikidata"] = @"Q93090957", [@"public_transport"] = @"station", [@"railway"] = @"station", [@"train"] = @"yes", },
            Terms: [@"sncf voyageurs", @"tgv"]),
        new NsiItem(
            DisplayName: @"Unireso",
            Id: @"unireso-14b1d4",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q1312883", [@"railway"] = @"station", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Unireso", [@"network:wikidata"] = @"Q1312883", [@"public_transport"] = @"station", [@"railway"] = @"station", [@"train"] = @"yes", },
            Terms: [@"tarifverbund genf", @"unireso"]),
        new NsiItem(
            DisplayName: @"Unireso",
            Id: @"unireso-d9e42c",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q1312883", [@"railway"] = @"tram_stop", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Unireso", [@"network:wikidata"] = @"Q1312883", [@"railway"] = @"tram_stop", },
            Terms: [@"unireso"]),
        new NsiItem(
            DisplayName: @"Cars Région Haute-Savoie",
            Id: @"carsregionhautesavoie-5ab278",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q3456845", [@"route"] = @"bus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Cars Région Haute-Savoie", [@"network:wikidata"] = @"Q3456845", [@"route"] = @"bus", [@"type"] = @"route", },
            Terms: [@"cars région haute-savoie"]),
        new NsiItem(
            DisplayName: @"Unireso",
            Id: @"unireso-0b3767",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q1312883", [@"route"] = @"bus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Unireso", [@"network:wikidata"] = @"Q1312883", [@"route"] = @"bus", [@"type"] = @"route", },
            Terms: [@"ctge", @"tarifverbund genf", @"unireso"]),
        new NsiItem(
            DisplayName: @"Léman Express",
            Id: @"lemanexpress-722408",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q7885274", [@"route"] = @"train", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Léman Express", [@"network:short"] = @"LEX", [@"network:wikidata"] = @"Q7885274", [@"route"] = @"train", [@"type"] = @"route", },
            Terms: [@"léman express", @"lex"]),
        new NsiItem(
            DisplayName: @"TGV",
            Id: @"tgv-0fcd6a",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q129337", [@"route"] = @"train", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"TGV", [@"network:wikidata"] = @"Q129337", [@"operator"] = @"SNCF Voyageurs", [@"operator:wikidata"] = @"Q93090957", [@"route"] = @"train", [@"type"] = @"route", },
            Terms: [@"sncf voyageurs", @"tgv"]),
        new NsiItem(
            DisplayName: @"Unireso",
            Id: @"unireso-c0433d",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q1312883", [@"route"] = @"train", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Unireso", [@"network:wikidata"] = @"Q1312883", [@"route"] = @"train", [@"type"] = @"route", },
            Terms: [@"tarifverbund genf", @"unireso"]),
        new NsiItem(
            DisplayName: @"Unireso",
            Id: @"unireso-e983cc",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q1312883", [@"route"] = @"tram", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Unireso", [@"network:wikidata"] = @"Q1312883", [@"route"] = @"tram", [@"type"] = @"route", },
            Terms: [@"unireso"]),
        new NsiItem(
            DisplayName: @"Unireso",
            Id: @"unireso-9f25ab",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q1312883", [@"route"] = @"trolleybus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Unireso", [@"network:wikidata"] = @"Q1312883", [@"route"] = @"trolleybus", [@"type"] = @"route", },
            Terms: [@"unireso"]),
    ];
}
