// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'northern cyprus'.</summary>
public static class NsiRegion_NORTHERN_CYPRUS
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"Alpet",
            Id: @"alpet-c19ddd",
            Tags: new Dictionary<string, string> { [@"advertising"] = @"totem", [@"brand:wikidata"] = @"Q62131561", },
            AddTags: new Dictionary<string, string> { [@"advertising"] = @"totem", [@"brand"] = @"Alpet", [@"brand:wikidata"] = @"Q62131561", },
            Terms: [@"alpet"]),
        new NsiItem(
            DisplayName: @"K-Pet",
            Id: @"kpet-7f977f",
            Tags: new Dictionary<string, string> { [@"advertising"] = @"totem", [@"brand:wikidata"] = @"Q6023970", },
            AddTags: new Dictionary<string, string> { [@"advertising"] = @"totem", [@"brand"] = @"K-Pet", [@"brand:wikidata"] = @"Q6023970", },
            Terms: [@"k-pet"]),
        new NsiItem(
            DisplayName: @"Akfinans Bank",
            Id: @"akfinansbank-a0e164",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand:wikidata"] = @"Q31188674", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand"] = @"Akfinans Bank", [@"brand:wikidata"] = @"Q31188674", [@"operator"] = @"Akfinans Bank", [@"operator:wikidata"] = @"Q31188674", },
            Terms: [@"akfinans bank"]),
        new NsiItem(
            DisplayName: @"Asbank",
            Id: @"asbank-a0e164",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand:wikidata"] = @"Q31188675", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand"] = @"Asbank", [@"brand:wikidata"] = @"Q31188675", [@"operator"] = @"Asbank", [@"operator:wikidata"] = @"Q31188675", },
            Terms: [@"asbank"]),
        new NsiItem(
            DisplayName: @"CapitalBank (TRNC)",
            Id: @"capitalbank-a0e164",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand:wikidata"] = @"Q31188679", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand"] = @"CapitalBank", [@"brand:wikidata"] = @"Q31188679", [@"operator"] = @"CapitalBank", [@"operator:wikidata"] = @"Q31188679", },
            Terms: [@"CapitalBank (TRNC)", @"capitalbank"]),
        new NsiItem(
            DisplayName: @"Creditwest Bank",
            Id: @"creditwestbank-a0e164",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand:wikidata"] = @"Q31188678", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand"] = @"Creditwest Bank", [@"brand:wikidata"] = @"Q31188678", [@"operator"] = @"Creditwest Bank", [@"operator:wikidata"] = @"Q31188678", },
            Terms: [@"creditwest bank"]),
        new NsiItem(
            DisplayName: @"İktisatbank",
            Id: @"iktisatbank-a0e164",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand:wikidata"] = @"Q21523788", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand"] = @"İktisatbank", [@"brand:wikidata"] = @"Q21523788", [@"operator"] = @"İktisatbank", [@"operator:wikidata"] = @"Q21523788", },
            Terms: [@"İktisatbank", @"i̇ktisatbank"]),
        new NsiItem(
            DisplayName: @"Koopbank",
            Id: @"koopbank-a0e164",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand:wikidata"] = @"Q31188681", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand"] = @"Koopbank", [@"brand:wikidata"] = @"Q31188681", [@"operator"] = @"Koopbank", [@"operator:wikidata"] = @"Q31188681", },
            Terms: [@"kıbrıs türk kooperatif merkez bankası", @"koopbank"]),
        new NsiItem(
            DisplayName: @"Limasol Türk Kooperatif Bankası",
            Id: @"limasolturkkooperatifbankasi-a0e164",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand:wikidata"] = @"Q31188702", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand"] = @"Limasol Türk Kooperatif Bankası", [@"brand:wikidata"] = @"Q31188702", [@"operator"] = @"Limasol Türk Kooperatif Bankası", [@"operator:wikidata"] = @"Q31188702", },
            Terms: [@"limasol türk kooperatif bankası"]),
        new NsiItem(
            DisplayName: @"Near East Bank",
            Id: @"neareastbank-a0e164",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand:wikidata"] = @"Q31188683", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand"] = @"Near East Bank", [@"brand:wikidata"] = @"Q31188683", [@"operator"] = @"Near East Bank", [@"operator:wikidata"] = @"Q31188683", },
            Terms: [@"near east bank"]),
        new NsiItem(
            DisplayName: @"NovaBank",
            Id: @"novabank-a0e164",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand:wikidata"] = @"Q61072074", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand"] = @"NovaBank", [@"brand:wikidata"] = @"Q61072074", [@"operator"] = @"NovaBank", [@"operator:wikidata"] = @"Q61072074", },
            Terms: [@"novabank"]),
        new NsiItem(
            DisplayName: @"Şekerbank",
            Id: @"sekerbank-254ed3",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand:wikidata"] = @"Q6088369", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand"] = @"Şekerbank", [@"brand:wikidata"] = @"Q6088369", [@"operator"] = @"Şekerbank", [@"operator:wikidata"] = @"Q6088369", },
            Terms: [@"şekerbank"]),
        new NsiItem(
            DisplayName: @"TEB",
            Id: @"teb-254ed3",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand:wikidata"] = @"Q7862447", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand"] = @"TEB", [@"brand:wikidata"] = @"Q7862447", [@"operator"] = @"TEB", [@"operator:wikidata"] = @"Q7862447", },
            Terms: [@"teb", @"türk ekonomi bankası"]),
        new NsiItem(
            DisplayName: @"Türk Bankası",
            Id: @"turkbankasi-a0e164",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand:wikidata"] = @"Q31188692", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand"] = @"Türk Bankası", [@"brand:wikidata"] = @"Q31188692", [@"operator"] = @"Türk Bankası", [@"operator:wikidata"] = @"Q31188692", },
            Terms: [@"türk bankası"]),
        new NsiItem(
            DisplayName: @"Ziraat Bankası",
            Id: @"ziraatbankasi-254ed3",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand:wikidata"] = @"Q696003", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand"] = @"Ziraat Bankası", [@"brand:wikidata"] = @"Q696003", [@"operator"] = @"Ziraat Bankası", [@"operator:wikidata"] = @"Q696003", },
            Terms: [@"t.c. ziraat bankası", @"ziraat bankası"]),
        new NsiItem(
            DisplayName: @"იშბანკი",
            Id: @"isbank-a7d7a7",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand:wikidata"] = @"Q909613", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"bic"] = @"ISBKGE22", [@"brand"] = @"იშბანკი", [@"brand:en"] = @"IsBank", [@"brand:ka"] = @"იშბანკი", [@"brand:ru"] = @"ИшБанк", [@"brand:tr"] = @"İşBank", [@"brand:wikidata"] = @"Q909613", [@"operator"] = @"იშბანკი", [@"operator:ka"] = @"სს იშბანკი საქართველო", [@"operator:wikidata"] = @"Q909613", },
            Terms: [@"isbank", @"i̇şbank", @"ишбанк", @"იშბანკი", @"სს იშბანკი საქართველო"]),
        new NsiItem(
            DisplayName: @"Akfinans Bank",
            Id: @"akfinansbank-c9effc",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand:wikidata"] = @"Q31188674", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand"] = @"Akfinans Bank", [@"brand:wikidata"] = @"Q31188674", [@"name"] = @"Akfinans Bank", },
            Terms: [@"akfinans bank"]),
        new NsiItem(
            DisplayName: @"Asbank",
            Id: @"asbank-c9effc",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand:wikidata"] = @"Q31188675", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand"] = @"Asbank", [@"brand:wikidata"] = @"Q31188675", [@"name"] = @"Asbank", },
            Terms: [@"asbank"]),
        new NsiItem(
            DisplayName: @"CapitalBank (TRNC)",
            Id: @"capitalbank-c9effc",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand:wikidata"] = @"Q31188679", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand"] = @"CapitalBank", [@"brand:wikidata"] = @"Q31188679", [@"name"] = @"CapitalBank", },
            Terms: [@"CapitalBank (TRNC)", @"capitalbank"]),
        new NsiItem(
            DisplayName: @"Creditwest Bank",
            Id: @"creditwestbank-c9effc",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand:wikidata"] = @"Q31188678", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand"] = @"Creditwest Bank", [@"brand:wikidata"] = @"Q31188678", [@"name"] = @"Creditwest Bank", },
            Terms: [@"creditwest bank"]),
        new NsiItem(
            DisplayName: @"İktisatbank",
            Id: @"iktisatbank-c9effc",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand:wikidata"] = @"Q21523788", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand"] = @"İktisatbank", [@"brand:wikidata"] = @"Q21523788", [@"name"] = @"İktisatbank", },
            Terms: [@"İktisatbank", @"i̇ktisatbank"]),
        new NsiItem(
            DisplayName: @"Koopbank",
            Id: @"koopbank-c9effc",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand:wikidata"] = @"Q31188681", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand"] = @"Koopbank", [@"brand:wikidata"] = @"Q31188681", [@"name"] = @"Koopbank", },
            Terms: [@"kıbrıs türk kooperatif merkez bankası", @"koopbank"]),
        new NsiItem(
            DisplayName: @"Limasol Türk Kooperatif Bankası",
            Id: @"limasolturkkooperatifbankasi-c9effc",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand:wikidata"] = @"Q31188702", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand"] = @"Limasol Türk Kooperatif Bankası", [@"brand:wikidata"] = @"Q31188702", [@"name"] = @"Limasol Türk Kooperatif Bankası", },
            Terms: [@"limasol türk kooperatif bankası"]),
        new NsiItem(
            DisplayName: @"Near East Bank",
            Id: @"neareastbank-c9effc",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand:wikidata"] = @"Q31188683", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand"] = @"Near East Bank", [@"brand:wikidata"] = @"Q31188683", [@"name"] = @"Near East Bank", },
            Terms: [@"near east bank"]),
        new NsiItem(
            DisplayName: @"NovaBank",
            Id: @"novabank-c9effc",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand:wikidata"] = @"Q61072074", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand"] = @"NovaBank", [@"brand:wikidata"] = @"Q61072074", [@"name"] = @"NovaBank", },
            Terms: [@"novabank"]),
        new NsiItem(
            DisplayName: @"Şekerbank",
            Id: @"sekerbank-f79a7c",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand:wikidata"] = @"Q6088369", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand"] = @"Şekerbank", [@"brand:wikidata"] = @"Q6088369", [@"name"] = @"Şekerbank", },
            Terms: [@"şekerbank"]),
        new NsiItem(
            DisplayName: @"TEB",
            Id: @"teb-f79a7c",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand:wikidata"] = @"Q7862447", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand"] = @"TEB", [@"brand:wikidata"] = @"Q7862447", [@"name"] = @"TEB", },
            Terms: [@"teb", @"türk ekonomi bankası"]),
        new NsiItem(
            DisplayName: @"Türk Bankası",
            Id: @"turkbankasi-c9effc",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand:wikidata"] = @"Q31188692", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand"] = @"Türk Bankası", [@"brand:wikidata"] = @"Q31188692", [@"name"] = @"Türk Bankası", },
            Terms: [@"türk bankası"]),
        new NsiItem(
            DisplayName: @"Ziraat Bankası",
            Id: @"ziraatbankasi-f79a7c",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand:wikidata"] = @"Q696003", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand"] = @"Ziraat Bankası", [@"brand:wikidata"] = @"Q696003", [@"name"] = @"Ziraat Bankası", },
            Terms: [@"t.c. ziraat bankası", @"ziraat bankası"]),
        new NsiItem(
            DisplayName: @"იშბანკი",
            Id: @"isbank-088e7d",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand:wikidata"] = @"Q909613", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"bic"] = @"ISBKGE22", [@"brand"] = @"იშბანკი", [@"brand:en"] = @"IsBank", [@"brand:ka"] = @"იშბანკი", [@"brand:ru"] = @"ИшБанк", [@"brand:tr"] = @"İşBank", [@"brand:wikidata"] = @"Q909613", [@"name"] = @"იშბანკი", [@"name:en"] = @"IsBank", [@"name:ka"] = @"იშბანკი", [@"name:ru"] = @"ИшБанк", [@"name:tr"] = @"İşBank", [@"operator"] = @"სს იშბანკი საქართველო", [@"operator:ka"] = @"სს იშბანკი საქართველო", },
            Terms: [@"isbank", @"i̇şbank", @"ишбанк", @"იშბანკი", @"სს იშბანკი საქართველო"]),
        new NsiItem(
            DisplayName: @"Alpet",
            Id: @"alpet-67f29f",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"fuel", [@"brand:wikidata"] = @"Q62131561", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"fuel", [@"brand"] = @"Alpet", [@"brand:wikidata"] = @"Q62131561", [@"name"] = @"Alpet", },
            Terms: [@"alpet"]),
        new NsiItem(
            DisplayName: @"K-Pet",
            Id: @"kpet-3fa7b1",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"fuel", [@"brand:wikidata"] = @"Q6023970", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"fuel", [@"brand"] = @"K-Pet", [@"brand:wikidata"] = @"Q6023970", [@"name"] = @"K-Pet", },
            Terms: [@"k-pet"]),
        new NsiItem(
            DisplayName: @"Telsim Vodafone",
            Id: @"telsimvodafone-7cc4eb",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q6332131", [@"shop"] = @"mobile_phone", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"Telsim", [@"brand:wikidata"] = @"Q6332131", [@"name"] = @"Telsim Vodafone", [@"shop"] = @"mobile_phone", },
            Terms: [@"Telsim Vodafone", @"telsim", @"vodafone"]),
        new NsiItem(
            DisplayName: @"Turkcell",
            Id: @"turkcell-fa064d",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q283852", [@"shop"] = @"mobile_phone", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"Turkcell", [@"brand:wikidata"] = @"Q283852", [@"name"] = @"Turkcell", [@"shop"] = @"mobile_phone", },
            Terms: [@"turkcell"]),
        new NsiItem(
            DisplayName: @"KKTC Posta Dairesi",
            Id: @"kktcpostadairesi-cdb265",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"post_box", [@"operator:wikidata"] = @"Q6031282", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"post_box", [@"operator"] = @"KKTC Posta Dairesi", [@"operator:wikidata"] = @"Q6031282", },
            Terms: [@"kktc posta dairesi"]),
        new NsiItem(
            DisplayName: @"KKTC Posta Dairesi",
            Id: @"kktcpostadairesi-c16b13",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"post_office", [@"operator:wikidata"] = @"Q6031282", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"post_office", [@"operator"] = @"KKTC Posta Dairesi", [@"operator:wikidata"] = @"Q6031282", },
            Terms: [@"kktc posta dairesi"]),
        new NsiItem(
            DisplayName: @"Harita Genel Müdürlüğü",
            Id: @"haritagenelmudurlugu-6619be",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"monitoring_station", [@"operator:wikidata"] = @"Q5531781", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"monitoring_station", [@"operator"] = @"Harita Genel Müdürlüğü", [@"operator:wikidata"] = @"Q5531781", },
            Terms: [@"harita genel müdürlüğü"]),
    ];
}
