// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'be-wbr.geojson'.</summary>
public static class NsiRegion_BE_WBR_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"Service public fédéral Justice",
            Id: @"servicepublicfederaljustice-923d72",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"prison", [@"operator:wikidata"] = @"Q1469956", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"prison", [@"operator"] = @"Service public fédéral Justice", [@"operator:fr"] = @"Service public fédéral Justice", [@"operator:nl"] = @"Federale Overheidsdienst Justitie", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q1469956", },
            Terms: [@"federale overheidsdienst justitie", @"service public fédéral justice"]),
        new NsiItem(
            DisplayName: @"Université catholique de Louvain",
            Id: @"universitecatholiquedelouvain-6c31c1",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"surveillance", [@"operator:wikidata"] = @"Q378134", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"surveillance", [@"operator"] = @"Université catholique de Louvain", [@"operator:wikidata"] = @"Q378134", },
            Terms: [@"université catholique de louvain"]),
    ];
}
