// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'jp-04.geojson'.</summary>
public static class NsiRegion_JP_04_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"宮城県警察",
            Id: @"473bdf-bd2fdb",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"police", [@"operator:wikidata"] = @"Q11453797", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"police", [@"operator"] = @"宮城県警察", [@"operator:wikidata"] = @"Q11453797", },
            Terms: [@"宮城県警察"]),
        new NsiItem(
            DisplayName: @"亘理町",
            Id: @"894125-5c1fa8",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q1205296", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"亘理町", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q1205296", },
            Terms: [@"亘理町"]),
        new NsiItem(
            DisplayName: @"仙台市",
            Id: @"e2ad4e-5c1fa8",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q46747", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"仙台市", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q46747", },
            Terms: [@"仙台市"]),
        new NsiItem(
            DisplayName: @"宮城県",
            Id: @"miyagiprefecture-5c1fa8",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q47896", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"宮城県", [@"operator:en"] = @"Miyagi Prefecture", [@"operator:ja"] = @"宮城県", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q47896", },
            Terms: [@"miyagi prefecture", @"宮城県"]),
        new NsiItem(
            DisplayName: @"気仙沼市",
            Id: @"98f090-5c1fa8",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q235746", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"気仙沼市", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q235746", },
            Terms: [@"気仙沼市"]),
        new NsiItem(
            DisplayName: @"登米市",
            Id: @"cityoftome-5c1fa8",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q696401", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"登米市", [@"operator:en"] = @"City of Tome", [@"operator:ja"] = @"登米市", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q696401", },
            Terms: [@"city of tome", @"登米市"]),
        new NsiItem(
            DisplayName: @"仙台市",
            Id: @"e2ad4e-8b675e",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator:wikidata"] = @"Q46747", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator"] = @"仙台市", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q46747", },
            Terms: [@"仙台市"]),
        new NsiItem(
            DisplayName: @"仙台市",
            Id: @"e2ad4e-21855d",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator:wikidata"] = @"Q46747", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator"] = @"仙台市", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q46747", },
            Terms: [@"仙台市"]),
    ];
}
