// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'ph-lag.geojson'.</summary>
public static class NsiRegion_PH_LAG_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"Alaminos District",
            Id: @"alaminosdistrict-a3ce88",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130489852", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Alaminos District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130489852", },
            Terms: [@"alaminos district", @"alaminos district, laguna school division, deped"]),
        new NsiItem(
            DisplayName: @"Bay District",
            Id: @"baydistrict-a3ce88",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130489853", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Bay District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130489853", },
            Terms: [@"bay district", @"bay district, laguna school division, department of education"]),
        new NsiItem(
            DisplayName: @"Biñan District",
            Id: @"binandistrict-a3ce88",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130489854", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Biñan District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130489854", },
            Terms: [@"biñan district", @"biñan district of laguna schools division, deped", @"biñan district, laguna school division, department of education"]),
        new NsiItem(
            DisplayName: @"Cabuyao District",
            Id: @"cabuyaodistrict-a3ce88",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130489855", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Cabuyao District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130489855", },
            Terms: [@"cabuyao district", @"cabuyao district of laguna schools division, deped"]),
        new NsiItem(
            DisplayName: @"Calauan District",
            Id: @"calauandistrict-a3ce88",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130489856", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Calauan District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130489856", },
            Terms: [@"calauan district", @"calauan district, laguna school division, department of education"]),
        new NsiItem(
            DisplayName: @"Cavinti District",
            Id: @"cavintidistrict-a3ce88",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130489857", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Cavinti District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130489857", },
            Terms: [@"cavinti district", @"cavinti district of laguna schools division, deped"]),
        new NsiItem(
            DisplayName: @"Famy-Mabitac District",
            Id: @"famymabitacdistrict-a3ce88",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130489859", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Famy-Mabitac District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130489859", },
            Terms: [@"famy-mabitac district", @"famy-mabitac district, laguna school division, deped"]),
        new NsiItem(
            DisplayName: @"Los Baños District",
            Id: @"losbanosdistrict-a3ce88",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130489860", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Los Baños District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130489860", },
            Terms: [@"los baños district", @"los baños district, laguna school division, deped"]),
        new NsiItem(
            DisplayName: @"Luisiana District",
            Id: @"luisianadistrict-a3ce88",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130489861", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Luisiana District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130489861", },
            Terms: [@"luisiana district", @"luisiana district of laguna schools division, deped"]),
        new NsiItem(
            DisplayName: @"Lumban-Kalayaan District",
            Id: @"lumbankalayaandistrict-a3ce88",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130489862", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Lumban-Kalayaan District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130489862", },
            Terms: [@"lumban-kalayaan district", @"lumban-kalayaan district of laguna schools division, deped"]),
        new NsiItem(
            DisplayName: @"Nagcarlan-Rizal District",
            Id: @"nagcarlanrizaldistrict-a3ce88",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130489863", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Nagcarlan-Rizal District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130489863", },
            Terms: [@"nagcarlan-rizal district", @"nagcarlan-rizal district, laguna school division, deped"]),
        new NsiItem(
            DisplayName: @"Pangil-Pakil District",
            Id: @"pangilpakildistrict-a3ce88",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130489864", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Pangil-Pakil District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130489864", },
            Terms: [@"pangil-pakil district", @"pangil-pakil district of laguna schools division, deped"]),
        new NsiItem(
            DisplayName: @"Pila District",
            Id: @"piladistrict-a3ce88",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130489865", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Pila District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130489865", },
            Terms: [@"pila district", @"pila district, laguna school division, deped"]),
        new NsiItem(
            DisplayName: @"San Francisco District (San Pablo City)",
            Id: @"sanfranciscodistrict-a3ce88",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490404", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"San Francisco District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490404", },
            Terms: [@"San Francisco District (San Pablo City)", @"san francisco district", @"san francisco district, san pablo city school division, deped"]),
        new NsiItem(
            DisplayName: @"San Pedro District",
            Id: @"sanpedrodistrict-a3ce88",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130489868", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"San Pedro District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130489868", },
            Terms: [@"san pedro district", @"san pedro district, laguna school division, department of education"]),
        new NsiItem(
            DisplayName: @"Santa Cruz District (Laguna)",
            Id: @"santacruzdistrict-a3ce88",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130489869", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Santa Cruz District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130489869", },
            Terms: [@"Santa Cruz District (Laguna)", @"santa cruz district", @"santa cruz district of laguna schools division, deped"]),
        new NsiItem(
            DisplayName: @"Santa Maria District (Laguna)",
            Id: @"santamariadistrict-a3ce88",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130489870", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Santa Maria District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130489870", },
            Terms: [@"Santa Maria District (Laguna)", @"santa maria district", @"santa maria district of laguna schools division, deped", @"santa maria district, laguna school division, deped"]),
        new NsiItem(
            DisplayName: @"Victoria District (Laguna)",
            Id: @"victoriadistrict-a3ce88",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130489871", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Victoria District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130489871", },
            Terms: [@"Victoria District (Laguna)", @"victoria district", @"victoria district, laguna school division, department of education"]),
        new NsiItem(
            DisplayName: @"West District (Calamba City)",
            Id: @"westdistrict-a3ce88",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130491145", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"West District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130491145", },
            Terms: [@"West District (Calamba City)", @"west district", @"west district, calamba city school division, department of education"]),
    ];
}
