// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'ag'.</summary>
public static class NsiRegion_AG
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"Caribbean Cinemas",
            Id: @"caribbeancinemas-77ba3f",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"cinema", [@"brand:wikidata"] = @"Q5039364", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"cinema", [@"brand"] = @"Caribbean Cinemas", [@"brand:wikidata"] = @"Q5039364", [@"name"] = @"Caribbean Cinemas", },
            Terms: [@"caribbean cinemas"]),
    ];
}
