// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'ph-mas.geojson'.</summary>
public static class NsiRegion_PH_MAS_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"Aroroy East District",
            Id: @"aroroyeastdistrict-13aca4",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490331", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Aroroy East District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490331", },
            Terms: [@"aroroy east district", @"aroroy east district of masbate schools division, deped"]),
        new NsiItem(
            DisplayName: @"Aroroy West District",
            Id: @"aroroywestdistrict-13aca4",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490333", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Aroroy West District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490333", },
            Terms: [@"aroroy west district", @"aroroy west district of masbate schools division, deped"]),
        new NsiItem(
            DisplayName: @"Baleno District",
            Id: @"balenodistrict-13aca4",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490334", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Baleno District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490334", },
            Terms: [@"baleno district", @"baleno district of masbate schools division, deped"]),
        new NsiItem(
            DisplayName: @"Balud North District",
            Id: @"baludnorthdistrict-13aca4",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490335", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Balud North District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490335", },
            Terms: [@"balud north district", @"balud north district of masbate schools division, deped"]),
        new NsiItem(
            DisplayName: @"Balud South District",
            Id: @"baludsouthdistrict-13aca4",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490336", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Balud South District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490336", },
            Terms: [@"balud south district", @"balud south district of masbate schools division, deped"]),
        new NsiItem(
            DisplayName: @"Batuan District (Masbate)",
            Id: @"batuandistrict-13aca4",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490337", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Batuan District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490337", },
            Terms: [@"Batuan District (Masbate)", @"batuan district", @"batuan district of masbate schools division, deped"]),
        new NsiItem(
            DisplayName: @"Cataingan East District",
            Id: @"catainganeastdistrict-13aca4",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490338", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Cataingan East District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490338", },
            Terms: [@"cataingan east district", @"cataingan east district of masbate schools division, deped"]),
        new NsiItem(
            DisplayName: @"Cataingan West District",
            Id: @"catainganwestdistrict-13aca4",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490339", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Cataingan West District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490339", },
            Terms: [@"cataingan west district", @"cataingan west district of masbate schools division, deped"]),
        new NsiItem(
            DisplayName: @"Cawayan East District",
            Id: @"cawayaneastdistrict-13aca4",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490340", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Cawayan East District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490340", },
            Terms: [@"cawayan east district", @"cawayan east district of masbate schools division, deped"]),
        new NsiItem(
            DisplayName: @"Cawayan West District",
            Id: @"cawayanwestdistrict-13aca4",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490341", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Cawayan West District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490341", },
            Terms: [@"cawayan west district", @"cawayan west district of masbate schools division, deped"]),
        new NsiItem(
            DisplayName: @"Claveria North District",
            Id: @"claverianorthdistrict-13aca4",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490342", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Claveria North District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490342", },
            Terms: [@"claveria north district", @"claveria north district of masbate schools division, deped"]),
        new NsiItem(
            DisplayName: @"Claveria South District",
            Id: @"claveriasouthdistrict-13aca4",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130491349", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Claveria South District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130491349", },
            Terms: [@"claveria south district", @"claveria south district of masbate schools division, deped"]),
        new NsiItem(
            DisplayName: @"Dimasalang District",
            Id: @"dimasalangdistrict-13aca4",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130491350", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Dimasalang District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130491350", },
            Terms: [@"dimasalang district", @"dimasalang district of masbate schools division, deped"]),
        new NsiItem(
            DisplayName: @"Esperanza District",
            Id: @"esperanzadistrict-13aca4",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130491351", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Esperanza District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130491351", },
            Terms: [@"esperanza district", @"esperanza district of masbate schools division, deped"]),
        new NsiItem(
            DisplayName: @"Mandaon North District",
            Id: @"mandaonnorthdistrict-13aca4",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130491352", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Mandaon North District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130491352", },
            Terms: [@"mandaon north district", @"mandaon north district of masbate schools division, deped"]),
        new NsiItem(
            DisplayName: @"Mandaon South District",
            Id: @"mandaonsouthdistrict-13aca4",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490343", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Mandaon South District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490343", },
            Terms: [@"mandaon south district", @"mandaon south district of masbate schools division, deped"]),
        new NsiItem(
            DisplayName: @"Milagros East District",
            Id: @"milagroseastdistrict-13aca4",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490345", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Milagros East District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490345", },
            Terms: [@"milagros east district", @"milagros east district of masbate schools division, deped"]),
        new NsiItem(
            DisplayName: @"Milagros West District",
            Id: @"milagroswestdistrict-13aca4",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490346", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Milagros West District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490346", },
            Terms: [@"milagros west district", @"milagros west district of masbate schools division, deped"]),
        new NsiItem(
            DisplayName: @"Mobo North District",
            Id: @"mobonorthdistrict-13aca4",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490347", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Mobo North District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490347", },
            Terms: [@"mobo north district", @"mobo north district of masbate schools division, deped"]),
        new NsiItem(
            DisplayName: @"Mobo South District",
            Id: @"mobosouthdistrict-13aca4",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490348", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Mobo South District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490348", },
            Terms: [@"mobo south district", @"mobo south district of masbate schools division, deped"]),
        new NsiItem(
            DisplayName: @"Monreal District",
            Id: @"monrealdistrict-13aca4",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490349", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Monreal District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490349", },
            Terms: [@"monreal district", @"monreal district of masbate schools division, deped"]),
        new NsiItem(
            DisplayName: @"Palanas North District",
            Id: @"palanasnorthdistrict-13aca4",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490350", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Palanas North District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490350", },
            Terms: [@"palanas north district", @"palanas north district of masbate schools division, deped"]),
        new NsiItem(
            DisplayName: @"Palanas South District",
            Id: @"palanassouthdistrict-13aca4",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490351", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Palanas South District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490351", },
            Terms: [@"palanas south district", @"palanas south district of masbate schools division, deped"]),
        new NsiItem(
            DisplayName: @"Pio V. Corpuz District",
            Id: @"piovcorpuzdistrict-13aca4",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490352", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Pio V. Corpuz District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490352", },
            Terms: [@"pio v. corpuz district", @"pio v. corpuz district of masbate schools division, deped"]),
        new NsiItem(
            DisplayName: @"Placer East District",
            Id: @"placereastdistrict-13aca4",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490353", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Placer East District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490353", },
            Terms: [@"placer east district", @"placer east district of masbate schools division, deped"]),
        new NsiItem(
            DisplayName: @"Placer West District",
            Id: @"placerwestdistrict-13aca4",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490354", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Placer West District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490354", },
            Terms: [@"placer west district", @"placer west district of masbate schools division, deped"]),
        new NsiItem(
            DisplayName: @"San Fernando District (Masbate)",
            Id: @"sanfernandodistrict-13aca4",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490355", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"San Fernando District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490355", },
            Terms: [@"San Fernando District (Masbate)", @"san fernando district", @"san fernando district of masbate schools division, deped"]),
        new NsiItem(
            DisplayName: @"San Jacinto District (Masbate)",
            Id: @"sanjacintodistrict-13aca4",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490356", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"San Jacinto District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490356", },
            Terms: [@"San Jacinto District (Masbate)", @"san jacinto district", @"san jacinto district of masbate schools division, deped"]),
        new NsiItem(
            DisplayName: @"San Pascual North District",
            Id: @"sanpascualnorthdistrict-13aca4",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490357", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"San Pascual North District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490357", },
            Terms: [@"san pascual north district", @"san pascual north district of masbate schools division, deped"]),
        new NsiItem(
            DisplayName: @"San Pascual South District",
            Id: @"sanpascualsouthdistrict-13aca4",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490358", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"San Pascual South District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490358", },
            Terms: [@"san pascual south district", @"san pascual south district of masbate schools division, deped"]),
        new NsiItem(
            DisplayName: @"Uson North District",
            Id: @"usonnorthdistrict-13aca4",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490359", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Uson North District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490359", },
            Terms: [@"uson north district", @"uson-north district of masbate schools division, deped"]),
        new NsiItem(
            DisplayName: @"Uson South District",
            Id: @"usonsouthdistrict-13aca4",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490360", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Uson South District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490360", },
            Terms: [@"uson south district", @"uson south district of masbate schools division, deped"]),
    ];
}
