// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'jp-19.geojson'.</summary>
public static class NsiRegion_JP_19_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"西東京バス",
            Id: @"nishitokyobus-95fa09",
            Tags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"network:wikidata"] = @"Q7040497", [@"public_transport"] = @"platform", },
            AddTags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"highway"] = @"bus_stop", [@"network"] = @"西東京バス", [@"network:en"] = @"Nishi Tokyo Bus", [@"network:ja"] = @"西東京バス", [@"network:wikidata"] = @"Q7040497", [@"public_transport"] = @"platform", },
            Terms: [@"nishi tokyo bus", @"西東京バス"]),
        new NsiItem(
            DisplayName: @"西東京バス",
            Id: @"nishitokyobus-d496a1",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q7040497", [@"route"] = @"bus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"西東京バス", [@"network:en"] = @"Nishi Tokyo Bus", [@"network:ja"] = @"西東京バス", [@"network:wikidata"] = @"Q7040497", [@"route"] = @"bus", [@"type"] = @"route", },
            Terms: [@"nishi tokyo bus", @"西東京バス"]),
    ];
}
