// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'la'.</summary>
public static class NsiRegion_LA
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"Sacombank",
            Id: @"sacombank-ca17c8",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand:wikidata"] = @"Q6123772", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand"] = @"Sacombank", [@"brand:wikidata"] = @"Q6123772", [@"operator"] = @"Sacombank", [@"operator:wikidata"] = @"Q6123772", },
            Terms: [@"sacombank"]),
        new NsiItem(
            DisplayName: @"Sacombank",
            Id: @"sacombank-0c3ae7",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand:wikidata"] = @"Q6123772", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand"] = @"Sacombank", [@"brand:wikidata"] = @"Q6123772", [@"name"] = @"Sacombank", },
            Terms: [@"sacombank"]),
        new NsiItem(
            DisplayName: @"Black Canyon",
            Id: @"blackcanyon-0e73cd",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"cafe", [@"brand:wikidata"] = @"Q125870828", [@"cuisine"] = @"coffee_shop", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"cafe", [@"brand"] = @"Black Canyon", [@"brand:wikidata"] = @"Q125870828", [@"cuisine"] = @"coffee_shop", [@"name"] = @"Black Canyon", [@"takeaway"] = @"yes", },
            Terms: [@"black canyon", @"black canyon coffee", @"black canyon coffee & eatery"]),
        new NsiItem(
            DisplayName: @"Mixue Ice Cream & Tea",
            Id: @"mixue-930f31",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"cafe", [@"brand:wikidata"] = @"Q107406476", [@"cuisine"] = @"ice_cream;bubble_tea", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"cafe", [@"brand"] = @"Mixue Ice Cream & Tea", [@"brand:wikidata"] = @"Q107406476", [@"cuisine"] = @"ice_cream;bubble_tea", [@"name"] = @"Mixue", [@"takeaway"] = @"yes", },
            Terms: [@"mixue ice cream & tea"]),
        new NsiItem(
            DisplayName: @"The Pizza Company",
            Id: @"thepizzacompany-abbb1f",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"fast_food", [@"brand:wikidata"] = @"Q2413520", [@"cuisine"] = @"pizza", },
            AddTags: new Dictionary<string, string> { [@"alt_name"] = @"Pizza Company", [@"amenity"] = @"fast_food", [@"brand"] = @"The Pizza Company", [@"brand:wikidata"] = @"Q2413520", [@"cuisine"] = @"pizza", [@"name"] = @"The Pizza Company", [@"takeaway"] = @"yes", },
            Terms: [@"pizza company", @"the pizza company"]),
        new NsiItem(
            DisplayName: @"Swensen's",
            Id: @"swensens-570cf0",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"ice_cream", [@"brand:wikidata"] = @"Q6640658", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"ice_cream", [@"brand"] = @"Swensen's", [@"brand:wikidata"] = @"Q6640658", [@"name"] = @"Swensen's", },
            Terms: [@"swensen's"]),
        new NsiItem(
            DisplayName: @"Allianz",
            Id: @"allianz-400bd0",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q487292", [@"office"] = @"insurance", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"Allianz", [@"brand:wikidata"] = @"Q487292", [@"name"] = @"Allianz", [@"office"] = @"insurance", },
            Terms: [@"allianz", @"allianz versicherung"]),
        new NsiItem(
            DisplayName: @"Beeline",
            Id: @"beeline-2f71de",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q402880", [@"office"] = @"telecommunication", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"Beeline", [@"brand:wikidata"] = @"Q402880", [@"name"] = @"Beeline", [@"office"] = @"telecommunication", },
            Terms: [@"beeline"]),
        new NsiItem(
            DisplayName: @"Inter Cars",
            Id: @"intercars-a4b6c1",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q115922509", [@"shop"] = @"car_parts", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"Inter Cars", [@"brand:wikidata"] = @"Q115922509", [@"name"] = @"Inter Cars", [@"shop"] = @"car_parts", },
            Terms: [@"inter cars"]),
        new NsiItem(
            DisplayName: @"Jiffy",
            Id: @"jiffy-c8e053",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q16770436", [@"shop"] = @"convenience", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"Jiffy", [@"brand:en"] = @"Jiffy", [@"brand:th"] = @"จิฟฟี่", [@"brand:wikidata"] = @"Q16770436", [@"name"] = @"Jiffy", [@"name:en"] = @"Jiffy", [@"name:th"] = @"จิฟฟี่", [@"shop"] = @"convenience", },
            Terms: [@"jiffy", @"จิฟฟี่"]),
        new NsiItem(
            DisplayName: @"Parkson",
            Id: @"parkson-6dcedc",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q835145", [@"shop"] = @"department_store", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"Parkson", [@"brand:en"] = @"Parkson", [@"brand:wikidata"] = @"Q835145", [@"brand:zh"] = @"百盛", [@"name"] = @"Parkson", [@"name:en"] = @"Parkson", [@"name:zh"] = @"百盛", [@"shop"] = @"department_store", },
            Terms: [@"parkson", @"百盛"]),
        new NsiItem(
            DisplayName: @"Avani",
            Id: @"avanihotelsandresorts-e9c192",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q48989823", [@"tourism"] = @"hotel", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"Avani Hotels & Resorts", [@"brand:wikidata"] = @"Q48989823", [@"name"] = @"Avani Hotels & Resorts", [@"tourism"] = @"hotel", },
            Terms: [@"avani", @"avani hotels & resorts"]),
        new NsiItem(
            DisplayName: @"SureStay",
            Id: @"surestay-e644f7",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q135246628", [@"tourism"] = @"hotel", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"SureStay", [@"brand:wikidata"] = @"Q135246628", [@"name"] = @"SureStay", [@"official_name"] = @"SureStay by Best Western", [@"tourism"] = @"hotel", },
            Terms: [@"surestay", @"surestay by best western", @"surestay hotels"]),
    ];
}
