// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'gb-dev.geojson'.</summary>
public static class NsiRegion_GB_DEV_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"Devon Partnership NHS Trust",
            Id: @"devonpartnershipnhstrust-228a98",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"clinic", [@"operator:wikidata"] = @"Q16988718", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"clinic", [@"healthcare"] = @"clinic", [@"operator"] = @"Devon Partnership NHS Trust", [@"operator:type"] = @"private", [@"operator:wikidata"] = @"Q16988718", },
            Terms: [@"devon partnership nhs trust"]),
        new NsiItem(
            DisplayName: @"Devon and Somerset Fire and Rescue Service",
            Id: @"devonandsomersetfireandrescueservice-52c78e",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"fire_station", [@"operator:wikidata"] = @"Q5267788", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"fire_station", [@"operator"] = @"Devon and Somerset Fire and Rescue Service", [@"operator:wikidata"] = @"Q5267788", },
            Terms: [@"devon and somerset fire and rescue service"]),
        new NsiItem(
            DisplayName: @"Devon Partnership NHS Trust",
            Id: @"devonpartnershipnhstrust-cd1ad5",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"hospital", [@"operator:wikidata"] = @"Q16988718", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"hospital", [@"healthcare"] = @"hospital", [@"operator"] = @"Devon Partnership NHS Trust", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q16988718", },
            Terms: [@"devon partnership nhs trust"]),
        new NsiItem(
            DisplayName: @"Devon County Council",
            Id: @"devoncountycouncil-e39d1a",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"library", [@"operator:wikidata"] = @"Q6385990", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"library", [@"operator"] = @"Devon County Council", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q6385990", [@"ref:isil"] = @"GB-UkExDL", },
            Terms: [@"devon county council"]),
        new NsiItem(
            DisplayName: @"Devon and Cornwall Police",
            Id: @"devonandcornwallpolice-4da082",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"police", [@"operator:wikidata"] = @"Q5267784", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"police", [@"operator"] = @"Devon and Cornwall Police", [@"operator:wikidata"] = @"Q5267784", },
            Terms: [@"devon and cornwall police"]),
        new NsiItem(
            DisplayName: @"Devon County Council",
            Id: @"devoncountycouncil-ad06a1",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"recycling", [@"operator:wikidata"] = @"Q6385990", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"recycling", [@"operator"] = @"Devon County Council", [@"operator:wikidata"] = @"Q6385990", },
            Terms: [@"devon county council"]),
        new NsiItem(
            DisplayName: @"Devon County Council",
            Id: @"devoncountycouncil-02f810",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q6385990", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Devon County Council", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q6385990", },
            Terms: [@"devon county council"]),
        new NsiItem(
            DisplayName: @"Plymouth Citybus (UK)",
            Id: @"plymouthcitybus-f59b7d",
            Tags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"network:wikidata"] = @"Q7205782", [@"public_transport"] = @"platform", },
            AddTags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"highway"] = @"bus_stop", [@"network"] = @"Plymouth Citybus", [@"network:wikidata"] = @"Q7205782", [@"public_transport"] = @"platform", },
            Terms: [@"Plymouth Citybus (UK)", @"plymouth citybus"]),
        new NsiItem(
            DisplayName: @"The Buses of Somerset",
            Id: @"thebusesofsomerset-0703e3",
            Tags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"network:wikidata"] = @"Q17018973", [@"public_transport"] = @"platform", },
            AddTags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"highway"] = @"bus_stop", [@"network"] = @"The Buses of Somerset", [@"network:wikidata"] = @"Q17018973", [@"operator"] = @"First South West", [@"operator:wikidata"] = @"Q5454172", [@"public_transport"] = @"platform", },
            Terms: [@"first south west", @"the buses of somerset"]),
        new NsiItem(
            DisplayName: @"Plymouth Citybus (UK)",
            Id: @"plymouthcitybus-8651a5",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q7205782", [@"route"] = @"bus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Plymouth Citybus", [@"network:wikidata"] = @"Q7205782", [@"route"] = @"bus", [@"type"] = @"route", },
            Terms: [@"Plymouth Citybus (UK)", @"plymouth citybus"]),
        new NsiItem(
            DisplayName: @"The Buses of Somerset",
            Id: @"thebusesofsomerset-e3e546",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q17018973", [@"route"] = @"bus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"The Buses of Somerset", [@"network:wikidata"] = @"Q17018973", [@"operator"] = @"First South West", [@"operator:wikidata"] = @"Q5454172", [@"route"] = @"bus", [@"type"] = @"route", },
            Terms: [@"first south west", @"the buses of somerset"]),
    ];
}
