// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'pl-10.geojson'.</summary>
public static class NsiRegion_PL_10_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"ASEC (ZTM Warszawa)",
            Id: @"asec-7bef08",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"vending_machine", [@"operator:wikidata"] = @"Q115014416", [@"vending"] = @"public_transport_tickets", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"vending_machine", [@"currency:PLN"] = @"yes", [@"network"] = @"ZTM Warszawa", [@"network:wikidata"] = @"Q8066998", [@"operator"] = @"ASEC", [@"operator:wikidata"] = @"Q115014416", [@"payment:coins"] = @"yes", [@"payment:contactless"] = @"yes", [@"payment:maestro"] = @"yes", [@"payment:mastercard"] = @"yes", [@"payment:mastercard_electronic"] = @"yes", [@"payment:notes"] = @"yes", [@"payment:v_pay"] = @"yes", [@"payment:visa"] = @"yes", [@"payment:visa_electron"] = @"yes", [@"vending"] = @"public_transport_tickets", },
            Terms: [@"ASEC (ZTM Warszawa)", @"asec"]),
        new NsiItem(
            DisplayName: @"Mennica Polska (ZTM Warszawa)",
            Id: @"mennicapolska-7bef08",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"vending_machine", [@"operator:wikidata"] = @"Q4371256", [@"vending"] = @"public_transport_tickets", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"vending_machine", [@"currency:PLN"] = @"yes", [@"network"] = @"ZTM Warszawa", [@"network:wikidata"] = @"Q8066998", [@"operator"] = @"Mennica Polska", [@"operator:wikidata"] = @"Q4371256", [@"payment:coins"] = @"yes", [@"payment:maestro"] = @"yes", [@"payment:mastercard"] = @"yes", [@"payment:notes"] = @"yes", [@"payment:v_pay"] = @"yes", [@"payment:visa"] = @"yes", [@"payment:visa_electron"] = @"yes", [@"vending"] = @"public_transport_tickets", },
            Terms: [@"Mennica Polska (ZTM Warszawa)", @"mennica polska"]),
        new NsiItem(
            DisplayName: @"Port Lotniczy Łódź",
            Id: @"portlotniczylodz-a635dd",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"surveillance", [@"operator:wikidata"] = @"Q764554", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"surveillance", [@"operator"] = @"Port Lotniczy Łódź", [@"operator:wikidata"] = @"Q764554", },
            Terms: [@"port lotniczy łódź"]),
        new NsiItem(
            DisplayName: @"Lokalny Transport Zbiorowy w Łodzi",
            Id: @"lokalnytransportzbiorowywlodzi-705cb6",
            Tags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"network:wikidata"] = @"Q133202246", [@"public_transport"] = @"platform", },
            AddTags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"highway"] = @"bus_stop", [@"network"] = @"Lokalny Transport Zbiorowy w Łodzi", [@"network:wikidata"] = @"Q133202246", [@"public_transport"] = @"platform", },
            Terms: [@"lokalny transport zbiorowy w łodzi", @"ltz łódź"]),
        new NsiItem(
            DisplayName: @"MUK Zgierz",
            Id: @"mukzgierz-705cb6",
            Tags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"network:wikidata"] = @"Q11780314", [@"public_transport"] = @"platform", },
            AddTags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"highway"] = @"bus_stop", [@"network"] = @"MUK Zgierz", [@"network:wikidata"] = @"Q11780314", [@"public_transport"] = @"platform", },
            Terms: [@"muk zgierz"]),
        new NsiItem(
            DisplayName: @"ZTM Warszawa",
            Id: @"ztmwarszawa-c4f1c9",
            Tags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"network:wikidata"] = @"Q8066998", [@"public_transport"] = @"platform", },
            AddTags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"highway"] = @"bus_stop", [@"network"] = @"ZTM Warszawa", [@"network:wikidata"] = @"Q8066998", [@"public_transport"] = @"platform", },
            Terms: [@"ztm warszawa"]),
        new NsiItem(
            DisplayName: @"Lokalny Transport Zbiorowy w Łodzi",
            Id: @"lokalnytransportzbiorowywlodzi-a6676e",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q133202246", [@"railway"] = @"tram_stop", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Lokalny Transport Zbiorowy w Łodzi", [@"network:wikidata"] = @"Q133202246", [@"operator"] = @"MPK-Łódź", [@"operator:wikidata"] = @"Q11780295", [@"railway"] = @"tram_stop", },
            Terms: [@"lokalny transport zbiorowy w łodzi", @"ltz łódź", @"mpk-łódź"]),
        new NsiItem(
            DisplayName: @"ZTM Warszawa",
            Id: @"ztmwarszawa-44ac96",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q8066998", [@"railway"] = @"tram_stop", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"ZTM Warszawa", [@"network:wikidata"] = @"Q8066998", [@"operator"] = @"Tramwaje Warszawskie", [@"operator:wikidata"] = @"Q9360809", [@"railway"] = @"tram_stop", },
            Terms: [@"tramwaje warszawskie", @"ztm warszawa"]),
        new NsiItem(
            DisplayName: @"Lokalny Transport Zbiorowy w Łodzi",
            Id: @"lokalnytransportzbiorowywlodzi-f88f23",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q133202246", [@"route"] = @"bus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Lokalny Transport Zbiorowy w Łodzi", [@"network:wikidata"] = @"Q133202246", [@"route"] = @"bus", [@"type"] = @"route", },
            Terms: [@"lokalny transport zbiorowy w łodzi", @"ltz łódź"]),
        new NsiItem(
            DisplayName: @"MUK Zgierz",
            Id: @"mukzgierz-f88f23",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q11780314", [@"route"] = @"bus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"MUK Zgierz", [@"network:wikidata"] = @"Q11780314", [@"route"] = @"bus", [@"type"] = @"route", },
            Terms: [@"muk zgierz"]),
        new NsiItem(
            DisplayName: @"ZTM Warszawa",
            Id: @"ztmwarszawa-a746cd",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q8066998", [@"route"] = @"bus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"ZTM Warszawa", [@"network:wikidata"] = @"Q8066998", [@"route"] = @"bus", [@"type"] = @"route", },
            Terms: [@"ztm warszawa"]),
        new NsiItem(
            DisplayName: @"Lokalny Transport Zbiorowy w Łodzi",
            Id: @"lokalnytransportzbiorowywlodzi-205da6",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q133202246", [@"route"] = @"tram", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Lokalny Transport Zbiorowy w Łodzi", [@"network:wikidata"] = @"Q133202246", [@"operator"] = @"MPK-Łódź", [@"operator:wikidata"] = @"Q11780295", [@"route"] = @"tram", [@"type"] = @"route", },
            Terms: [@"lokalny transport zbiorowy w łodzi", @"ltz łódź", @"mpk-łódź"]),
        new NsiItem(
            DisplayName: @"ZTM Warszawa",
            Id: @"ztmwarszawa-545edd",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q8066998", [@"route"] = @"tram", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"ZTM Warszawa", [@"network:wikidata"] = @"Q8066998", [@"operator"] = @"Tramwaje Warszawskie", [@"operator:wikidata"] = @"Q9360809", [@"route"] = @"tram", [@"type"] = @"route", },
            Terms: [@"tramwaje warszawskie", @"ztm warszawa"]),
    ];
}
