// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'ar-j.geojson'.</summary>
public static class NsiRegion_AR_J_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"CISEM",
            Id: @"cisem-ad9313",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"surveillance", [@"operator:wikidata"] = @"Q131378440", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"surveillance", [@"operator"] = @"CISEM", [@"operator:wikidata"] = @"Q131378440", },
            Terms: [@"cisem"]),
        new NsiItem(
            DisplayName: @"Naturgy",
            Id: @"naturgy-5490e4",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q474690", [@"power"] = @"substation", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Naturgy", [@"operator:wikidata"] = @"Q474690", [@"power"] = @"substation", },
            Terms: [@"naturgy", @"union fenosa"]),
        new NsiItem(
            DisplayName: @"Naturgy",
            Id: @"naturgy-32e0f3",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q474690", [@"power"] = @"transformer", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Naturgy", [@"operator:wikidata"] = @"Q474690", [@"power"] = @"transformer", },
            Terms: [@"naturgy", @"union fenosa"]),
        new NsiItem(
            DisplayName: @"Red Tulum",
            Id: @"redtulum-6302ab",
            Tags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"network:wikidata"] = @"Q105633430", [@"public_transport"] = @"platform", },
            AddTags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"highway"] = @"bus_stop", [@"network"] = @"Red Tulum", [@"network:wikidata"] = @"Q105633430", [@"public_transport"] = @"platform", },
            Terms: [@"red tulum"]),
        new NsiItem(
            DisplayName: @"Red Tulum",
            Id: @"redtulum-7f694f",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q105633430", [@"route"] = @"bus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Red Tulum", [@"network:wikidata"] = @"Q105633430", [@"route"] = @"bus", [@"type"] = @"route", },
            Terms: [@"red tulum"]),
    ];
}
