// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'de-hb.geojson'.</summary>
public static class NsiRegion_DE_HB_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"Sparda-Bank (Deutschland)",
            Id: @"spardabank-eb9668",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand:wikidata"] = @"Q2307136", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand"] = @"Sparda-Bank", [@"brand:wikidata"] = @"Q2307136", [@"operator"] = @"Sparda-Bank", [@"operator:wikidata"] = @"Q2307136", },
            Terms: [@"Sparda-Bank (Deutschland)", @"sparda-bank"]),
        new NsiItem(
            DisplayName: @"Sparda-Bank (Deutschland)",
            Id: @"spardabank-a7f91c",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand:wikidata"] = @"Q2307136", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand"] = @"Sparda-Bank", [@"brand:wikidata"] = @"Q2307136", [@"name"] = @"Sparda-Bank", },
            Terms: [@"Sparda-Bank (Deutschland)", @"sparda-bank"]),
        new NsiItem(
            DisplayName: @"AOK Bremen/Bremerhaven",
            Id: @"aokbremenbremerhaven-b4fc7f",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q2632327", [@"office"] = @"insurance", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"AOK Bremen/Bremerhaven", [@"brand:wikidata"] = @"Q2632327", [@"insurance"] = @"health", [@"name"] = @"AOK Bremen/Bremerhaven", [@"office"] = @"insurance", },
            Terms: [@"aok", @"aok bremen", @"aok bremen/bremerhaven", @"aok bremerhaven"]),
        new NsiItem(
            DisplayName: @"swb (Bremen)",
            Id: @"swb-152e8e",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"charging_station", [@"operator:wikidata"] = @"Q1740682", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"charging_station", [@"operator"] = @"swb", [@"operator:wikidata"] = @"Q1740682", },
            Terms: [@"swb (Bremen)", @"swb"]),
        new NsiItem(
            DisplayName: @"KiTa Bremen",
            Id: @"kitabremen-f9b96a",
            Tags: new Dictionary<string, string> { [@"education"] = @"kindergarten", [@"operator:wikidata"] = @"Q129772069", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"kindergarten", [@"education"] = @"kindergarten", [@"operator"] = @"KiTa Bremen", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q129772069", },
            Terms: [@"kita bremen"]),
        new NsiItem(
            DisplayName: @"Landeskriminalamt Bremen",
            Id: @"landeskriminalamtbremen-048619",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"police", [@"operator:wikidata"] = @"Q1802335", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"police", [@"operator"] = @"Landeskriminalamt Bremen", [@"operator:short"] = @"LKA", [@"operator:wikidata"] = @"Q1802335", },
            Terms: [@"landeskriminalamt bremen", @"lka"]),
        new NsiItem(
            DisplayName: @"Polizei Bremen",
            Id: @"polizeibremen-048619",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"police", [@"operator:wikidata"] = @"Q1672788", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"police", [@"operator"] = @"Polizei Bremen", [@"operator:wikidata"] = @"Q1672788", },
            Terms: [@"polizei bremen"]),
        new NsiItem(
            DisplayName: @"Behörde für Schule und Berufsbildung",
            Id: @"behordefurschuleundberufsbildung-964df5",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q814586", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Behörde für Schule und Berufsbildung", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q814586", },
            Terms: [@"behörde für schule und berufsbildung"]),
        new NsiItem(
            DisplayName: @"Bremer Heimstiftung",
            Id: @"bremerheimstiftung-739aab",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"social_facility", [@"operator:wikidata"] = @"Q907638", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"social_facility", [@"operator"] = @"Bremer Heimstiftung", [@"operator:type"] = @"ngo", [@"operator:wikidata"] = @"Q907638", },
            Terms: [@"bremer heimstiftung"]),
        new NsiItem(
            DisplayName: @"Sozialwerk der Freien Christengemeinde Bremen e.V.",
            Id: @"sozialwerkderfreienchristengemeindebremenev-739aab",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"social_facility", [@"operator:wikidata"] = @"Q130273117", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"social_facility", [@"operator"] = @"Sozialwerk der Freien Christengemeinde Bremen e.V.", [@"operator:type"] = @"ngo", [@"operator:wikidata"] = @"Q130273117", },
            Terms: [@"sozialwerk der freien christengemeinde bremen e.v."]),
        new NsiItem(
            DisplayName: @"swb (Bremen)",
            Id: @"swb-fd47ae",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"charge_point", [@"operator:wikidata"] = @"Q1740682", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"charge_point", [@"operator"] = @"swb", [@"operator:wikidata"] = @"Q1740682", },
            Terms: [@"swb (Bremen)", @"swb"]),
        new NsiItem(
            DisplayName: @"TenneT TSO",
            Id: @"tennettso-adf225",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q1662830", [@"power"] = @"line", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"TenneT TSO", [@"operator:wikidata"] = @"Q1662830", [@"power"] = @"line", },
            Terms: [@"tennet tso", @"tennet tso gmbh", @"transpower"]),
        new NsiItem(
            DisplayName: @"TenneT TSO",
            Id: @"tennettso-d61b6c",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q1662830", [@"power"] = @"minor_line", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"TenneT TSO", [@"operator:wikidata"] = @"Q1662830", [@"power"] = @"minor_line", },
            Terms: [@"tennet tso", @"tennet tso gmbh", @"transpower"]),
        new NsiItem(
            DisplayName: @"TenneT TSO",
            Id: @"tennettso-9c1c2e",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q1662830", [@"power"] = @"pole", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"TenneT TSO", [@"operator:wikidata"] = @"Q1662830", [@"power"] = @"pole", },
            Terms: [@"tennet tso", @"tennet tso gmbh", @"transpower"]),
        new NsiItem(
            DisplayName: @"Bremer Straßenbahn AG",
            Id: @"bremerstrassenbahnag-b4e66c",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q6716847", [@"power"] = @"substation", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Bremer Straßenbahn AG", [@"operator:short"] = @"BSAG", [@"operator:wikidata"] = @"Q6716847", [@"power"] = @"substation", },
            Terms: [@"bremer straßenbahn ag", @"bsag"]),
        new NsiItem(
            DisplayName: @"swb (Bremen)",
            Id: @"swb-b4e66c",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q1740682", [@"power"] = @"substation", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"swb", [@"operator:wikidata"] = @"Q1740682", [@"power"] = @"substation", },
            Terms: [@"swb (Bremen)", @"swb", @"swb ag"]),
        new NsiItem(
            DisplayName: @"TenneT TSO",
            Id: @"tennettso-56054e",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q1662830", [@"power"] = @"substation", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"TenneT TSO", [@"operator:wikidata"] = @"Q1662830", [@"power"] = @"substation", },
            Terms: [@"tennet tso", @"tennet tso gmbh", @"transpower"]),
        new NsiItem(
            DisplayName: @"Wesernetz Bremen",
            Id: @"wesernetzbremen-b4e66c",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q124371401", [@"power"] = @"substation", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Wesernetz Bremen", [@"operator:wikidata"] = @"Q124371401", [@"power"] = @"substation", },
            Terms: [@"wesernetz", @"wesernetz bremen", @"wesernetz bremen gmbh"]),
        new NsiItem(
            DisplayName: @"TenneT TSO",
            Id: @"tennettso-85a108",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q1662830", [@"power"] = @"tower", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"TenneT TSO", [@"operator:wikidata"] = @"Q1662830", [@"power"] = @"tower", },
            Terms: [@"tennet tso", @"tennet tso gmbh", @"transpower"]),
        new NsiItem(
            DisplayName: @"Bremer Straßenbahn AG",
            Id: @"bremerstrassenbahnag-d1d6a2",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q6716847", [@"power"] = @"transformer", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Bremer Straßenbahn AG", [@"operator:short"] = @"BSAG", [@"operator:wikidata"] = @"Q6716847", [@"power"] = @"transformer", },
            Terms: [@"bremer straßenbahn ag", @"bsag"]),
        new NsiItem(
            DisplayName: @"swb (Bremen)",
            Id: @"swb-d1d6a2",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q1740682", [@"power"] = @"transformer", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"swb", [@"operator:wikidata"] = @"Q1740682", [@"power"] = @"transformer", },
            Terms: [@"swb (Bremen)", @"swb", @"swb ag"]),
        new NsiItem(
            DisplayName: @"TenneT TSO",
            Id: @"tennettso-90172e",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q1662830", [@"power"] = @"transformer", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"TenneT TSO", [@"operator:wikidata"] = @"Q1662830", [@"power"] = @"transformer", },
            Terms: [@"tennet tso", @"tennet tso gmbh", @"transpower"]),
        new NsiItem(
            DisplayName: @"Wesernetz Bremen",
            Id: @"wesernetzbremen-d1d6a2",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q124371401", [@"power"] = @"transformer", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Wesernetz Bremen", [@"operator:wikidata"] = @"Q124371401", [@"power"] = @"transformer", },
            Terms: [@"wesernetz", @"wesernetz bremen", @"wesernetz bremen gmbh"]),
        new NsiItem(
            DisplayName: @"TenneT TSO",
            Id: @"tennettso-45db45",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q1662830", [@"route"] = @"power", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"TenneT TSO", [@"operator:wikidata"] = @"Q1662830", [@"route"] = @"power", [@"type"] = @"route", },
            Terms: [@"tennet", @"tennet tso", @"tennet tso gmbh"]),
        new NsiItem(
            DisplayName: @"Verkehrsverbund Bremen/Niedersachsen",
            Id: @"verkehrsverbundbremenniedersachsen-a57f9c",
            Tags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"network:wikidata"] = @"Q1306245", [@"public_transport"] = @"platform", },
            AddTags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"highway"] = @"bus_stop", [@"network"] = @"Verkehrsverbund Bremen/Niedersachsen", [@"network:short"] = @"VBN", [@"network:wikidata"] = @"Q1306245", [@"public_transport"] = @"platform", },
            Terms: [@"vbn", @"verkehrsverbund bremen/niedersachsen"]),
        new NsiItem(
            DisplayName: @"VBN",
            Id: @"vbn-b10cec",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q1306245", [@"railway"] = @"tram_stop", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"VBN", [@"network:wikidata"] = @"Q1306245", [@"operator"] = @"Bremer Straßenbahn AG", [@"operator:short"] = @"BSAG", [@"operator:wikidata"] = @"Q6716847", [@"railway"] = @"tram_stop", },
            Terms: [@"bremer straßenbahn ag", @"bsag", @"vbn"]),
        new NsiItem(
            DisplayName: @"Verkehrsverbund Bremen/Niedersachsen",
            Id: @"verkehrsverbundbremenniedersachsen-8902e5",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q1306245", [@"route"] = @"bus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Verkehrsverbund Bremen/Niedersachsen", [@"network:short"] = @"VBN", [@"network:wikidata"] = @"Q1306245", [@"route"] = @"bus", [@"type"] = @"route", },
            Terms: [@"vbn", @"verkehrsverbund bremen/niedersachsen"]),
        new NsiItem(
            DisplayName: @"VBN",
            Id: @"vbn-83b49b",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q1306245", [@"route"] = @"tram", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"VBN", [@"network:wikidata"] = @"Q1306245", [@"operator"] = @"Bremer Straßenbahn AG", [@"operator:short"] = @"BSAG", [@"operator:wikidata"] = @"Q6716847", [@"route"] = @"tram", [@"type"] = @"route", },
            Terms: [@"bremer straßenbahn ag", @"bsag", @"vbn"]),
    ];
}
