// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'us-ut.geojson'.</summary>
public static class NsiRegion_US_UT_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"Holiday Oil",
            Id: @"holidayoil-1196cc",
            Tags: new Dictionary<string, string> { [@"advertising"] = @"totem", [@"brand:wikidata"] = @"Q125941013", },
            AddTags: new Dictionary<string, string> { [@"advertising"] = @"totem", [@"brand"] = @"Holiday Oil", [@"brand:wikidata"] = @"Q125941013", },
            Terms: [@"holiday oil"]),
        new NsiItem(
            DisplayName: @"Columbia Bank",
            Id: @"columbiabank-2839b5",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand:wikidata"] = @"Q7881772", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand"] = @"Columbia Bank", [@"brand:wikidata"] = @"Q7881772", [@"operator"] = @"Columbia Bank", [@"operator:wikidata"] = @"Q7881772", },
            Terms: [@"columbia bank", @"umpqua bank"]),
        new NsiItem(
            DisplayName: @"HomeStreet Bank",
            Id: @"homestreetbank-9527f3",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand:wikidata"] = @"Q60762481", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand"] = @"HomeStreet Bank", [@"brand:wikidata"] = @"Q60762481", [@"operator"] = @"HomeStreet Bank", [@"operator:wikidata"] = @"Q60762481", },
            Terms: [@"homestreet bank"]),
        new NsiItem(
            DisplayName: @"Mountain America Credit Union",
            Id: @"mountainamericacreditunion-35eca1",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand:wikidata"] = @"Q6924862", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand"] = @"Mountain America Credit Union", [@"brand:wikidata"] = @"Q6924862", [@"operator"] = @"Mountain America Credit Union", [@"operator:wikidata"] = @"Q6924862", },
            Terms: [@"mountain america credit union"]),
        new NsiItem(
            DisplayName: @"Columbia Bank",
            Id: @"columbiabank-e80fe4",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand:wikidata"] = @"Q7881772", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand"] = @"Columbia Bank", [@"brand:wikidata"] = @"Q7881772", [@"name"] = @"Columbia Bank", },
            Terms: [@"columbia bank", @"umpqua bank"]),
        new NsiItem(
            DisplayName: @"HomeStreet Bank",
            Id: @"homestreetbank-80e3ed",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand:wikidata"] = @"Q60762481", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand"] = @"HomeStreet Bank", [@"brand:wikidata"] = @"Q60762481", [@"name"] = @"HomeStreet Bank", },
            Terms: [@"homestreet bank"]),
        new NsiItem(
            DisplayName: @"Mountain America Credit Union",
            Id: @"mountainamericacreditunion-1d85ab",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand:wikidata"] = @"Q6924862", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand"] = @"Mountain America Credit Union", [@"brand:wikidata"] = @"Q6924862", [@"name"] = @"Mountain America Credit Union", },
            Terms: [@"mountain america credit union"]),
        new NsiItem(
            DisplayName: @"Duck Donuts",
            Id: @"duckdonuts-6333a9",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"fast_food", [@"brand:wikidata"] = @"Q54958282", [@"cuisine"] = @"donut", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"fast_food", [@"brand"] = @"Duck Donuts", [@"brand:wikidata"] = @"Q54958282", [@"cuisine"] = @"donut", [@"name"] = @"Duck Donuts", [@"takeaway"] = @"yes", },
            Terms: [@"duck donuts", @"duck doughnuts"]),
        new NsiItem(
            DisplayName: @"Pick Up Stix",
            Id: @"pickupstix-cb7a0c",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"fast_food", [@"brand:wikidata"] = @"Q7190707", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"fast_food", [@"brand"] = @"Pick Up Stix", [@"brand:wikidata"] = @"Q7190707", [@"cuisine"] = @"asian", [@"name"] = @"Pick Up Stix", [@"takeaway"] = @"yes", },
            Terms: [@"pick up stix"]),
        new NsiItem(
            DisplayName: @"Holiday Oil",
            Id: @"holidayoil-b0257b",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"fuel", [@"brand:wikidata"] = @"Q125941013", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"fuel", [@"brand"] = @"Holiday Oil", [@"brand:wikidata"] = @"Q125941013", [@"name"] = @"Holiday Oil", },
            Terms: [@"holiday oil"]),
        new NsiItem(
            DisplayName: @"Joe's Crab Shack",
            Id: @"joescrabshack-c6bbaa",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"restaurant", [@"brand:wikidata"] = @"Q6208210", [@"cuisine"] = @"seafood", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"restaurant", [@"brand"] = @"Joe's Crab Shack", [@"brand:wikidata"] = @"Q6208210", [@"cuisine"] = @"seafood", [@"name"] = @"Joe's Crab Shack", },
            Terms: [@"joe's crab shack"]),
        new NsiItem(
            DisplayName: @"X Golf",
            Id: @"xgolf-8a88af",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q111585369", [@"leisure"] = @"sports_centre", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"X Golf", [@"brand:wikidata"] = @"Q111585369", [@"indoor"] = @"yes", [@"leisure"] = @"sports_centre", [@"name"] = @"X Golf", [@"sport"] = @"golf", },
            Terms: [@"x golf"]),
        new NsiItem(
            DisplayName: @"Cannabist",
            Id: @"cannabist-c9b3a7",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q114896590", [@"shop"] = @"cannabis", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"Cannabist", [@"brand:wikidata"] = @"Q114896590", [@"name"] = @"Cannabist", [@"shop"] = @"cannabis", },
            Terms: [@"cannabist"]),
        new NsiItem(
            DisplayName: @"Curaleaf",
            Id: @"curaleaf-4b9e8a",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q85754829", [@"shop"] = @"cannabis", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"Curaleaf", [@"brand:wikidata"] = @"Q85754829", [@"name"] = @"Curaleaf", [@"shop"] = @"cannabis", },
            Terms: [@"curaleaf"]),
        new NsiItem(
            DisplayName: @"C-A-L Ranch",
            Id: @"calranch-0790b6",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q132851714", [@"shop"] = @"country_store", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"C-A-L Ranch", [@"brand:wikidata"] = @"Q132851714", [@"name"] = @"C-A-L Ranch", [@"shop"] = @"country_store", },
            Terms: [@"c-a-l ranch"]),
        new NsiItem(
            DisplayName: @"Attic Salt",
            Id: @"atticsalt-ae6503",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q108409773", [@"shop"] = @"gift", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"Attic Salt", [@"brand:wikidata"] = @"Q108409773", [@"name"] = @"Attic Salt", [@"shop"] = @"gift", },
            Terms: [@"attic salt"]),
        new NsiItem(
            DisplayName: @"Image Studios",
            Id: @"imagestudios-0d42d5",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q110998819", [@"shop"] = @"hairdresser", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"Image Studios", [@"brand:wikidata"] = @"Q110998819", [@"name"] = @"Image Studios", [@"shop"] = @"hairdresser", },
            Terms: [@"image studios"]),
        new NsiItem(
            DisplayName: @"Mrs. Fields",
            Id: @"mrsfields-839ebf",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q3866841", [@"shop"] = @"pastry", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"Mrs. Fields", [@"brand:wikidata"] = @"Q3866841", [@"name"] = @"Mrs. Fields", [@"shop"] = @"pastry", },
            Terms: [@"mrs. fields"]),
        new NsiItem(
            DisplayName: @"Wheeler CAT",
            Id: @"wheelercat-753d55",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q109615516", [@"shop"] = @"trade", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"Wheeler CAT", [@"brand:wikidata"] = @"Q109615516", [@"name"] = @"Wheeler CAT", [@"shop"] = @"trade", [@"trade"] = @"construction_equipment", },
            Terms: [@"wheeler cat"]),
        new NsiItem(
            DisplayName: @"Unified Fire Authority",
            Id: @"unifiedfireauthority-7e1920",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"fire_station", [@"operator:wikidata"] = @"Q7884928", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"fire_station", [@"operator"] = @"Unified Fire Authority", [@"operator:wikidata"] = @"Q7884928", },
            Terms: [@"unified fire authority"]),
        new NsiItem(
            DisplayName: @"Utah Highway Patrol",
            Id: @"utahhighwaypatrol-b507af",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"police", [@"operator:wikidata"] = @"Q7902372", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"police", [@"operator"] = @"Utah Highway Patrol", [@"operator:short"] = @"UHP", [@"operator:wikidata"] = @"Q7902372", },
            Terms: [@"uhp", @"utah highway patrol"]),
        new NsiItem(
            DisplayName: @"Utah Department of Corrections",
            Id: @"utahdepartmentofcorrections-213f01",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"prison", [@"operator:wikidata"] = @"Q7902343", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"prison", [@"operator"] = @"Utah Department of Corrections", [@"operator:short"] = @"UDC", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q7902343", },
            Terms: [@"udc", @"utah department of corrections"]),
        new NsiItem(
            DisplayName: @"Easterseals-Goodwill",
            Id: @"eastersealsgoodwillnorthernrockymountain-9c67a8",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"recycling", [@"operator:wikidata"] = @"Q114923320", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"recycling", [@"operator"] = @"Easterseals-Goodwill Northern Rocky Mountain", [@"operator:wikidata"] = @"Q114923320", },
            Terms: [@"Easterseals-Goodwill", @"easterseals-goodwill northern rocky mountain"]),
        new NsiItem(
            DisplayName: @"Alpine School District",
            Id: @"alpineschooldistrict-614f2b",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q4735517", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Alpine School District", [@"operator:short"] = @"ASD", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q4735517", },
            Terms: [@"alpine school district", @"asd"]),
        new NsiItem(
            DisplayName: @"Box Elder School District",
            Id: @"boxelderschooldistrict-614f2b",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q81533950", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Box Elder School District", [@"operator:short"] = @"BESD", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q81533950", },
            Terms: [@"besd", @"box elder school district"]),
        new NsiItem(
            DisplayName: @"Granite School District",
            Id: @"graniteschooldistrict-614f2b",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q5595920", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Granite School District", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q5595920", },
            Terms: [@"granite school district"]),
        new NsiItem(
            DisplayName: @"Jordan School District",
            Id: @"jordanschooldistrict-614f2b",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q6276988", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Jordan School District", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q6276988", },
            Terms: [@"jordan school district"]),
        new NsiItem(
            DisplayName: @"Nebo School District",
            Id: @"neboschooldistrict-614f2b",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q6984625", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Nebo School District", [@"operator:short"] = @"NSD", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q6984625", },
            Terms: [@"nebo school district", @"nsd"]),
        new NsiItem(
            DisplayName: @"Provo City School District",
            Id: @"provocityschooldistrict-614f2b",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q7252784", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Provo City School District", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q7252784", },
            Terms: [@"provo city school district", @"provo school district"]),
        new NsiItem(
            DisplayName: @"Salt Lake City School District",
            Id: @"saltlakecityschooldistrict-614f2b",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q7405876", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Salt Lake City School District", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q7405876", },
            Terms: [@"salt lake city school district", @"salt lake school district"]),
        new NsiItem(
            DisplayName: @"Washington County School District",
            Id: @"washingtoncountyschooldistrict-614f2b",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q7971788", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Washington County School District", [@"operator:short"] = @"WCSD", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q7971788", },
            Terms: [@"washington county school district", @"wcsd"]),
        new NsiItem(
            DisplayName: @"Utah State Parks",
            Id: @"utahstateparks-7625dc",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator:wikidata"] = @"Q109292618", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator"] = @"Utah State Parks", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q109292618", },
            Terms: [@"utah state parks"]),
        new NsiItem(
            DisplayName: @"Utah State Parks",
            Id: @"utahstateparks-535432",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator:wikidata"] = @"Q109292618", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator"] = @"Utah State Parks", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q109292618", },
            Terms: [@"utah state parks"]),
        new NsiItem(
            DisplayName: @"Utah Department of Transportation",
            Id: @"utahdepartmentoftransportation-130bd9",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"monitoring_station", [@"operator:wikidata"] = @"Q2506783", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"monitoring_station", [@"operator"] = @"Utah Department of Transportation", [@"operator:short"] = @"UDOT", [@"operator:wikidata"] = @"Q2506783", },
            Terms: [@"udot", @"utah department of transportation"]),
        new NsiItem(
            DisplayName: @"Utah Department of Transportation",
            Id: @"utahdepartmentoftransportation-0839c4",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"surveillance", [@"operator:wikidata"] = @"Q2506783", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"surveillance", [@"operator"] = @"Utah Department of Transportation", [@"operator:short"] = @"UDOT", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q2506783", },
            Terms: [@"udot", @"utah department of transportation"]),
        new NsiItem(
            DisplayName: @"Rocky Mountain Power",
            Id: @"rockymountainpower-5acb27",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q2045479", [@"power"] = @"line", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Rocky Mountain Power", [@"operator:wikidata"] = @"Q2045479", [@"power"] = @"line", },
            Terms: [@"rocky mountain power"]),
        new NsiItem(
            DisplayName: @"Rocky Mountain Power",
            Id: @"rockymountainpower-900587",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q2045479", [@"power"] = @"minor_line", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Rocky Mountain Power", [@"operator:wikidata"] = @"Q2045479", [@"power"] = @"minor_line", },
            Terms: [@"rocky mountain power"]),
        new NsiItem(
            DisplayName: @"Rocky Mountain Power",
            Id: @"rockymountainpower-3a4568",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q2045479", [@"power"] = @"pole", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Rocky Mountain Power", [@"operator:wikidata"] = @"Q2045479", [@"power"] = @"pole", },
            Terms: [@"rocky mountain power"]),
        new NsiItem(
            DisplayName: @"Rocky Mountain Power",
            Id: @"rockymountainpower-d898d7",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q2045479", [@"power"] = @"substation", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Rocky Mountain Power", [@"operator:wikidata"] = @"Q2045479", [@"power"] = @"substation", },
            Terms: [@"rocky mountain power"]),
        new NsiItem(
            DisplayName: @"Rocky Mountain Power",
            Id: @"rockymountainpower-abd620",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q2045479", [@"power"] = @"tower", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Rocky Mountain Power", [@"operator:wikidata"] = @"Q2045479", [@"power"] = @"tower", },
            Terms: [@"rocky mountain power"]),
        new NsiItem(
            DisplayName: @"Rocky Mountain Power",
            Id: @"rockymountainpower-b2dffe",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q2045479", [@"power"] = @"transformer", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Rocky Mountain Power", [@"operator:wikidata"] = @"Q2045479", [@"power"] = @"transformer", },
            Terms: [@"rocky mountain power"]),
        new NsiItem(
            DisplayName: @"Connect Public Transit",
            Id: @"connectpublictransit-58d8ca",
            Tags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"network:wikidata"] = @"Q129798316", [@"public_transport"] = @"platform", },
            AddTags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"highway"] = @"bus_stop", [@"network"] = @"Connect Public Transit", [@"network:wikidata"] = @"Q129798316", [@"public_transport"] = @"platform", },
            Terms: [@"connect public transit", @"cvtd"]),
        new NsiItem(
            DisplayName: @"UTA",
            Id: @"uta-58d8ca",
            Tags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"network:wikidata"] = @"Q7902494", [@"public_transport"] = @"platform", },
            AddTags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"highway"] = @"bus_stop", [@"network"] = @"UTA", [@"network:wikidata"] = @"Q7902494", [@"public_transport"] = @"platform", },
            Terms: [@"uta"]),
        new NsiItem(
            DisplayName: @"FrontRunner",
            Id: @"uta-80e213",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q5505779", [@"railway"] = @"station", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"UTA", [@"network:wikidata"] = @"Q5505779", [@"public_transport"] = @"station", [@"railway"] = @"station", [@"train"] = @"yes", },
            Terms: [@"frontrunner", @"uta", @"uta frontrunner"]),
        new NsiItem(
            DisplayName: @"Connect Public Transit",
            Id: @"connectpublictransit-31c02a",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q129798316", [@"route"] = @"bus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Connect Public Transit", [@"network:wikidata"] = @"Q129798316", [@"route"] = @"bus", [@"type"] = @"route", },
            Terms: [@"connect public transit", @"cvtd"]),
        new NsiItem(
            DisplayName: @"UTA",
            Id: @"uta-31c02a",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q7902494", [@"route"] = @"bus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"UTA", [@"network:wikidata"] = @"Q7902494", [@"route"] = @"bus", [@"type"] = @"route", },
            Terms: [@"uta"]),
        new NsiItem(
            DisplayName: @"FrontRunner",
            Id: @"uta-4f331b",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q5505779", [@"route"] = @"train", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"UTA", [@"network:wikidata"] = @"Q5505779", [@"route"] = @"train", [@"type"] = @"route", },
            Terms: [@"frontrunner", @"uta", @"uta frontrunner"]),
    ];
}
