// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'jp-kanto.geojson'.</summary>
public static class NsiRegion_JP_KANTO_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"Big-A",
            Id: @"biga-3bcdfb",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q11330804", [@"shop"] = @"supermarket", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"Big-A", [@"brand:en"] = @"Big-A", [@"brand:ja"] = @"ビッグ・エー", [@"brand:wikidata"] = @"Q11330804", [@"name"] = @"Big-A", [@"name:en"] = @"Big-A", [@"name:ja"] = @"ビッグ・エー", [@"shop"] = @"supermarket", },
            Terms: [@"big-a", @"ビッグ・エー"]),
        new NsiItem(
            DisplayName: @"アピタ",
            Id: @"apita-43f63e",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q55384637", [@"shop"] = @"supermarket", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"アピタ", [@"brand:en"] = @"APITA", [@"brand:ja"] = @"アピタ", [@"brand:wikidata"] = @"Q55384637", [@"name"] = @"アピタ", [@"name:en"] = @"APITA", [@"name:ja"] = @"アピタ", [@"shop"] = @"supermarket", },
            Terms: [@"apita", @"アピタ"]),
        new NsiItem(
            DisplayName: @"いなげや",
            Id: @"inageya-3bcdfb",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q17193392", [@"shop"] = @"supermarket", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"いなげや", [@"brand:en"] = @"Inageya", [@"brand:ja"] = @"いなげや", [@"brand:wikidata"] = @"Q17193392", [@"name"] = @"いなげや", [@"name:en"] = @"Inageya", [@"name:ja"] = @"いなげや", [@"shop"] = @"supermarket", },
            Terms: [@"inageya", @"いなげや"]),
        new NsiItem(
            DisplayName: @"エコス",
            Id: @"ecos-126132",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q11289886", [@"shop"] = @"supermarket", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"エコス", [@"brand:en"] = @"Ecos", [@"brand:ja"] = @"エコス", [@"brand:wikidata"] = @"Q11289886", [@"name"] = @"エコス", [@"name:en"] = @"Ecos", [@"name:ja"] = @"エコス", [@"shop"] = @"supermarket", },
            Terms: [@"ecos", @"エコス"]),
        new NsiItem(
            DisplayName: @"オーケーストア",
            Id: @"okstore-bb7c11",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q11293184", [@"shop"] = @"supermarket", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"オーケー", [@"brand:en"] = @"OK", [@"brand:ja"] = @"オーケー", [@"brand:wikidata"] = @"Q11293184", [@"name"] = @"オーケーストア", [@"name:en"] = @"OK Store", [@"name:ja"] = @"オーケーストア", [@"shop"] = @"supermarket", },
            Terms: [@"ok", @"ok store", @"okストア", @"オーケー", @"オーケーストア"]),
        new NsiItem(
            DisplayName: @"オリンピック",
            Id: @"olympic-3bcdfb",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q11292764", [@"shop"] = @"supermarket", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"オリンピック", [@"brand:en"] = @"Olympic", [@"brand:ja"] = @"オリンピック", [@"brand:wikidata"] = @"Q11292764", [@"name"] = @"オリンピック", [@"name:en"] = @"Olympic", [@"name:ja"] = @"オリンピック", [@"shop"] = @"supermarket", },
            Terms: [@"olympic", @"オリンピック"]),
        new NsiItem(
            DisplayName: @"カスミ",
            Id: @"kasumi-3bcdfb",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q11294160", [@"shop"] = @"supermarket", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"カスミ", [@"brand:en"] = @"Kasumi", [@"brand:ja"] = @"カスミ", [@"brand:wikidata"] = @"Q11294160", [@"name"] = @"カスミ", [@"name:en"] = @"Kasumi", [@"name:ja"] = @"カスミ", [@"shop"] = @"supermarket", },
            Terms: [@"kasumi", @"カスミ"]),
        new NsiItem(
            DisplayName: @"グルメシティ",
            Id: @"gourmetcity-bb7c11",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q11300647", [@"shop"] = @"supermarket", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"グルメシティ", [@"brand:en"] = @"Gourmet City", [@"brand:ja"] = @"グルメシティ", [@"brand:wikidata"] = @"Q11300647", [@"name"] = @"グルメシティ", [@"name:en"] = @"Gourmet City", [@"name:ja"] = @"グルメシティ", [@"shop"] = @"supermarket", },
            Terms: [@"gourmet city", @"グルメシティ"]),
        new NsiItem(
            DisplayName: @"サミット",
            Id: @"summit-3bcdfb",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q11305129", [@"shop"] = @"supermarket", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"サミット", [@"brand:en"] = @"Summit", [@"brand:ja"] = @"サミット", [@"brand:wikidata"] = @"Q11305129", [@"name"] = @"サミット", [@"name:en"] = @"Summit", [@"name:ja"] = @"サミット", [@"shop"] = @"supermarket", },
            Terms: [@"summit", @"サミット"]),
        new NsiItem(
            DisplayName: @"サンディ",
            Id: @"sundi-3d6a22",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q11305717", [@"shop"] = @"supermarket", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"サンディ", [@"brand:en"] = @"Sundi", [@"brand:ja"] = @"サンディ", [@"brand:wikidata"] = @"Q11305717", [@"name"] = @"サンディ", [@"name:ja"] = @"サンディ", [@"shop"] = @"supermarket", },
            Terms: [@"sundi", @"サンディ"]),
        new NsiItem(
            DisplayName: @"とりせん",
            Id: @"torisen-3bcdfb",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q11273505", [@"shop"] = @"supermarket", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"とりせん", [@"brand:en"] = @"Torisen", [@"brand:ja"] = @"とりせん", [@"brand:wikidata"] = @"Q11273505", [@"name"] = @"とりせん", [@"name:en"] = @"Torisen", [@"name:ja"] = @"とりせん", [@"shop"] = @"supermarket", },
            Terms: [@"torisen", @"とりせん"]),
        new NsiItem(
            DisplayName: @"ベイシア",
            Id: @"beisia-92743a",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q11336776", [@"shop"] = @"supermarket", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"ベイシア", [@"brand:en"] = @"Beisia", [@"brand:ja"] = @"ベイシア", [@"brand:wikidata"] = @"Q11336776", [@"name"] = @"ベイシア", [@"name:en"] = @"Beisia", [@"name:ja"] = @"ベイシア", [@"shop"] = @"supermarket", },
            Terms: [@"beisia", @"ベイシア"]),
        new NsiItem(
            DisplayName: @"ベルク",
            Id: @"belc-3bcdfb",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q11337090", [@"shop"] = @"supermarket", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"ベルク", [@"brand:en"] = @"Belc", [@"brand:ja"] = @"ベルク", [@"brand:wikidata"] = @"Q11337090", [@"name"] = @"ベルク", [@"name:en"] = @"Belc", [@"name:ja"] = @"ベルク", [@"shop"] = @"supermarket", },
            Terms: [@"belc", @"ベルク"]),
        new NsiItem(
            DisplayName: @"マミーマート",
            Id: @"mammymart-3bcdfb",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q126935642", [@"shop"] = @"supermarket", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"マミーマート", [@"brand:en"] = @"Mammy Mart", [@"brand:ja"] = @"マミーマート", [@"brand:wikidata"] = @"Q126935642", [@"name"] = @"マミーマート", [@"name:en"] = @"Mammy Mart", [@"name:ja"] = @"マミーマート", [@"shop"] = @"supermarket", },
            Terms: [@"mammy mart", @"マミーマート"]),
        new NsiItem(
            DisplayName: @"マルエツ",
            Id: @"maruetsu-3bcdfb",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q11341197", [@"shop"] = @"supermarket", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"マルエツ", [@"brand:en"] = @"Maruetsu", [@"brand:ja"] = @"マルエツ", [@"brand:wikidata"] = @"Q11341197", [@"name"] = @"マルエツ", [@"name:en"] = @"Maruetsu", [@"name:ja"] = @"マルエツ", [@"shop"] = @"supermarket", },
            Terms: [@"maruetsu", @"マルエツ"]),
        new NsiItem(
            DisplayName: @"マルエツプチ",
            Id: @"maruetsupetit-3bcdfb",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q11341197", [@"shop"] = @"supermarket", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"マルエツ", [@"brand:en"] = @"Maruetsu", [@"brand:ja"] = @"マルエツ", [@"brand:wikidata"] = @"Q11341197", [@"name"] = @"マルエツプチ", [@"name:en"] = @"Maruetsu Petit", [@"name:ja"] = @"マルエツプチ", [@"shop"] = @"supermarket", },
            Terms: [@"maruetsu", @"maruetsu petit", @"マルエツ", @"マルエツプチ"]),
        new NsiItem(
            DisplayName: @"ヤオコー",
            Id: @"yaoko-3bcdfb",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q11344967", [@"shop"] = @"supermarket", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"ヤオコー", [@"brand:en"] = @"Yaoko", [@"brand:ja"] = @"ヤオコー", [@"brand:wikidata"] = @"Q11344967", [@"name"] = @"ヤオコー", [@"name:en"] = @"Yaoko", [@"name:ja"] = @"ヤオコー", [@"shop"] = @"supermarket", },
            Terms: [@"yaoko", @"ヤオコー"]),
        new NsiItem(
            DisplayName: @"ヨークマート",
            Id: @"yorkmart-3bcdfb",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q11346201", [@"shop"] = @"supermarket", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"ヨークマート", [@"brand:en"] = @"YorkMart", [@"brand:ja"] = @"ヨークマート", [@"brand:wikidata"] = @"Q11346201", [@"name"] = @"ヨークマート", [@"name:en"] = @"YorkMart", [@"name:ja"] = @"ヨークマート", [@"shop"] = @"supermarket", },
            Terms: [@"yorkmart", @"ヨークマート"]),
        new NsiItem(
            DisplayName: @"ライフ",
            Id: @"life-bb7c11",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q11346476", [@"shop"] = @"supermarket", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"ライフ", [@"brand:en"] = @"Life", [@"brand:ja"] = @"ライフ", [@"brand:wikidata"] = @"Q11346476", [@"name"] = @"ライフ", [@"name:en"] = @"Life", [@"name:ja"] = @"ライフ", [@"shop"] = @"supermarket", },
            Terms: [@"life", @"ライフ"]),
        new NsiItem(
            DisplayName: @"東急ストア",
            Id: @"tokyustore-466bb0",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q11526963", [@"shop"] = @"supermarket", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"東急ストア", [@"brand:en"] = @"Tokyu Store", [@"brand:ja"] = @"東急ストア", [@"brand:wikidata"] = @"Q11526963", [@"name"] = @"東急ストア", [@"name:en"] = @"Tokyu Store", [@"name:ja"] = @"東急ストア", [@"shop"] = @"supermarket", },
            Terms: [@"tokyu store", @"東急ストア"]),
        new NsiItem(
            DisplayName: @"綿半スーパーセンター",
            Id: @"watahansupercenter-150ace",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q126189811", [@"shop"] = @"supermarket", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"綿半スーパーセンター", [@"brand:en"] = @"Watahan Super Center", [@"brand:ja"] = @"綿半スーパーセンター", [@"brand:wikidata"] = @"Q126189811", [@"name"] = @"綿半スーパーセンター", [@"name:en"] = @"Watahan Super Center", [@"name:ja"] = @"綿半スーパーセンター", [@"shop"] = @"supermarket", },
            Terms: [@"watahan super center", @"綿半スーパーセンター"]),
        new NsiItem(
            DisplayName: @"肉のハナマサ",
            Id: @"hanamasa-4344cc",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q11326564", [@"shop"] = @"supermarket", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"肉のハナマサ", [@"brand:en"] = @"Hanamasa", [@"brand:ja"] = @"肉のハナマサ", [@"brand:wikidata"] = @"Q11326564", [@"name"] = @"肉のハナマサ", [@"name:en"] = @"Hanamasa", [@"name:ja"] = @"肉のハナマサ", [@"shop"] = @"supermarket", },
            Terms: [@"hanamasa", @"ハナマサ", @"ハナマサ肉", @"肉のハナマサ"]),
    ];
}
