// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'es-s.geojson'.</summary>
public static class NsiRegion_ES_S_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"Torrebici",
            Id: @"torrebici-a485b3",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bicycle_rental", [@"brand:wikidata"] = @"Q117074164", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bicycle_rental", [@"authentication:app"] = @"yes", [@"bicycle_rental"] = @"dropoff_point", [@"brand"] = @"Torrebici", [@"brand:wikidata"] = @"Q117074164", [@"fee"] = @"yes", [@"name"] = @"Torrebici", [@"network"] = @"Torrebici", [@"network:wikidata"] = @"Q117074164", [@"operator"] = @"Movilidad Urbana Sostenible SL", [@"operator:short"] = @"MOVUS", [@"operator:type"] = @"private", [@"operator:wikidata"] = @"Q117079539", [@"rental"] = @"ebike", },
            Terms: [@"movilidad urbana sostenible sl", @"movus", @"torrebici"]),
        new NsiItem(
            DisplayName: @"Ayuntamiento de Los Corrales de Buelna",
            Id: @"ayuntamientodeloscorralesdebuelna-89268f",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"drinking_water", [@"operator:wikidata"] = @"Q60051355", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"drinking_water", [@"operator"] = @"Ayuntamiento de Los Corrales de Buelna", [@"operator:wikidata"] = @"Q60051355", },
            Terms: [@"ayuntamiento de los corrales de buelna"]),
        new NsiItem(
            DisplayName: @"Ayuntamiento de San Felices de Buelna",
            Id: @"ayuntamientodesanfelicesdebuelna-89268f",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"drinking_water", [@"operator:wikidata"] = @"Q60051501", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"drinking_water", [@"operator"] = @"Ayuntamiento de San Felices de Buelna", [@"operator:wikidata"] = @"Q60051501", },
            Terms: [@"ayuntamiento de san felices de buelna"]),
        new NsiItem(
            DisplayName: @"Gobierno de Cantabria",
            Id: @"gobiernodecantabria-ca6b3a",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q578851", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Gobierno de Cantabria", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q578851", },
            Terms: [@"gobierno de cantabria"]),
        new NsiItem(
            DisplayName: @"Ayuntamiento de Santander",
            Id: @"ayuntamientodesantander-b74e42",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"monitoring_station", [@"operator:wikidata"] = @"Q5714934", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"monitoring_station", [@"operator"] = @"Ayuntamiento de Santander", [@"operator:wikidata"] = @"Q5714934", },
            Terms: [@"ayuntamiento de santander"]),
        new NsiItem(
            DisplayName: @"Viesgo Distribución Eléctrica",
            Id: @"viesgodistribucionelectrica-3aff86",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q5829004", [@"power"] = @"line", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Viesgo Distribución Eléctrica", [@"operator:wikidata"] = @"Q5829004", [@"power"] = @"line", },
            Terms: [@"viesgo", @"viesgo distribución eléctrica", @"viesgo distribución eléctrica, s.l"]),
        new NsiItem(
            DisplayName: @"Viesgo Distribución Eléctrica",
            Id: @"viesgodistribucionelectrica-cf4a46",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q5829004", [@"power"] = @"minor_line", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Viesgo Distribución Eléctrica", [@"operator:wikidata"] = @"Q5829004", [@"power"] = @"minor_line", },
            Terms: [@"viesgo", @"viesgo distribución eléctrica", @"viesgo distribución eléctrica, s.l"]),
        new NsiItem(
            DisplayName: @"Viesgo Distribución Eléctrica",
            Id: @"viesgodistribucionelectrica-2771ba",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q5829004", [@"power"] = @"pole", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Viesgo Distribución Eléctrica", [@"operator:wikidata"] = @"Q5829004", [@"power"] = @"pole", },
            Terms: [@"viesgo", @"viesgo distribución eléctrica", @"viesgo distribución eléctrica, s.l"]),
        new NsiItem(
            DisplayName: @"Viesgo Distribución Eléctrica",
            Id: @"viesgodistribucionelectrica-f5fe9f",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q5829004", [@"power"] = @"substation", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Viesgo Distribución Eléctrica", [@"operator:wikidata"] = @"Q5829004", [@"power"] = @"substation", },
            Terms: [@"viesgo", @"viesgo distribución eléctrica"]),
        new NsiItem(
            DisplayName: @"Viesgo Distribución Eléctrica",
            Id: @"viesgodistribucionelectrica-77857c",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q5829004", [@"power"] = @"tower", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Viesgo Distribución Eléctrica", [@"operator:wikidata"] = @"Q5829004", [@"power"] = @"tower", },
            Terms: [@"viesgo", @"viesgo distribución eléctrica", @"viesgo distribución eléctrica, s.l"]),
        new NsiItem(
            DisplayName: @"Viesgo Distribución Eléctrica",
            Id: @"viesgodistribucionelectrica-9029f9",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q5829004", [@"power"] = @"transformer", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Viesgo Distribución Eléctrica", [@"operator:wikidata"] = @"Q5829004", [@"power"] = @"transformer", },
            Terms: [@"viesgo", @"viesgo distribución eléctrica"]),
        new NsiItem(
            DisplayName: @"Cercanías Cantabria",
            Id: @"cercaniascantabria-f79b38",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q1054773", [@"railway"] = @"station", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Cercanías Cantabria", [@"network:wikidata"] = @"Q1054773", [@"operator"] = @"Renfe", [@"operator:wikidata"] = @"Q2476154", [@"public_transport"] = @"station", [@"railway"] = @"station", [@"train"] = @"yes", },
            Terms: [@"cercanías cantabria", @"cercanías santander", @"renfe"]),
        new NsiItem(
            DisplayName: @"Cercanías Cantabria",
            Id: @"cercaniascantabria-f28461",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q1054773", [@"route"] = @"train", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Cercanías Cantabria", [@"network:wikidata"] = @"Q1054773", [@"operator"] = @"Renfe", [@"operator:wikidata"] = @"Q2476154", [@"route"] = @"train", [@"type"] = @"route", },
            Terms: [@"cercanías cantabria", @"cercanías santander", @"renfe"]),
    ];
}
