// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'id-sm'.</summary>
public static class NsiRegion_ID_SM
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"PT Pembangkitan Jawa Bali",
            Id: @"ptpembangkitanjawabali-e47eed",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q12504353", [@"power"] = @"plant", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"PT Pembangkitan Jawa Bali", [@"operator:short"] = @"PJB", [@"operator:wikidata"] = @"Q12504353", [@"power"] = @"plant", },
            Terms: [@"pembangkitan jawa bali", @"pjb", @"pt pembangkitan jawa bali", @"pt pjb"]),
        new NsiItem(
            DisplayName: @"KAI",
            Id: @"kai-6af736",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q2745027", [@"railway"] = @"station", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"KAI", [@"network:wikidata"] = @"Q2745027", [@"public_transport"] = @"station", [@"railway"] = @"station", [@"train"] = @"yes", },
            Terms: [@"kai"]),
        new NsiItem(
            DisplayName: @"KAI Bandara",
            Id: @"kaibandara-6af736",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q19752643", [@"railway"] = @"station", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"KAI Bandara", [@"network:wikidata"] = @"Q19752643", [@"public_transport"] = @"station", [@"railway"] = @"station", [@"train"] = @"yes", },
            Terms: [@"kai bandara"]),
        new NsiItem(
            DisplayName: @"KAI",
            Id: @"kai-b7b423",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q2745027", [@"route"] = @"train", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"KAI", [@"network:wikidata"] = @"Q2745027", [@"route"] = @"train", [@"type"] = @"route", },
            Terms: [@"kai"]),
        new NsiItem(
            DisplayName: @"KAI Bandara",
            Id: @"kaibandara-b7b423",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q19752643", [@"route"] = @"train", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"KAI Bandara", [@"network:wikidata"] = @"Q19752643", [@"route"] = @"train", [@"type"] = @"route", },
            Terms: [@"kai bandara"]),
    ];
}
