// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'cd'.</summary>
public static class NsiRegion_CD
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"Shiptech",
            Id: @"shiptech-960b09",
            Tags: new Dictionary<string, string> { [@"advertising"] = @"totem", [@"brand:wikidata"] = @"Q116894475", },
            AddTags: new Dictionary<string, string> { [@"advertising"] = @"totem", [@"brand"] = @"Shiptech", [@"brand:wikidata"] = @"Q116894475", },
            Terms: [@"shiptech"]),
        new NsiItem(
            DisplayName: @"Access Bank",
            Id: @"accessbank-04aa13",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand:wikidata"] = @"Q4672418", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand"] = @"Access Bank", [@"brand:wikidata"] = @"Q4672418", [@"operator"] = @"Access Bank", [@"operator:wikidata"] = @"Q4672418", },
            Terms: [@"access bank", @"diamond bank"]),
        new NsiItem(
            DisplayName: @"Attijariwafa Bank (التجاري وفا بنك)",
            Id: @"attijariwafabank-3e1123",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand:wikidata"] = @"Q758052", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand"] = @"Attijariwafa Bank", [@"brand:ar"] = @"التجاري وفا بنك", [@"brand:en"] = @"Attijariwafa Bank", [@"brand:wikidata"] = @"Q758052", [@"operator"] = @"Attijariwafa Bank", [@"operator:wikidata"] = @"Q758052", },
            Terms: [@"Attijariwafa Bank (التجاري وفا بنك)", @"attijariwafa bank", @"attijariwafa bank التجاري وفا بنك", @"التجاري وفا بنك"]),
        new NsiItem(
            DisplayName: @"Bank of Africa",
            Id: @"bankofafrica-daf274",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand:wikidata"] = @"Q2882627", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand"] = @"Bank of Africa", [@"brand:wikidata"] = @"Q2882627", [@"operator"] = @"Bank of Africa", [@"operator:wikidata"] = @"Q2882627", },
            Terms: [@"bank of africa"]),
        new NsiItem(
            DisplayName: @"Equity Bank (Congo)",
            Id: @"equitybank-39f68b",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand:wikidata"] = @"Q21178738", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand"] = @"Equity Bank", [@"brand:wikidata"] = @"Q21178738", [@"operator"] = @"Equity Bank", [@"operator:wikidata"] = @"Q21178738", },
            Terms: [@"Equity Bank (Congo)", @"equity bank"]),
        new NsiItem(
            DisplayName: @"UBA",
            Id: @"uba-69edd8",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand:wikidata"] = @"Q513457", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand"] = @"UBA", [@"brand:wikidata"] = @"Q513457", [@"operator"] = @"UBA", [@"operator:wikidata"] = @"Q513457", },
            Terms: [@"uba"]),
        new NsiItem(
            DisplayName: @"Access Bank",
            Id: @"accessbank-155277",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand:wikidata"] = @"Q4672418", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand"] = @"Access Bank", [@"brand:wikidata"] = @"Q4672418", [@"name"] = @"Access Bank", },
            Terms: [@"access bank", @"diamond bank"]),
        new NsiItem(
            DisplayName: @"Attijariwafa Bank (التجاري وفا بنك)",
            Id: @"attijariwafabank-efc165",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand:wikidata"] = @"Q758052", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand"] = @"Attijariwafa Bank", [@"brand:ar"] = @"التجاري وفا بنك", [@"brand:en"] = @"Attijariwafa Bank", [@"brand:wikidata"] = @"Q758052", [@"name:ar"] = @"التجاري وفا بنك", [@"name:en"] = @"Attijariwafa Bank", },
            Terms: [@"Attijariwafa Bank (التجاري وفا بنك)", @"attijariwafa bank", @"attijariwafa bank التجاري وفا بنك", @"التجاري وفا بنك"]),
        new NsiItem(
            DisplayName: @"Bank of Africa",
            Id: @"bankofafrica-dae5c5",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand:wikidata"] = @"Q2882627", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand"] = @"Bank of Africa", [@"brand:wikidata"] = @"Q2882627", [@"name"] = @"Bank of Africa", [@"short_name"] = @"BOA", },
            Terms: [@"bank of africa", @"boa"]),
        new NsiItem(
            DisplayName: @"Equity Bank (Congo)",
            Id: @"equitybank-0eac7f",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand:wikidata"] = @"Q21178738", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand"] = @"Equity Bank", [@"brand:wikidata"] = @"Q21178738", [@"name"] = @"Equity Bank", },
            Terms: [@"Equity Bank (Congo)", @"equity bank"]),
        new NsiItem(
            DisplayName: @"UBA",
            Id: @"uba-95540f",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand:wikidata"] = @"Q513457", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand"] = @"UBA", [@"brand:wikidata"] = @"Q513457", [@"name"] = @"UBA", [@"official_name"] = @"United Bank for Africa", },
            Terms: [@"uba", @"united bank for africa"]),
        new NsiItem(
            DisplayName: @"Galito's",
            Id: @"galitos-00ffa4",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"fast_food", [@"brand:wikidata"] = @"Q116619555", [@"cuisine"] = @"chicken", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"fast_food", [@"brand"] = @"Galito's", [@"brand:wikidata"] = @"Q116619555", [@"cuisine"] = @"chicken", [@"name"] = @"Galito's", [@"takeaway"] = @"yes", },
            Terms: [@"galito's"]),
        new NsiItem(
            DisplayName: @"Shiptech",
            Id: @"shiptech-ddc474",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"fuel", [@"brand:wikidata"] = @"Q116894475", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"fuel", [@"brand"] = @"Shiptech", [@"brand:wikidata"] = @"Q116894475", [@"name"] = @"Shiptech", },
            Terms: [@"shiptech"]),
        new NsiItem(
            DisplayName: @"RocoMamas",
            Id: @"rocomamas-a7acfa",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"restaurant", [@"brand:wikidata"] = @"Q123034964", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"restaurant", [@"brand"] = @"RocoMamas", [@"brand:wikidata"] = @"Q123034964", [@"cuisine"] = @"burger", [@"name"] = @"RocoMamas", },
            Terms: [@"rocomamas"]),
        new NsiItem(
            DisplayName: @"Orange",
            Id: @"orange-87fd86",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q1431486", [@"shop"] = @"mobile_phone", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"Orange", [@"brand:wikidata"] = @"Q1431486", [@"name"] = @"Orange", [@"shop"] = @"mobile_phone", },
            Terms: [@"agence orange", @"orange", @"orange egypt"]),
        new NsiItem(
            DisplayName: @"Vodacom (D. R. Congo)",
            Id: @"vodacom-dd47b4",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q130477507", [@"shop"] = @"mobile_phone", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"Vodacom Congo", [@"brand:wikidata"] = @"Q130477507", [@"name"] = @"Vodacom", [@"shop"] = @"mobile_phone", },
            Terms: [@"Vodacom (D. R. Congo)", @"vodacom congo", @"vodacom shop", @"vodashop"]),
        new NsiItem(
            DisplayName: @"Shoprite (Africa)",
            Id: @"shoprite-502f12",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q1857639", [@"shop"] = @"supermarket", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"Shoprite", [@"brand:wikidata"] = @"Q1857639", [@"name"] = @"Shoprite", [@"shop"] = @"supermarket", },
            Terms: [@"Shoprite (Africa)", @"shoprite"]),
        new NsiItem(
            DisplayName: @"Serena Hotels",
            Id: @"serenahotels-b76fe0",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q7453121", [@"tourism"] = @"hotel", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"Serena Hotels", [@"brand:wikidata"] = @"Q7453121", [@"name"] = @"Serena Hotels", [@"tourism"] = @"hotel", },
            Terms: [@"serena hotels"]),
        new NsiItem(
            DisplayName: @"Ministère de la Justice (DRC)",
            Id: @"ministeredelajustice-160188",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"courthouse", [@"operator:wikidata"] = @"Q97185601", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"courthouse", [@"operator"] = @"Ministère de la Justice", [@"operator:wikidata"] = @"Q97185601", },
            Terms: [@"Ministère de la Justice (DRC)", @"ministère de la justice"]),
        new NsiItem(
            DisplayName: @"Vodacom (D. R. Congo)",
            Id: @"vodacomcongo-5540e6",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"mast", [@"operator:wikidata"] = @"Q130477507", [@"tower:type"] = @"communication", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"mast", [@"operator"] = @"Vodacom Congo", [@"operator:wikidata"] = @"Q130477507", [@"tower:type"] = @"communication", },
            Terms: [@"Vodacom (D. R. Congo)", @"vodacom", @"vodacom congo"]),
        new NsiItem(
            DisplayName: @"Vodacom (D. R. Congo)",
            Id: @"vodacomcongo-e13b02",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"tower", [@"operator:wikidata"] = @"Q130477507", [@"tower:type"] = @"communication", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"tower", [@"operator"] = @"Vodacom Congo", [@"operator:wikidata"] = @"Q130477507", [@"tower:type"] = @"communication", },
            Terms: [@"Vodacom (D. R. Congo)", @"vodacom", @"vodacom congo"]),
        new NsiItem(
            DisplayName: @"SNCC",
            Id: @"sncc-374ff8",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q1481581", [@"power"] = @"catenary_mast", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"SNCC", [@"operator:wikidata"] = @"Q1481581", [@"power"] = @"catenary_mast", },
            Terms: [@"sncc", @"société nationale des chemins de fer du congo"]),
        new NsiItem(
            DisplayName: @"SNCC",
            Id: @"sncc-398c7e",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q1481581", [@"route"] = @"railway", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"SNCC", [@"operator:wikidata"] = @"Q1481581", [@"route"] = @"railway", [@"type"] = @"route", },
            Terms: [@"sncc", @"société nationale des chemins de fer du congo"]),
    ];
}
