// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'dk-82.geojson'.</summary>
public static class NsiRegion_DK_82_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"Aarhus Kommune",
            Id: @"aarhuskommune-578125",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bicycle_rental", [@"brand:wikidata"] = @"Q240262", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bicycle_rental", [@"brand"] = @"Aarhus Kommune", [@"brand:wikidata"] = @"Q240262", [@"name"] = @"Aarhus Kommune", [@"operator"] = @"Aarhus Kommune", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q240262", },
            Terms: [@"aarhus kommune", @"århus kommune"]),
        new NsiItem(
            DisplayName: @"Aarhus Kommune",
            Id: @"aarhuskommune-258737",
            Tags: new Dictionary<string, string> { [@"advertising"] = @"column", [@"operator:wikidata"] = @"Q240262", },
            AddTags: new Dictionary<string, string> { [@"advertising"] = @"column", [@"operator"] = @"Aarhus Kommune", [@"operator:wikidata"] = @"Q240262", },
            Terms: [@"aarhus kommune"]),
        new NsiItem(
            DisplayName: @"Midt- og Vestjyllands Politi",
            Id: @"midtogvestjyllandspoliti-1622d4",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"police", [@"operator:wikidata"] = @"Q81814786", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"police", [@"operator"] = @"Midt- og Vestjyllands Politi", [@"operator:wikidata"] = @"Q81814786", },
            Terms: [@"midt- og vestjyllands politi"]),
        new NsiItem(
            DisplayName: @"Sydøstjyllands Politi",
            Id: @"sydostjyllandspoliti-00bac1",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"police", [@"operator:wikidata"] = @"Q98645768", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"police", [@"operator"] = @"Sydøstjyllands Politi", [@"operator:wikidata"] = @"Q98645768", },
            Terms: [@"sydøstjyllands politi"]),
        new NsiItem(
            DisplayName: @"Lalandia Søndervig",
            Id: @"lalandiasondervig-12aa71",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"recycling", [@"operator:wikidata"] = @"Q113706903", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"recycling", [@"operator"] = @"Lalandia Søndervig", [@"operator:wikidata"] = @"Q113706903", },
            Terms: [@"lalandia", @"lalandia søndervig"]),
    ];
}
