// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'ch-ag.geojson'.</summary>
public static class NsiRegion_CH_AG_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"Energiedienst",
            Id: @"energiedienst-6cf9a8",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"charging_station", [@"operator:wikidata"] = @"Q1341261", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"charging_station", [@"operator"] = @"Energiedienst", [@"operator:wikidata"] = @"Q1341261", },
            Terms: [@"energiedienst"]),
        new NsiItem(
            DisplayName: @"NaturEnergie",
            Id: @"naturenergie-6cf9a8",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"charging_station", [@"operator:wikidata"] = @"Q1285415", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"charging_station", [@"operator"] = @"NaturEnergie", [@"operator:wikidata"] = @"Q1285415", },
            Terms: [@"naturenergie"]),
        new NsiItem(
            DisplayName: @"Energiedienst",
            Id: @"energiedienst-0a01b8",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"charge_point", [@"operator:wikidata"] = @"Q1341261", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"charge_point", [@"operator"] = @"Energiedienst", [@"operator:wikidata"] = @"Q1341261", },
            Terms: [@"energiedienst"]),
        new NsiItem(
            DisplayName: @"NaturEnergie",
            Id: @"naturenergie-0a01b8",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"charge_point", [@"operator:wikidata"] = @"Q1285415", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"charge_point", [@"operator"] = @"NaturEnergie", [@"operator:wikidata"] = @"Q1285415", },
            Terms: [@"naturenergie"]),
        new NsiItem(
            DisplayName: @"Erdgas Zentralschweiz",
            Id: @"erdgaszentralschweiz-c2536a",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"pipeline", [@"operator:wikidata"] = @"Q1276501", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"pipeline", [@"operator"] = @"Erdgas Zentralschweiz", [@"operator:wikidata"] = @"Q1276501", [@"substance"] = @"gas", },
            Terms: [@"erdgas zentralschweiz"]),
        new NsiItem(
            DisplayName: @"Erdgas Zentralschweiz",
            Id: @"erdgaszentralschweiz-c0f0d1",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q1276501", [@"pipeline"] = @"substation", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Erdgas Zentralschweiz", [@"operator:wikidata"] = @"Q1276501", [@"pipeline"] = @"substation", [@"substance"] = @"gas", },
            Terms: [@"erdgas zentralschweiz"]),
        new NsiItem(
            DisplayName: @"AEW",
            Id: @"aew-3c10bb",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q291519", [@"power"] = @"line", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"AEW", [@"operator:wikidata"] = @"Q291519", [@"power"] = @"line", },
            Terms: [@"aew", @"aew energie"]),
        new NsiItem(
            DisplayName: @"ATEL",
            Id: @"atel-151882",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q691286", [@"power"] = @"line", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"ATEL", [@"operator:wikidata"] = @"Q691286", [@"power"] = @"line", },
            Terms: [@"atel"]),
        new NsiItem(
            DisplayName: @"AEW",
            Id: @"aew-f9871c",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q291519", [@"power"] = @"minor_line", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"AEW", [@"operator:wikidata"] = @"Q291519", [@"power"] = @"minor_line", },
            Terms: [@"aew", @"aew energie"]),
        new NsiItem(
            DisplayName: @"ATEL",
            Id: @"atel-abd8f7",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q691286", [@"power"] = @"minor_line", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"ATEL", [@"operator:wikidata"] = @"Q691286", [@"power"] = @"minor_line", },
            Terms: [@"atel"]),
        new NsiItem(
            DisplayName: @"AEW",
            Id: @"aew-6b178d",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q291519", [@"power"] = @"pole", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"AEW", [@"operator:wikidata"] = @"Q291519", [@"power"] = @"pole", },
            Terms: [@"aew", @"aew energie"]),
        new NsiItem(
            DisplayName: @"ATEL",
            Id: @"atel-4b9791",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q691286", [@"power"] = @"pole", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"ATEL", [@"operator:wikidata"] = @"Q691286", [@"power"] = @"pole", },
            Terms: [@"atel"]),
        new NsiItem(
            DisplayName: @"AEW",
            Id: @"aew-f6524b",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q291519", [@"power"] = @"substation", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"AEW", [@"operator:wikidata"] = @"Q291519", [@"power"] = @"substation", },
            Terms: [@"aew", @"aew energie"]),
        new NsiItem(
            DisplayName: @"EWW (Schweiz)",
            Id: @"eww-3d4bad",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q15445360", [@"power"] = @"substation", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"EWW", [@"operator:wikidata"] = @"Q15445360", [@"power"] = @"substation", },
            Terms: [@"EWW (Schweiz)", @"eww"]),
        new NsiItem(
            DisplayName: @"AEW",
            Id: @"aew-e2ba80",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q291519", [@"power"] = @"tower", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"AEW", [@"operator:wikidata"] = @"Q291519", [@"power"] = @"tower", },
            Terms: [@"aew", @"aew energie"]),
        new NsiItem(
            DisplayName: @"ATEL",
            Id: @"atel-ca3aad",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q691286", [@"power"] = @"tower", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"ATEL", [@"operator:wikidata"] = @"Q691286", [@"power"] = @"tower", },
            Terms: [@"atel"]),
        new NsiItem(
            DisplayName: @"AEW",
            Id: @"aew-5e4e63",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q291519", [@"power"] = @"transformer", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"AEW", [@"operator:wikidata"] = @"Q291519", [@"power"] = @"transformer", },
            Terms: [@"aew", @"aew energie"]),
        new NsiItem(
            DisplayName: @"EWW (Schweiz)",
            Id: @"eww-3a1ab2",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q15445360", [@"power"] = @"transformer", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"EWW", [@"operator:wikidata"] = @"Q15445360", [@"power"] = @"transformer", },
            Terms: [@"EWW (Schweiz)", @"eww"]),
    ];
}
