// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'br-rj.geojson'.</summary>
public static class NsiRegion_BR_RJ_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"Prefeitura do Rio de Janeiro",
            Id: @"prefeituradoriodejaneiro-4e3c1b",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"clinic", [@"operator:wikidata"] = @"Q53930899", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"clinic", [@"healthcare"] = @"clinic", [@"operator"] = @"Prefeitura do Rio de Janeiro", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q53930899", },
            Terms: [@"prefeitura da cidade do rio de janeiro", @"prefeitura do rio", @"prefeitura do rio de janeiro"]),
        new NsiItem(
            DisplayName: @"Prefeitura Municipal de Seropédica",
            Id: @"prefeituramunicipaldeseropedica-4e3c1b",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"clinic", [@"operator:wikidata"] = @"Q988677", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"clinic", [@"healthcare"] = @"clinic", [@"operator"] = @"Prefeitura Municipal de Seropédica", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q988677", },
            Terms: [@"prefeitura municipal de seropédica"]),
        new NsiItem(
            DisplayName: @"Prefeitura do Rio de Janeiro",
            Id: @"prefeituradoriodejaneiro-53a359",
            Tags: new Dictionary<string, string> { [@"education"] = @"kindergarten", [@"operator:wikidata"] = @"Q53930899", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"kindergarten", [@"education"] = @"kindergarten", [@"operator"] = @"Prefeitura do Rio de Janeiro", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q53930899", },
            Terms: [@"prefeitura do rio", @"prefeitura do rio de janeiro"]),
        new NsiItem(
            DisplayName: @"Polícia Civil do Estado do Rio de Janeiro",
            Id: @"policiacivildoestadodoriodejaneiro-347580",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"police", [@"operator:wikidata"] = @"Q5124531", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"police", [@"operator"] = @"Polícia Civil do Estado do Rio de Janeiro", [@"operator:wikidata"] = @"Q5124531", },
            Terms: [@"polícia civil do estado do rio de janeiro"]),
        new NsiItem(
            DisplayName: @"Polícia Militar do Estado do Rio de Janeiro",
            Id: @"policiamilitardoestadodoriodejaneiro-347580",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"police", [@"operator:wikidata"] = @"Q6852137", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"police", [@"operator"] = @"Polícia Militar do Estado do Rio de Janeiro", [@"operator:short"] = @"PMERJ", [@"operator:wikidata"] = @"Q6852137", },
            Terms: [@"pmerj", @"polícia militar do estado do rio de janeiro"]),
        new NsiItem(
            DisplayName: @"Governo do Estado do Rio de Janeiro",
            Id: @"governodoestadodoriodejaneiro-df8785",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q48855361", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Governo do Estado do Rio de Janeiro", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q48855361", },
            Terms: [@"governo do estado do rio de janeiro"]),
        new NsiItem(
            DisplayName: @"Prefeitura do Rio de Janeiro",
            Id: @"prefeituradoriodejaneiro-df8785",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q53930899", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Prefeitura do Rio de Janeiro", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q53930899", },
            Terms: [@"prefeitura do rio", @"prefeitura do rio de janeiro", @"prefeitura municipal do rio de janeiro"]),
        new NsiItem(
            DisplayName: @"Prefeitura Municipal de Armação dos Búzios",
            Id: @"prefeituramunicipaldearmacaodosbuzios-df8785",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q680119", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Prefeitura Municipal de Armação dos Búzios", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q680119", },
            Terms: [@"prefeitura municipal de armação dos búzios"]),
        new NsiItem(
            DisplayName: @"Prefeitura Municipal de Maricá",
            Id: @"prefeituramunicipaldemarica-df8785",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q847037", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Prefeitura Municipal de Maricá", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q847037", },
            Terms: [@"prefeitura municipal de maricá"]),
        new NsiItem(
            DisplayName: @"Prefeitura Municipal de Seropédica",
            Id: @"prefeituramunicipaldeseropedica-df8785",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q988677", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Prefeitura Municipal de Seropédica", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q988677", },
            Terms: [@"prefeitura municipal de seropédica"]),
        new NsiItem(
            DisplayName: @"Secretaria de Educação do Estado do Rio de Janeiro",
            Id: @"secretariadeeducacaodoestadodoriodejaneiro-df8785",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q56351917", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Secretaria de Educação do Estado do Rio de Janeiro", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q56351917", },
            Terms: [@"secretaria de educação do estado do rio de janeiro"]),
        new NsiItem(
            DisplayName: @"Secretaria Municipal de Educação de Campos dos Goytacazes",
            Id: @"secretariamunicipaldeeducacaodecamposdosgoytacazes-df8785",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q56450025", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Secretaria Municipal de Educação de Campos dos Goytacazes", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q56450025", },
            Terms: [@"secretaria municipal de educação de campos dos goytacazes"]),
        new NsiItem(
            DisplayName: @"Secretaria Municipal de Educação de Itaperuna",
            Id: @"secretariamunicipaldeeducacaodeitaperuna-df8785",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q1675245", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Secretaria Municipal de Educação de Itaperuna", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q1675245", },
            Terms: [@"secretaria municipal de educação de itaperuna"]),
        new NsiItem(
            DisplayName: @"Secretaria Municipal de Educação de Rio das Ostras",
            Id: @"secretariamunicipaldeeducacaoderiodasostras-df8785",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q61930515", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Secretaria Municipal de Educação de Rio das Ostras", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q61930515", },
            Terms: [@"secretaria municipal de educação de rio das ostras", @"semede"]),
        new NsiItem(
            DisplayName: @"Prefeitura Municipal de Rio das Ostras",
            Id: @"prefeituramunicipalderiodasostras-5bd13a",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"social_facility", [@"operator:wikidata"] = @"Q61930515", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"social_facility", [@"operator"] = @"Prefeitura Municipal de Rio das Ostras", [@"operator:short"] = @"PMRO", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q61930515", },
            Terms: [@"pmro", @"prefeitura municipal de rio das ostras"]),
        new NsiItem(
            DisplayName: @"Prefeitura Municipal de Maricá",
            Id: @"prefeituramunicipaldemarica-768e06",
            Tags: new Dictionary<string, string> { [@"emergency"] = @"siren", [@"operator:wikidata"] = @"Q847037", },
            AddTags: new Dictionary<string, string> { [@"emergency"] = @"siren", [@"operator"] = @"Prefeitura Municipal de Maricá", [@"operator:wikidata"] = @"Q847037", },
            Terms: [@"prefeitura municipal de maricá", @"prefeitura municipal de maricá/defesa civil"]),
        new NsiItem(
            DisplayName: @"Internorte (Rio de Janeiro)",
            Id: @"internorte-15440d",
            Tags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"network:wikidata"] = @"Q18480910", [@"public_transport"] = @"platform", },
            AddTags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"highway"] = @"bus_stop", [@"network"] = @"Internorte", [@"network:wikidata"] = @"Q18480910", [@"public_transport"] = @"platform", },
            Terms: [@"Internorte (Rio de Janeiro)", @"internorte"]),
        new NsiItem(
            DisplayName: @"Internorte (Rio de Janeiro)",
            Id: @"internorte-6c36d5",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q18480910", [@"route"] = @"bus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Internorte", [@"network:wikidata"] = @"Q18480910", [@"route"] = @"bus", [@"type"] = @"route", },
            Terms: [@"Internorte (Rio de Janeiro)", @"internorte"]),
    ];
}
