// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'ph-zas.geojson'.</summary>
public static class NsiRegion_PH_ZAS_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"Aurora East District",
            Id: @"auroraeastdistrict-c1a2b6",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490565", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Aurora East District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490565", },
            Terms: [@"aurora east district", @"aurora east district of zamboanga del sur schools division, deped"]),
        new NsiItem(
            DisplayName: @"Aurora West District",
            Id: @"aurorawestdistrict-c1a2b6",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490566", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Aurora West District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490566", },
            Terms: [@"aurora west district", @"aurora west district of zamboanga del sur schools division, deped"]),
        new NsiItem(
            DisplayName: @"Bayog District",
            Id: @"bayogdistrict-c1a2b6",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490567", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Bayog District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490567", },
            Terms: [@"bayog district", @"bayog district of zamboanga del sur schools division, deped"]),
        new NsiItem(
            DisplayName: @"Dimataling District",
            Id: @"dimatalingdistrict-c1a2b6",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490568", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Dimataling District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490568", },
            Terms: [@"dimataling district", @"dimataling district of zamboanga del sur schools division, deped"]),
        new NsiItem(
            DisplayName: @"Dinas District",
            Id: @"dinasdistrict-c1a2b6",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490569", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Dinas District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490569", },
            Terms: [@"dinas district", @"dinas district of zamboanga del sur schools division, deped"]),
        new NsiItem(
            DisplayName: @"Dumalinao District",
            Id: @"dumalinaodistrict-c1a2b6",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490570", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Dumalinao District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490570", },
            Terms: [@"dumalinao district", @"dumalinao district of zamboanga del sur schools division, deped"]),
        new NsiItem(
            DisplayName: @"Dumingag I District",
            Id: @"dumingagidistrict-c1a2b6",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490571", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Dumingag I District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490571", },
            Terms: [@"dumingag i district", @"dumingag i district of zamboanga del sur schools division, deped"]),
        new NsiItem(
            DisplayName: @"Dumingag II District",
            Id: @"dumingagiidistrict-c1a2b6",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490572", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Dumingag II District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490572", },
            Terms: [@"dumingag ii district", @"dumingag ii district of zamboanga del sur schools division, deped"]),
        new NsiItem(
            DisplayName: @"East District (Pagadian City)",
            Id: @"eastdistrict-c1a2b6",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130491275", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"East District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130491275", },
            Terms: [@"East District (Pagadian City)", @"east district", @"east district pagadian city schools division, deped"]),
        new NsiItem(
            DisplayName: @"Guipos District",
            Id: @"guiposdistrict-c1a2b6",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490573", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Guipos District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490573", },
            Terms: [@"guipos district", @"guipos district of zamboanga del sur schools division, deped"]),
        new NsiItem(
            DisplayName: @"Josefina District",
            Id: @"josefinadistrict-c1a2b6",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490574", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Josefina District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490574", },
            Terms: [@"josefina district", @"josefina district of zamboanga del sur schools division, deped"]),
        new NsiItem(
            DisplayName: @"Kumalarang District",
            Id: @"kumalarangdistrict-c1a2b6",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490575", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Kumalarang District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490575", },
            Terms: [@"kumalarang district", @"kumalarang district of zamboanga del sur schools division, deped"]),
        new NsiItem(
            DisplayName: @"Labangan I District",
            Id: @"labanganidistrict-c1a2b6",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490576", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Labangan I District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490576", },
            Terms: [@"labangan i district", @"labangan i district of zamboanga del sur schools division, deped"]),
        new NsiItem(
            DisplayName: @"Labangan II District",
            Id: @"labanganiidistrict-c1a2b6",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490577", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Labangan II District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490577", },
            Terms: [@"labangan ii district", @"labangan ii district of zamboanga del sur schools division, deped"]),
        new NsiItem(
            DisplayName: @"Lakewood District",
            Id: @"lakewooddistrict-c1a2b6",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490578", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Lakewood District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490578", },
            Terms: [@"lakewood district", @"lakewood district of zamboanga del sur schools division, deped"]),
        new NsiItem(
            DisplayName: @"Lapuyan District",
            Id: @"lapuyandistrict-c1a2b6",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490579", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Lapuyan District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490579", },
            Terms: [@"lapuyan district", @"lapuyan district of zamboanga del sur schools division, deped"]),
        new NsiItem(
            DisplayName: @"Mahayag North District",
            Id: @"mahayagnorthdistrict-c1a2b6",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490580", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Mahayag North District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490580", },
            Terms: [@"mahayag north district", @"mahayag north district of zamboanga del sur schools division, deped"]),
        new NsiItem(
            DisplayName: @"Mahayag South District",
            Id: @"mahayagsouthdistrict-c1a2b6",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490581", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Mahayag South District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490581", },
            Terms: [@"mahayag south district", @"mahayag south district of zamboanga del sur schools division, deped"]),
        new NsiItem(
            DisplayName: @"Margosatubig District",
            Id: @"margosatubigdistrict-c1a2b6",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490582", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Margosatubig District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490582", },
            Terms: [@"margosatubig district", @"margosatubig district of zamboanga del sur schools division, deped"]),
        new NsiItem(
            DisplayName: @"Midsalip District",
            Id: @"midsalipdistrict-c1a2b6",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490583", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Midsalip District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490583", },
            Terms: [@"midsalip district", @"midsalip district of zamboanga del sur schools division, deped"]),
        new NsiItem(
            DisplayName: @"Molave East District",
            Id: @"molaveeastdistrict-c1a2b6",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490584", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Molave East District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490584", },
            Terms: [@"molave east district", @"molave east district of zamboanga del sur schools division, deped"]),
        new NsiItem(
            DisplayName: @"Molave West District",
            Id: @"molavewestdistrict-c1a2b6",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490585", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Molave West District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490585", },
            Terms: [@"molave west district", @"molave west district of zamboanga del sur schools division, deped"]),
        new NsiItem(
            DisplayName: @"Pitogo District (Zamboanga del Sur)",
            Id: @"pitogodistrict-c1a2b6",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490586", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Pitogo District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490586", },
            Terms: [@"Pitogo District (Zamboanga del Sur)", @"pitogo district", @"pitogo district of zamboanga del sur schools division, deped"]),
        new NsiItem(
            DisplayName: @"Ramon Magsaysay District",
            Id: @"ramonmagsaysaydistrict-c1a2b6",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130491428", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Ramon Magsaysay District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130491428", },
            Terms: [@"ramon magsaysay district", @"ramon magsaysay district of zamboanga del sur schools division, deped"]),
        new NsiItem(
            DisplayName: @"San Miguel District (Zamboanga del Sur)",
            Id: @"sanmigueldistrict-c1a2b6",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490587", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"San Miguel District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490587", },
            Terms: [@"San Miguel District (Zamboanga del Sur)", @"san miguel district", @"san miguel district of zamboanga del sur schools division, deped"]),
        new NsiItem(
            DisplayName: @"San Pablo District (Zamboanga del Sur)",
            Id: @"sanpablodistrict-c1a2b6",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490588", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"San Pablo District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490588", },
            Terms: [@"San Pablo District (Zamboanga del Sur)", @"san pablo district", @"san pablo district of zamboanga del sur schools division, deped"]),
        new NsiItem(
            DisplayName: @"Sominot District",
            Id: @"sominotdistrict-c1a2b6",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490589", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Sominot District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490589", },
            Terms: [@"sominot district", @"sominot district of zamboanga del sur schools division, deped"]),
        new NsiItem(
            DisplayName: @"South District (Pagadian City)",
            Id: @"southdistrict-c1a2b6",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130491276", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"South District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130491276", },
            Terms: [@"South District (Pagadian City)", @"south district", @"south district pagadian city schools division, deped"]),
        new NsiItem(
            DisplayName: @"Tabina District",
            Id: @"tabinadistrict-c1a2b6",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490590", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Tabina District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490590", },
            Terms: [@"tabina district", @"tabina district of zamboanga del sur schools division, deped"]),
        new NsiItem(
            DisplayName: @"Tambulig District",
            Id: @"tambuligdistrict-c1a2b6",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490591", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Tambulig District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490591", },
            Terms: [@"tambulig district", @"tambulig district of zamboanga del sur schools division, deped"]),
        new NsiItem(
            DisplayName: @"Tigbao District",
            Id: @"tigbaodistrict-c1a2b6",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490592", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Tigbao District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490592", },
            Terms: [@"tigbao district", @"tigbao district of zamboanga del sur schools division, deped"]),
        new NsiItem(
            DisplayName: @"Tukuran East District",
            Id: @"tukuraneastdistrict-c1a2b6",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490593", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Tukuran East District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490593", },
            Terms: [@"tukuran east district", @"tukuran east district of zamboanga del sur schools division, deped"]),
        new NsiItem(
            DisplayName: @"Tukuran West District",
            Id: @"tukuranwestdistrict-c1a2b6",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490594", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Tukuran West District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490594", },
            Terms: [@"tukuran west district", @"tukuran west district of zamboanga del sur schools division, deped"]),
        new NsiItem(
            DisplayName: @"Vincenzo Sagun District",
            Id: @"vincenzosagundistrict-c1a2b6",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490595", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Vincenzo Sagun District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490595", },
            Terms: [@"vincenzo sagun district", @"vincenzo sagun district of zamboanga del sur schools division, deped"]),
    ];
}
