// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'gb-bst.geojson'.</summary>
public static class NsiRegion_GB_BST_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"Bristol City Council",
            Id: @"bristolcitycouncil-8b0fb3",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"library", [@"operator:wikidata"] = @"Q16953796", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"library", [@"operator"] = @"Bristol City Council", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q16953796", },
            Terms: [@"bristol city council"]),
        new NsiItem(
            DisplayName: @"Bristol City Council",
            Id: @"bristolcitycouncil-c2a4f5",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q16953796", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Bristol City Council", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q16953796", },
            Terms: [@"bristol city council"]),
        new NsiItem(
            DisplayName: @"Bristol City Council",
            Id: @"bristolcitycouncil-5915cd",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator:wikidata"] = @"Q16953796", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator"] = @"Bristol City Council", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q16953796", },
            Terms: [@"bristol city council"]),
        new NsiItem(
            DisplayName: @"Bristol City Council",
            Id: @"bristolcitycouncil-2e053b",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator:wikidata"] = @"Q16953796", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator"] = @"Bristol City Council", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q16953796", },
            Terms: [@"bristol city council"]),
        new NsiItem(
            DisplayName: @"Bristol City Council",
            Id: @"bristolcitycouncil-4175ff",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"surveillance", [@"operator:wikidata"] = @"Q16953796", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"surveillance", [@"operator"] = @"Bristol City Council", [@"operator:wikidata"] = @"Q16953796", },
            Terms: [@"bristol city council"]),
    ];
}
