// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'at-5.geojson'.</summary>
public static class NsiRegion_AT_5_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"Salzburg AG",
            Id: @"salzburgag-2afdb6",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"charging_station", [@"operator:wikidata"] = @"Q2215905", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"charging_station", [@"operator"] = @"Salzburg AG", [@"operator:wikidata"] = @"Q2215905", },
            Terms: [@"salzburg ag"]),
        new NsiItem(
            DisplayName: @"Österreichisches Rotes Kreuz, Landesverband Salzburg",
            Id: @"osterreichischesroteskreuzlandesverbandsalzburg-ae68c2",
            Tags: new Dictionary<string, string> { [@"emergency"] = @"ambulance_station", [@"operator:wikidata"] = @"Q105577291", },
            AddTags: new Dictionary<string, string> { [@"emergency"] = @"ambulance_station", [@"operator"] = @"Österreichisches Rotes Kreuz, Landesverband Salzburg", [@"operator:wikidata"] = @"Q105577291", },
            Terms: [@"österreichisches rotes kreuz, landesverband salzburg"]),
        new NsiItem(
            DisplayName: @"Salzburg AG",
            Id: @"salzburgag-28a506",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"charge_point", [@"operator:wikidata"] = @"Q2215905", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"charge_point", [@"operator"] = @"Salzburg AG", [@"operator:wikidata"] = @"Q2215905", },
            Terms: [@"salzburg ag"]),
        new NsiItem(
            DisplayName: @"Transalpine Ölleitung in Österreich Ges.m.b.H",
            Id: @"transalpineolleitunginosterreichgesmbh-c00783",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"pipeline", [@"operator:wikidata"] = @"Q118611102", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"pipeline", [@"operator"] = @"Transalpine Ölleitung in Österreich Ges.m.b.H", [@"operator:wikidata"] = @"Q118611102", },
            Terms: [@"transalpine ölleitung in österreich ges.m.b.h"]),
        new NsiItem(
            DisplayName: @"Salzburg AG",
            Id: @"salzburgag-4f5b5f",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"street_cabinet", [@"operator:wikidata"] = @"Q2215905", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"street_cabinet", [@"operator"] = @"Salzburg AG", [@"operator:wikidata"] = @"Q2215905", },
            Terms: [@"salzburg ag"]),
        new NsiItem(
            DisplayName: @"Salzburg Netz",
            Id: @"salzburgnetz-ae6f64",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"street_cabinet", [@"operator:wikidata"] = @"Q108283678", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"street_cabinet", [@"operator"] = @"Salzburg Netz", [@"operator:wikidata"] = @"Q108283678", },
            Terms: [@"salzburg netz"]),
        new NsiItem(
            DisplayName: @"Transalpine Ölleitung in Österreich Ges.m.b.H",
            Id: @"transalpineolleitunginosterreichgesmbh-926872",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q118611102", [@"pipeline"] = @"substation", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Transalpine Ölleitung in Österreich Ges.m.b.H", [@"operator:wikidata"] = @"Q118611102", [@"pipeline"] = @"substation", },
            Terms: [@"transalpine ölleitung in österreich ges.m.b.h"]),
        new NsiItem(
            DisplayName: @"Salzburg AG",
            Id: @"salzburgag-295d00",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q2215905", [@"power"] = @"generator", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Salzburg AG", [@"operator:wikidata"] = @"Q2215905", [@"power"] = @"generator", },
            Terms: [@"salzburg ag"]),
        new NsiItem(
            DisplayName: @"Salzburg AG",
            Id: @"salzburgag-38d9ce",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q2215905", [@"power"] = @"line", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Salzburg AG", [@"operator:wikidata"] = @"Q2215905", [@"power"] = @"line", },
            Terms: [@"salzburg ag", @"salzburg netz"]),
        new NsiItem(
            DisplayName: @"Salzburg AG",
            Id: @"salzburgag-bd38fa",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q2215905", [@"power"] = @"minor_line", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Salzburg AG", [@"operator:wikidata"] = @"Q2215905", [@"power"] = @"minor_line", },
            Terms: [@"salzburg ag", @"salzburg netz"]),
        new NsiItem(
            DisplayName: @"Salzburg AG",
            Id: @"salzburgag-da17ce",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q2215905", [@"power"] = @"plant", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Salzburg AG", [@"operator:wikidata"] = @"Q2215905", [@"power"] = @"plant", },
            Terms: [@"salzburg ag"]),
        new NsiItem(
            DisplayName: @"Salzburg AG",
            Id: @"salzburgag-3061ab",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q2215905", [@"power"] = @"pole", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Salzburg AG", [@"operator:wikidata"] = @"Q2215905", [@"power"] = @"pole", },
            Terms: [@"salzburg ag", @"salzburg netz"]),
        new NsiItem(
            DisplayName: @"Salzburg AG",
            Id: @"salzburgag-d5d274",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q2215905", [@"power"] = @"substation", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Salzburg AG", [@"operator:wikidata"] = @"Q2215905", [@"power"] = @"substation", },
            Terms: [@"salzburg ag", @"salzburg netz"]),
        new NsiItem(
            DisplayName: @"Salzburg AG",
            Id: @"salzburgag-f0df32",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q2215905", [@"power"] = @"tower", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Salzburg AG", [@"operator:wikidata"] = @"Q2215905", [@"power"] = @"tower", },
            Terms: [@"salzburg ag", @"salzburg netz"]),
        new NsiItem(
            DisplayName: @"Salzburg AG",
            Id: @"salzburgag-6beb1b",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q2215905", [@"power"] = @"transformer", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Salzburg AG", [@"operator:wikidata"] = @"Q2215905", [@"power"] = @"transformer", },
            Terms: [@"salzburg ag", @"salzburg netz"]),
        new NsiItem(
            DisplayName: @"Oberösterreichischer Verkehrsverbund",
            Id: @"oberosterreichischerverkehrsverbund-a33556",
            Tags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"network:wikidata"] = @"Q2011605", [@"public_transport"] = @"platform", },
            AddTags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"highway"] = @"bus_stop", [@"network"] = @"Oberösterreichischer Verkehrsverbund", [@"network:short"] = @"OÖVV", [@"network:wikidata"] = @"Q2011605", [@"public_transport"] = @"platform", },
            Terms: [@"oberösterreichischer verkehrsverbund", @"oövv"]),
        new NsiItem(
            DisplayName: @"Regionalverkehr Oberbayern",
            Id: @"regionalverkehroberbayern-1eac73",
            Tags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"network:wikidata"] = @"Q2138493", [@"public_transport"] = @"platform", },
            AddTags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"highway"] = @"bus_stop", [@"network"] = @"Regionalverkehr Oberbayern", [@"network:wikidata"] = @"Q2138493", [@"public_transport"] = @"platform", },
            Terms: [@"regionalverkehr oberbayern"]),
        new NsiItem(
            DisplayName: @"Verkehrsverbund Tirol",
            Id: @"verkehrsverbundtirol-7b8655",
            Tags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"network:wikidata"] = @"Q1668732", [@"public_transport"] = @"platform", },
            AddTags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"highway"] = @"bus_stop", [@"network"] = @"Verkehrsverbund Tirol", [@"network:short"] = @"VVT", [@"network:wikidata"] = @"Q1668732", [@"public_transport"] = @"platform", },
            Terms: [@"ivb", @"verkehrsverbund tirol", @"vvt"]),
        new NsiItem(
            DisplayName: @"Verkehrsverbund Tirol",
            Id: @"verkehrsverbundtirol-708c11",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q1668732", [@"railway"] = @"station", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Verkehrsverbund Tirol", [@"network:short"] = @"VVT", [@"network:wikidata"] = @"Q1668732", [@"public_transport"] = @"station", [@"railway"] = @"station", [@"train"] = @"yes", },
            Terms: [@"verkehrsverbund tirol", @"vvt"]),
        new NsiItem(
            DisplayName: @"Oberösterreichischer Verkehrsverbund",
            Id: @"oberosterreichischerverkehrsverbund-7c0334",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q2011605", [@"route"] = @"bus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Oberösterreichischer Verkehrsverbund", [@"network:short"] = @"OÖVV", [@"network:wikidata"] = @"Q2011605", [@"route"] = @"bus", [@"type"] = @"route", },
            Terms: [@"oberösterreichischer verkehrsverbund", @"oövv"]),
        new NsiItem(
            DisplayName: @"Regionalverkehr Oberbayern",
            Id: @"regionalverkehroberbayern-5d6e8d",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q2138493", [@"route"] = @"bus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Regionalverkehr Oberbayern", [@"network:wikidata"] = @"Q2138493", [@"route"] = @"bus", [@"type"] = @"route", },
            Terms: [@"regionalverkehr oberbayern"]),
        new NsiItem(
            DisplayName: @"Verkehrsverbund Tirol",
            Id: @"verkehrsverbundtirol-3c7a9e",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q1668732", [@"route"] = @"bus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Verkehrsverbund Tirol", [@"network:short"] = @"VVT", [@"network:wikidata"] = @"Q1668732", [@"route"] = @"bus", [@"type"] = @"route", },
            Terms: [@"ivb", @"verkehrsverbund tirol", @"vvt"]),
        new NsiItem(
            DisplayName: @"Verkehrsverbund Tirol",
            Id: @"verkehrsverbundtirol-8ca58a",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q1668732", [@"route"] = @"train", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Verkehrsverbund Tirol", [@"network:short"] = @"VVT", [@"network:wikidata"] = @"Q1668732", [@"route"] = @"train", [@"type"] = @"route", },
            Terms: [@"verkehrsverbund tirol", @"vvt"]),
        new NsiItem(
            DisplayName: @"Salzburger Verkehrsverbund",
            Id: @"salzburgerverkehrsverbund-86785f",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q1254319", [@"route"] = @"trolleybus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Salzburger Verkehrsverbund", [@"network:short"] = @"SVV", [@"network:wikidata"] = @"Q1254319", [@"operator"] = @"Salzburg AG", [@"operator:wikidata"] = @"Q2215905", [@"route"] = @"trolleybus", [@"type"] = @"route", },
            Terms: [@"salzburg ag", @"salzburger verkehrsverbund", @"svv"]),
    ];
}
