// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'ph-pam.geojson'.</summary>
public static class NsiRegion_PH_PAM_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"Apalit District",
            Id: @"apalitdistrict-b17b76",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490382", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Apalit District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490382", },
            Terms: [@"apalit district", @"apalit district of pampanga schools division, deped"]),
        new NsiItem(
            DisplayName: @"Arayat East District",
            Id: @"arayateastdistrict-b17b76",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490383", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Arayat East District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490383", },
            Terms: [@"arayat east district", @"arayat east district of pampanga schools division, deped"]),
        new NsiItem(
            DisplayName: @"Arayat West District",
            Id: @"arayatwestdistrict-b17b76",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490384", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Arayat West District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490384", },
            Terms: [@"arayat west district", @"arayat west district of pampanga schools division, deped"]),
        new NsiItem(
            DisplayName: @"Bacolor District",
            Id: @"bacolordistrict-b17b76",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490385", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Bacolor District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490385", },
            Terms: [@"bacolor district", @"bacolor district of pampanga schools division, deped"]),
        new NsiItem(
            DisplayName: @"Candaba East District",
            Id: @"candabaeastdistrict-b17b76",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490386", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Candaba East District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490386", },
            Terms: [@"candaba east district", @"candaba east district of pampanga schools division, deped"]),
        new NsiItem(
            DisplayName: @"Candaba West District",
            Id: @"candabawestdistrict-b17b76",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490387", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Candaba West District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490387", },
            Terms: [@"candaba west district", @"candaba west district of pampanga schools division, deped"]),
        new NsiItem(
            DisplayName: @"Floridablanca East District",
            Id: @"floridablancaeastdistrict-b17b76",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490388", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Floridablanca East District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490388", },
            Terms: [@"floridablanca east district", @"floridablanca east district, pampanga school division, department of education"]),
        new NsiItem(
            DisplayName: @"Floridablanca West District",
            Id: @"floridablancawestdistrict-b17b76",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490389", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Floridablanca West District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490389", },
            Terms: [@"floridablanca west district", @"floridablanca west district, pampanga school division, department of education"]),
        new NsiItem(
            DisplayName: @"Guagua West District",
            Id: @"guaguawestdistrict-b17b76",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490390", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Guagua West District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490390", },
            Terms: [@"guagua west district", @"guagua west district, pampanga school division, department of education"]),
        new NsiItem(
            DisplayName: @"Lubao East District",
            Id: @"lubaoeastdistrict-b17b76",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490391", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Lubao East District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490391", },
            Terms: [@"lubao east district", @"lubao east district, pampanga school division, department of education"]),
        new NsiItem(
            DisplayName: @"Lubao West District",
            Id: @"lubaowestdistrict-b17b76",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490392", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Lubao West District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490392", },
            Terms: [@"lubao west district", @"lubao west district, pampanga school division, department of education"]),
        new NsiItem(
            DisplayName: @"Macabebe East District",
            Id: @"macabebeeastdistrict-b17b76",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490393", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Macabebe East District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490393", },
            Terms: [@"macabebe east district", @"macabebe east district of pampanga schools division, deped"]),
        new NsiItem(
            DisplayName: @"Macabebe West District",
            Id: @"macabebewestdistrict-b17b76",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490394", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Macabebe West District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490394", },
            Terms: [@"macabebe west district", @"macabebe west district of pampanga schools division, deped"]),
        new NsiItem(
            DisplayName: @"Magalang North District",
            Id: @"magalangnorthdistrict-b17b76",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490395", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Magalang North District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490395", },
            Terms: [@"magalang north district", @"magalang north district, pampanga school division, department of education"]),
        new NsiItem(
            DisplayName: @"Masantol District",
            Id: @"masantoldistrict-b17b76",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490396", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Masantol District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490396", },
            Terms: [@"masantol district", @"masantol district of pampanga schools division, deped"]),
        new NsiItem(
            DisplayName: @"Mexico North District",
            Id: @"mexiconorthdistrict-b17b76",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490397", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Mexico North District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490397", },
            Terms: [@"mexico north district", @"mexico north district of pampanga schools division, deped"]),
        new NsiItem(
            DisplayName: @"Mexico South District",
            Id: @"mexicosouthdistrict-b17b76",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490398", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Mexico South District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490398", },
            Terms: [@"mexico south district", @"mexico south district of pampanga schools division, deped"]),
        new NsiItem(
            DisplayName: @"Minalin District",
            Id: @"minalindistrict-b17b76",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490399", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Minalin District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490399", },
            Terms: [@"minalin district", @"minalin district of pampanga schools division, deped"]),
        new NsiItem(
            DisplayName: @"Porac West District",
            Id: @"poracwestdistrict-b17b76",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490400", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Porac West District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490400", },
            Terms: [@"porac west district", @"porac west district, pampanga school division, department of education"]),
        new NsiItem(
            DisplayName: @"San Luis District (Pampanga)",
            Id: @"sanluisdistrict-b17b76",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490401", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"San Luis District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490401", },
            Terms: [@"San Luis District (Pampanga)", @"san luis district", @"san luis district of pampanga schools division, deped"]),
        new NsiItem(
            DisplayName: @"San Simon District",
            Id: @"sansimondistrict-b17b76",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490402", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"San Simon District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490402", },
            Terms: [@"san simon district", @"san simon district of pampanga schools division, deped"]),
        new NsiItem(
            DisplayName: @"Santa Ana District (Pampanga)",
            Id: @"santaanadistrict-b17b76",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130490403", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Santa Ana District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130490403", },
            Terms: [@"Santa Ana District (Pampanga)", @"santa ana district", @"sta. ana district of pampanga schools division, deped"]),
        new NsiItem(
            DisplayName: @"Converge ICT Solutions",
            Id: @"convergeictsolutions-2005fe",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"street_cabinet", [@"operator:wikidata"] = @"Q39058397", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"street_cabinet", [@"operator"] = @"Converge ICT Solutions", [@"operator:wikidata"] = @"Q39058397", },
            Terms: [@"converge ict solutions", @"converge ict solutions inc."]),
    ];
}
