// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'mv'.</summary>
public static class NsiRegion_MV
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"Bank of Maldives",
            Id: @"bankofmaldives-413aed",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand:wikidata"] = @"Q4856148", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand"] = @"Bank of Maldives", [@"brand:en"] = @"Bank of Maldives", [@"brand:wikidata"] = @"Q4856148", [@"operator"] = @"Bank of Maldives", [@"operator:wikidata"] = @"Q4856148", },
            Terms: [@"bank of maldives"]),
        new NsiItem(
            DisplayName: @"Bank of Maldives",
            Id: @"bankofmaldives-ec25c3",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand:wikidata"] = @"Q4856148", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand"] = @"Bank of Maldives", [@"brand:en"] = @"Bank of Maldives", [@"brand:wikidata"] = @"Q4856148", [@"name"] = @"Bank of Maldives", [@"name:en"] = @"Bank of Maldives", },
            Terms: [@"bank of maldives"]),
        new NsiItem(
            DisplayName: @"Barista",
            Id: @"barista-56abeb",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"cafe", [@"brand:wikidata"] = @"Q644735", [@"cuisine"] = @"coffee_shop", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"cafe", [@"brand"] = @"Barista", [@"brand:wikidata"] = @"Q644735", [@"cuisine"] = @"coffee_shop", [@"name"] = @"Barista", [@"takeaway"] = @"yes", },
            Terms: [@"barista"]),
        new NsiItem(
            DisplayName: @"Secret Recipe",
            Id: @"secretrecipe-541408",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"fast_food", [@"brand:wikidata"] = @"Q7444079", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"fast_food", [@"brand"] = @"Secret Recipe", [@"brand:wikidata"] = @"Q7444079", [@"cuisine"] = @"cake;malaysian", [@"name"] = @"Secret Recipe", [@"takeaway"] = @"yes", },
            Terms: [@"secret recipe"]),
        new NsiItem(
            DisplayName: @"Ooredoo",
            Id: @"ooredoo-5cc5ab",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q919935", [@"shop"] = @"telecommunication", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"Ooredoo", [@"brand:wikidata"] = @"Q919935", [@"name"] = @"Ooredoo", [@"shop"] = @"telecommunication", },
            Terms: [@"ooredoo"]),
        new NsiItem(
            DisplayName: @"Anantara",
            Id: @"anantara-e8534c",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q112671781", [@"tourism"] = @"hotel", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"Anantara", [@"brand:wikidata"] = @"Q112671781", [@"name"] = @"Anantara", [@"tourism"] = @"hotel", },
            Terms: [@"anantara"]),
        new NsiItem(
            DisplayName: @"Barceló",
            Id: @"barcelohotelsandresorts-302c40",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q15148996", [@"tourism"] = @"hotel", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"Barceló Hotels & Resorts", [@"brand:wikidata"] = @"Q15148996", [@"name"] = @"Barceló Hotels & Resorts", [@"tourism"] = @"hotel", },
            Terms: [@"Barceló", @"barceló hotels & resorts"]),
        new NsiItem(
            DisplayName: @"Conrad Hotels & Resorts",
            Id: @"conrad-ee1a43",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q855525", [@"tourism"] = @"hotel", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"Conrad", [@"brand:wikidata"] = @"Q855525", [@"name"] = @"Conrad", [@"tourism"] = @"hotel", },
            Terms: [@"Conrad Hotels & Resorts", @"conrad"]),
        new NsiItem(
            DisplayName: @"Outrigger Hotels and Resorts",
            Id: @"outriggerhotelsandresorts-dd4bde",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q7112915", [@"tourism"] = @"hotel", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"Outrigger Hotels and Resorts", [@"brand:wikidata"] = @"Q7112915", [@"name"] = @"Outrigger Hotels and Resorts", [@"tourism"] = @"hotel", },
            Terms: [@"outrigger hotels and resorts"]),
        new NsiItem(
            DisplayName: @"Raffles",
            Id: @"raffles-771760",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q4306661", [@"tourism"] = @"hotel", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"Raffles", [@"brand:wikidata"] = @"Q4306661", [@"name"] = @"Raffles", [@"tourism"] = @"hotel", },
            Terms: [@"raffles"]),
        new NsiItem(
            DisplayName: @"Waldorf Astoria",
            Id: @"waldorfastoria-665f74",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q3239392", [@"tourism"] = @"hotel", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"Waldorf Astoria", [@"brand:wikidata"] = @"Q3239392", [@"name"] = @"Waldorf Astoria", [@"tourism"] = @"hotel", },
            Terms: [@"waldorf astoria", @"waldorf astoria hotels & resorts"]),
        new NsiItem(
            DisplayName: @"Fenaka Vaikaradhoo Branch",
            Id: @"fenakavaikaradhoobranch-ebce48",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"pipeline", [@"operator:wikidata"] = @"Q130384689", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"pipeline", [@"operator"] = @"Fenaka Vaikaradhoo Branch", [@"operator:wikidata"] = @"Q130384689", },
            Terms: [@"fenaka corporation limited vaikaradhoo", @"fenaka vaikaradhoo branch"]),
        new NsiItem(
            DisplayName: @"Fenaka Vaikaradhoo Branch",
            Id: @"fenakavaikaradhoobranch-0b97e8",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q130384689", [@"pipeline"] = @"substation", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Fenaka Vaikaradhoo Branch", [@"operator:wikidata"] = @"Q130384689", [@"pipeline"] = @"substation", },
            Terms: [@"fenaka corporation limited vaikaradhoo", @"fenaka vaikaradhoo branch"]),
        new NsiItem(
            DisplayName: @"Fenaka",
            Id: @"fenaka-1b2052",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q130384689", [@"power"] = @"generator", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Fenaka", [@"operator:wikidata"] = @"Q130384689", [@"power"] = @"generator", },
            Terms: [@"fenaka"]),
        new NsiItem(
            DisplayName: @"Fenaka",
            Id: @"fenaka-a15a28",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q130384689", [@"power"] = @"plant", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Fenaka", [@"operator:wikidata"] = @"Q130384689", [@"power"] = @"plant", },
            Terms: [@"fenaka"]),
        new NsiItem(
            DisplayName: @"Fenaka Vaikaradhoo Branch",
            Id: @"fenakavaikaradhoobranch-50d5ac",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q130384689", [@"power"] = @"substation", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Fenaka Vaikaradhoo Branch", [@"operator:wikidata"] = @"Q130384689", [@"power"] = @"substation", },
            Terms: [@"fenaka corporation limited vaikaradhoo", @"fenaka vaikaradhoo branch"]),
        new NsiItem(
            DisplayName: @"Fenaka Vaikaradhoo Branch",
            Id: @"fenakavaikaradhoobranch-7ccaed",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q130384689", [@"power"] = @"transformer", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Fenaka Vaikaradhoo Branch", [@"operator:wikidata"] = @"Q130384689", [@"power"] = @"transformer", },
            Terms: [@"fenaka corporation limited vaikaradhoo", @"fenaka vaikaradhoo branch"]),
        new NsiItem(
            DisplayName: @"RTL",
            Id: @"rtl-d54873",
            Tags: new Dictionary<string, string> { [@"ferry"] = @"yes", [@"network:wikidata"] = @"Q138509118", [@"public_transport"] = @"station", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"ferry_terminal", [@"ferry"] = @"yes", [@"network"] = @"RTL", [@"network:wikidata"] = @"Q138509118", [@"operator"] = @"MTCC", [@"operator:wikidata"] = @"Q138509111", [@"public_transport"] = @"station", },
            Terms: [@"mtcc", @"rtl"]),
        new NsiItem(
            DisplayName: @"RTL (Maldives)",
            Id: @"rtl-3bfe6b",
            Tags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"network:wikidata"] = @"Q138509118", [@"public_transport"] = @"platform", },
            AddTags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"highway"] = @"bus_stop", [@"network"] = @"RTL", [@"network:wikidata"] = @"Q138509118", [@"operator"] = @"MTCC", [@"operator:wikidata"] = @"Q138509111", [@"public_transport"] = @"platform", },
            Terms: [@"RTL (Maldives)", @"mtcc", @"rtl"]),
        new NsiItem(
            DisplayName: @"RTL (Maldives)",
            Id: @"rtl-80c041",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q138509118", [@"route"] = @"bus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"RTL", [@"network:wikidata"] = @"Q138509118", [@"operator"] = @"MTCC", [@"operator:wikidata"] = @"Q138509111", [@"route"] = @"bus", [@"type"] = @"route", },
            Terms: [@"RTL (Maldives)", @"mtcc", @"rtl"]),
        new NsiItem(
            DisplayName: @"RTL",
            Id: @"rtl-982c29",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q138509118", [@"route"] = @"ferry", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"RTL", [@"network:wikidata"] = @"Q138509118", [@"operator"] = @"MTCC", [@"operator:wikidata"] = @"Q138509111", [@"route"] = @"ferry", [@"type"] = @"route", },
            Terms: [@"mtcc", @"rtl"]),
        new NsiItem(
            DisplayName: @"RTL",
            Id: @"rtl-982c29",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q138509118", [@"route"] = @"ferry", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"RTL", [@"network:wikidata"] = @"Q138509118", [@"operator"] = @"MTCC", [@"operator:wikidata"] = @"Q138509111", [@"route"] = @"ferry", },
            Terms: [@"mtcc", @"rtl"]),
    ];
}
