// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'es-ab.geojson'.</summary>
public static class NsiRegion_ES_AB_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"AlbaBici",
            Id: @"albabici-23cd33",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bicycle_rental", [@"brand:wikidata"] = @"Q17620480", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bicycle_rental", [@"brand"] = @"AlbaBici", [@"brand:wikidata"] = @"Q17620480", [@"network"] = @"AlbaBici", [@"network:wikidata"] = @"Q17620480", [@"operator"] = @"Labici", [@"operator:type"] = @"private", },
            Terms: [@"albabici", @"labici"]),
        new NsiItem(
            DisplayName: @"Servicio de Salud de Castilla-La Mancha",
            Id: @"serviciodesaluddecastillalamancha-37c413",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"clinic", [@"operator:wikidata"] = @"Q5665691", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"clinic", [@"healthcare"] = @"clinic", [@"operator"] = @"Servicio de Salud de Castilla-La Mancha", [@"operator:short"] = @"SESCAM", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q5665691", },
            Terms: [@"servicio de salud de castilla-la mancha", @"sescam"]),
        new NsiItem(
            DisplayName: @"Ayuntamiento de Albacete",
            Id: @"ayuntamientodealbacete-da0e49",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"recycling", [@"operator:wikidata"] = @"Q5714788", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"recycling", [@"operator"] = @"Ayuntamiento de Albacete", [@"operator:wikidata"] = @"Q5714788", },
            Terms: [@"ayuntamiento de albacete"]),
        new NsiItem(
            DisplayName: @"Confederación Hidrográfica del Júcar",
            Id: @"confederacionhidrograficadeljucar-46ce5c",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"pipeline", [@"operator:wikidata"] = @"Q8349721", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"pipeline", [@"operator"] = @"Confederación Hidrográfica del Júcar", [@"operator:wikidata"] = @"Q8349721", },
            Terms: [@"confederación hidrográfica del júcar"]),
        new NsiItem(
            DisplayName: @"Mancomunidad de los Canales del Taibilla",
            Id: @"mancomunidaddeloscanalesdeltaibilla-2a9cbf",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"pipeline", [@"operator:wikidata"] = @"Q71304122", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"pipeline", [@"operator"] = @"Mancomunidad de los Canales del Taibilla", [@"operator:wikidata"] = @"Q71304122", },
            Terms: [@"mancomunidad de los canales del taibilla"]),
        new NsiItem(
            DisplayName: @"Confederación Hidrográfica del Júcar",
            Id: @"confederacionhidrograficadeljucar-6c59b5",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q8349721", [@"pipeline"] = @"substation", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Confederación Hidrográfica del Júcar", [@"operator:wikidata"] = @"Q8349721", [@"pipeline"] = @"substation", },
            Terms: [@"confederación hidrográfica del júcar"]),
        new NsiItem(
            DisplayName: @"Mancomunidad de los Canales del Taibilla",
            Id: @"mancomunidaddeloscanalesdeltaibilla-59a03a",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q71304122", [@"pipeline"] = @"substation", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Mancomunidad de los Canales del Taibilla", [@"operator:wikidata"] = @"Q71304122", [@"pipeline"] = @"substation", },
            Terms: [@"mancomunidad de los canales del taibilla"]),
        new NsiItem(
            DisplayName: @"Transport Públic Generalitat Valenciana",
            Id: @"transportpublicgeneralitatvalenciana-8b71a7",
            Tags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"network:wikidata"] = @"Q134462067", [@"public_transport"] = @"platform", },
            AddTags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"highway"] = @"bus_stop", [@"network"] = @"Transport Públic Generalitat Valenciana", [@"network:wikidata"] = @"Q134462067", [@"public_transport"] = @"platform", },
            Terms: [@"transport públic generalitat valenciana"]),
        new NsiItem(
            DisplayName: @"Transport Públic Generalitat Valenciana",
            Id: @"transportpublicgeneralitatvalenciana-28bf89",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q134462067", [@"route"] = @"bus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Transport Públic Generalitat Valenciana", [@"network:wikidata"] = @"Q134462067", [@"route"] = @"bus", [@"type"] = @"route", },
            Terms: [@"transport públic generalitat valenciana"]),
    ];
}
