// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'us-ca-san_francisco.geojson'.</summary>
public static class NsiRegion_US_CA_SAN_FRANCISCO_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"Bay Wheels",
            Id: @"baywheels-2a665b",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bicycle_rental", [@"brand:wikidata"] = @"Q16971391", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bicycle_rental", [@"bicycle_rental"] = @"docking_station", [@"brand"] = @"Bay Wheels", [@"brand:wikidata"] = @"Q16971391", [@"fee"] = @"yes", [@"name"] = @"Bay Wheels", [@"network"] = @"Bay Wheels", [@"network:wikidata"] = @"Q16971391", [@"operator"] = @"Lyft", [@"operator:type"] = @"private", [@"operator:wikidata"] = @"Q17077936", },
            Terms: [@"bay area bike share", @"bay wheels", @"ford gobike", @"lyft", @"lyft bike"]),
        new NsiItem(
            DisplayName: @"San Francisco Public Library",
            Id: @"sanfranciscopubliclibrary-92bbc9",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"library", [@"operator:wikidata"] = @"Q2901530", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"library", [@"operator"] = @"San Francisco Public Library", [@"operator:short"] = @"SFPL", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q2901530", },
            Terms: [@"san francisco public library", @"sfpl"]),
        new NsiItem(
            DisplayName: @"San Francisco Recreation & Park Department",
            Id: @"sanfranciscorecreationandparkdepartment-36fb4a",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator:wikidata"] = @"Q14683875", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator"] = @"San Francisco Recreation & Park Department", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q14683875", },
            Terms: [@"san francisco recreation & park department"]),
        new NsiItem(
            DisplayName: @"San Francisco Recreation & Park Department",
            Id: @"sanfranciscorecreationandparkdepartment-7d4eb5",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator:wikidata"] = @"Q14683875", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator"] = @"San Francisco Recreation & Park Department", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q14683875", },
            Terms: [@"san francisco recreation & park department"]),
        new NsiItem(
            DisplayName: @"San Francisco Police Department",
            Id: @"sanfranciscopolicedepartment-3ba7d2",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"surveillance", [@"operator:wikidata"] = @"Q1320247", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"surveillance", [@"operator"] = @"San Francisco Police Department", [@"operator:wikidata"] = @"Q1320247", },
            Terms: [@"san francisco police department"]),
    ];
}
