// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'nz-can.geojson'.</summary>
public static class NsiRegion_NZ_CAN_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"Christchurch City Council",
            Id: @"christchurchcitycouncil-f7c9d2",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"drinking_water", [@"operator:wikidata"] = @"Q5109064", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"drinking_water", [@"operator"] = @"Christchurch City Council", [@"operator:wikidata"] = @"Q5109064", },
            Terms: [@"christchurch city council"]),
        new NsiItem(
            DisplayName: @"University of Canterbury",
            Id: @"universityofcanterbury-dce6cd",
            Tags: new Dictionary<string, string> { [@"emergency"] = @"phone", [@"operator:wikidata"] = @"Q432475", },
            AddTags: new Dictionary<string, string> { [@"emergency"] = @"phone", [@"operator"] = @"University of Canterbury", [@"operator:wikidata"] = @"Q432475", },
            Terms: [@"university of canterbury"]),
        new NsiItem(
            DisplayName: @"Christchurch City Council",
            Id: @"christchurchcitycouncil-ff83c4",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator:wikidata"] = @"Q5109064", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator"] = @"Christchurch City Council", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q5109064", },
            Terms: [@"christchurch city council"]),
        new NsiItem(
            DisplayName: @"Hurunui District Council",
            Id: @"hurunuidistrictcouncil-ff83c4",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator:wikidata"] = @"Q65606410", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator"] = @"Hurunui District Council", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q65606410", },
            Terms: [@"hurunui district council"]),
        new NsiItem(
            DisplayName: @"Timaru District Council",
            Id: @"timarudistrictcouncil-ff83c4",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator:wikidata"] = @"Q65601656", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator"] = @"Timaru District Council", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q65601656", },
            Terms: [@"timaru district council"]),
        new NsiItem(
            DisplayName: @"Waimakariri District Council",
            Id: @"waimakariridistrictcouncil-ff83c4",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator:wikidata"] = @"Q71866858", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator"] = @"Waimakariri District Council", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q71866858", },
            Terms: [@"waimakariri district council"]),
        new NsiItem(
            DisplayName: @"Christchurch City Council",
            Id: @"christchurchcitycouncil-b93ce4",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator:wikidata"] = @"Q5109064", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator"] = @"Christchurch City Council", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q5109064", },
            Terms: [@"christchurch city council"]),
        new NsiItem(
            DisplayName: @"Hurunui District Council",
            Id: @"hurunuidistrictcouncil-b93ce4",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator:wikidata"] = @"Q65606410", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator"] = @"Hurunui District Council", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q65606410", },
            Terms: [@"hurunui district council"]),
        new NsiItem(
            DisplayName: @"Timaru District Council",
            Id: @"timarudistrictcouncil-b93ce4",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator:wikidata"] = @"Q65601656", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator"] = @"Timaru District Council", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q65601656", },
            Terms: [@"timaru district council"]),
        new NsiItem(
            DisplayName: @"Waimakariri District Council",
            Id: @"waimakariridistrictcouncil-b93ce4",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator:wikidata"] = @"Q71866858", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator"] = @"Waimakariri District Council", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q71866858", },
            Terms: [@"waimakariri district council"]),
        new NsiItem(
            DisplayName: @"Christchurch City Council",
            Id: @"christchurchcitycouncil-43ca57",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"monitoring_station", [@"operator:wikidata"] = @"Q5109064", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"monitoring_station", [@"operator"] = @"Christchurch City Council", [@"operator:wikidata"] = @"Q5109064", },
            Terms: [@"christchurch city council"]),
        new NsiItem(
            DisplayName: @"Alpine Energy",
            Id: @"alpineenergy-e516d3",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q65068829", [@"power"] = @"substation", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Alpine Energy", [@"operator:wikidata"] = @"Q65068829", [@"power"] = @"substation", },
            Terms: [@"alpine energy"]),
        new NsiItem(
            DisplayName: @"Alpine Energy",
            Id: @"alpineenergy-a6e13b",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q65068829", [@"power"] = @"transformer", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Alpine Energy", [@"operator:wikidata"] = @"Q65068829", [@"power"] = @"transformer", },
            Terms: [@"alpine energy"]),
        new NsiItem(
            DisplayName: @"Enable",
            Id: @"enable-ded43e",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q25349009", [@"telecom"] = @"exchange", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Enable", [@"operator:wikidata"] = @"Q25349009", [@"telecom"] = @"exchange", },
            Terms: [@"enable"]),
        new NsiItem(
            DisplayName: @"Metro (Christchurch)",
            Id: @"metrochristchurch-429601",
            Tags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"network:wikidata"] = @"Q7258007", [@"public_transport"] = @"platform", },
            AddTags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"highway"] = @"bus_stop", [@"network"] = @"Metro Christchurch", [@"network:wikidata"] = @"Q7258007", [@"public_transport"] = @"platform", },
            Terms: [@"Metro (Christchurch)", @"ecan", @"environment canterbury", @"metro christchurch"]),
        new NsiItem(
            DisplayName: @"Metro (Christchurch)",
            Id: @"metrochristchurch-034a34",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q7258007", [@"route"] = @"bus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Metro Christchurch", [@"network:wikidata"] = @"Q7258007", [@"route"] = @"bus", [@"type"] = @"route", },
            Terms: [@"Metro (Christchurch)", @"ecan", @"environment canterbury", @"metro christchurch"]),
    ];
}
