// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'ru-len.geojson'.</summary>
public static class NsiRegion_RU_LEN_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"Ленэнерго",
            Id: @"e6193d-f58ce4",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"charging_station", [@"operator:wikidata"] = @"Q4258700", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"charging_station", [@"operator"] = @"Ленэнерго", [@"operator:wikidata"] = @"Q4258700", },
            Terms: [@"ленэнерго", @"пао ""ленэнерго"""]),
        new NsiItem(
            DisplayName: @"Ленэнерго",
            Id: @"e6193d-e6c100",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"charge_point", [@"operator:wikidata"] = @"Q4258700", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"charge_point", [@"operator"] = @"Ленэнерго", [@"operator:wikidata"] = @"Q4258700", },
            Terms: [@"ленэнерго", @"пао ""ленэнерго"""]),
        new NsiItem(
            DisplayName: @"Nord Stream AG",
            Id: @"nordstreamag-f8e464",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"pipeline", [@"operator:wikidata"] = @"Q691563", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"pipeline", [@"operator"] = @"Nord Stream AG", [@"operator:wikidata"] = @"Q691563", },
            Terms: [@"nord stream ag"]),
        new NsiItem(
            DisplayName: @"Nord Stream AG",
            Id: @"nordstreamag-92ef49",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q691563", [@"pipeline"] = @"substation", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Nord Stream AG", [@"operator:wikidata"] = @"Q691563", [@"pipeline"] = @"substation", },
            Terms: [@"nord stream ag"]),
        new NsiItem(
            DisplayName: @"Комитет по Транспорту Санкт-Петербурга",
            Id: @"6185c7-f09832",
            Tags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"network:wikidata"] = @"Q115120075", [@"public_transport"] = @"platform", },
            AddTags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"highway"] = @"bus_stop", [@"network"] = @"Комитет по Транспорту Санкт-Петербурга", [@"network:wikidata"] = @"Q115120075", [@"public_transport"] = @"platform", },
            Terms: [@"комитет по транспорту санкт-петербурга"]),
        new NsiItem(
            DisplayName: @"Комитет по Транспорту Санкт-Петербурга",
            Id: @"saintpetersburgtransportcommittee-53f339",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q115120075", [@"railway"] = @"tram_stop", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Комитет по Транспорту Санкт-Петербурга", [@"network:en"] = @"Saint Petersburg Transport Committee", [@"network:ru"] = @"Комитет по Транспорту Санкт-Петербурга", [@"network:wikidata"] = @"Q115120075", [@"railway"] = @"tram_stop", },
            Terms: [@"saint petersburg transport committee", @"комитет по транспорту санкт-петербурга"]),
        new NsiItem(
            DisplayName: @"Комитет по Транспорту Санкт-Петербурга",
            Id: @"6185c7-8576bc",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q115120075", [@"route"] = @"bus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Комитет по Транспорту Санкт-Петербурга", [@"network:wikidata"] = @"Q115120075", [@"route"] = @"bus", [@"type"] = @"route", },
            Terms: [@"комитет по транспорту санкт-петербурга"]),
        new NsiItem(
            DisplayName: @"Комитет по Транспорту Санкт-Петербурга",
            Id: @"saintpetersburgtransportcommittee-abb09b",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q115120075", [@"route"] = @"tram", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Комитет по Транспорту Санкт-Петербурга", [@"network:en"] = @"Saint Petersburg Transport Committee", [@"network:ru"] = @"Комитет по Транспорту Санкт-Петербурга", [@"network:wikidata"] = @"Q115120075", [@"route"] = @"tram", [@"type"] = @"route", },
            Terms: [@"saint petersburg transport committee", @"комитет по транспорту санкт-петербурга"]),
        new NsiItem(
            DisplayName: @"Комитет по Транспорту Санкт-Петербурга",
            Id: @"saintpetersburgtransportcommittee-c8d96d",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q115120075", [@"route"] = @"trolleybus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Комитет по Транспорту Санкт-Петербурга", [@"network:en"] = @"Saint Petersburg Transport Committee", [@"network:ru"] = @"Комитет по Транспорту Санкт-Петербурга", [@"network:wikidata"] = @"Q115120075", [@"route"] = @"trolleybus", [@"type"] = @"route", },
            Terms: [@"saint petersburg transport committee", @"комитет по транспорту санкт-петербурга"]),
    ];
}
