// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'jp-ntt-west.geojson'.</summary>
public static class NsiRegion_JP_NTT_WEST_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"NTT西日本",
            Id: @"nippontelegraphandtelephonewest-ff8e1b",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"telephone", [@"operator:wikidata"] = @"Q11628418", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"telephone", [@"operator"] = @"西日本電信電話株式会社", [@"operator:en"] = @"Nippon Telegraph and Telephone West", [@"operator:ja"] = @"西日本電信電話株式会社", [@"operator:short"] = @"NTT西日本", [@"operator:short:en"] = @"NTT West", [@"operator:short:ja"] = @"NTT西日本", [@"operator:wikidata"] = @"Q11628418", },
            Terms: [@"nippon telegraph and telephone west", @"ntt west", @"ntt西日本", @"ntt西日本 (ntt east)", @"西日本電信電話", @"西日本電信電話株式会社"]),
        new NsiItem(
            DisplayName: @"NTT西日本",
            Id: @"nippontelegraphandtelephonewest-bad60c",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q11628418", [@"telecom"] = @"exchange", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"西日本電信電話株式会社", [@"operator:en"] = @"Nippon Telegraph and Telephone West", [@"operator:ja"] = @"西日本電信電話株式会社", [@"operator:short"] = @"NTT西日本", [@"operator:short:en"] = @"NTT West", [@"operator:short:ja"] = @"NTT西日本", [@"operator:wikidata"] = @"Q11628418", [@"telecom"] = @"exchange", },
            Terms: [@"nippon telegraph and telephone west", @"ntt west", @"ntt西日本", @"ntt西日本 (ntt east)", @"西日本電信電話", @"西日本電信電話株式会社"]),
    ];
}
