// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'mp'.</summary>
public static class NsiRegion_MP
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"Hawaiian First Bank",
            Id: @"hawaiianfirstbank-bc3288",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand:wikidata"] = @"Q3072937", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand"] = @"Hawaiian First Bank", [@"brand:wikidata"] = @"Q3072937", [@"operator"] = @"Hawaiian First Bank", [@"operator:wikidata"] = @"Q3072937", },
            Terms: [@"hawaiian first bank"]),
        new NsiItem(
            DisplayName: @"Hawaiian First Bank",
            Id: @"hawaiianfirstbank-ae6ba2",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand:wikidata"] = @"Q3072937", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand"] = @"Hawaiian First Bank", [@"brand:wikidata"] = @"Q3072937", [@"name"] = @"Hawaiian First Bank", },
            Terms: [@"hawaiian first bank"]),
    ];
}
