// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'ch-zh.geojson'.</summary>
public static class NsiRegion_CH_ZH_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"Stiftung Zürcher Gemeinschaftszentren",
            Id: @"stiftungzurchergemeinschaftszentren-4b6460",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"community_centre", [@"operator:wikidata"] = @"Q96178809", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"community_centre", [@"operator"] = @"Stiftung Zürcher Gemeinschaftszentren", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q96178809", },
            Terms: [@"stiftung zürcher gemeinschaftszentren"]),
        new NsiItem(
            DisplayName: @"WVZ",
            Id: @"wvz-32a6c1",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"drinking_water", [@"operator:wikidata"] = @"Q27229237", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"drinking_water", [@"operator"] = @"WVZ", [@"operator:wikidata"] = @"Q27229237", },
            Terms: [@"wvz"]),
        new NsiItem(
            DisplayName: @"Stadt Dietikon",
            Id: @"stadtdietikon-af761c",
            Tags: new Dictionary<string, string> { [@"education"] = @"kindergarten", [@"operator:wikidata"] = @"Q64070", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"kindergarten", [@"education"] = @"kindergarten", [@"operator"] = @"Stadt Dietikon", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q64070", },
            Terms: [@"stadt dietikon"]),
        new NsiItem(
            DisplayName: @"Pestalozzi-Bibliothek Zürich",
            Id: @"pestalozzibibliothekzurich-eb2614",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"library", [@"operator:wikidata"] = @"Q2073008", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"library", [@"operator"] = @"Pestalozzi-Bibliothek Zürich", [@"operator:short"] = @"PBZ", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q2073008", },
            Terms: [@"pbz", @"pbz pestalozzi-bibliothek zürich", @"pestalozzi-bibliothek zürich"]),
        new NsiItem(
            DisplayName: @"Kantonspolizei Zürich",
            Id: @"kantonspolizeizurich-ad4a21",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"police", [@"operator:wikidata"] = @"Q1728099", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"police", [@"operator"] = @"Kantonspolizei Zürich", [@"operator:wikidata"] = @"Q1728099", },
            Terms: [@"kantonspolizei zürich"]),
        new NsiItem(
            DisplayName: @"Stadtpolizei Zürich",
            Id: @"stadtpolizeizurich-ad4a21",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"police", [@"operator:wikidata"] = @"Q2327949", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"police", [@"operator"] = @"Stadtpolizei Zürich", [@"operator:wikidata"] = @"Q2327949", },
            Terms: [@"stadtpolizei zürich"]),
        new NsiItem(
            DisplayName: @"ERZ",
            Id: @"erz-3fa24a",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"recycling", [@"operator:wikidata"] = @"Q1345452", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"recycling", [@"operator"] = @"ERZ", [@"operator:wikidata"] = @"Q1345452", },
            Terms: [@"erz"]),
        new NsiItem(
            DisplayName: @"Gemeinde Gossau",
            Id: @"gemeindegossau-25b252",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q67525", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Gemeinde Gossau", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q67525", },
            Terms: [@"gemeinde gossau"]),
        new NsiItem(
            DisplayName: @"Kanton Zürich, Bildungsdirektion",
            Id: @"kantonzurichbildungsdirektion-25b252",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q113033130", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Kanton Zürich, Bildungsdirektion", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q113033130", },
            Terms: [@"kanton zürich, bildungsdirektion"]),
        new NsiItem(
            DisplayName: @"Stadt Winterthur",
            Id: @"stadtwinterthur-25b252",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q9125", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Stadt Winterthur", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q9125", },
            Terms: [@"stadt winterthur"]),
        new NsiItem(
            DisplayName: @"Stiftung Alterswohnungen der Stadt Zürich",
            Id: @"stiftungalterswohnungenderstadtzurich-f2c9df",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"social_facility", [@"operator:wikidata"] = @"Q2348865", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"social_facility", [@"operator"] = @"Stiftung Alterswohnungen der Stadt Zürich", [@"operator:short"] = @"SAW", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q2348865", },
            Terms: [@"saw", @"stiftung alterswohnungen der stadt zürich", @"stiftung alterswohnungen der stadt zürich (saw)"]),
        new NsiItem(
            DisplayName: @"Stiftung Zürcher Kinder- und Jugendheime",
            Id: @"stiftungzurcherkinderundjugendheime-f2c9df",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"social_facility", [@"operator:wikidata"] = @"Q33121178", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"social_facility", [@"operator"] = @"Stiftung Zürcher Kinder- und Jugendheime", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q33121178", },
            Terms: [@"stiftung zürcher kinder- und jugendheime"]),
        new NsiItem(
            DisplayName: @"Flughafen Zürich AG",
            Id: @"flughafenzurichag-960a4a",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"toilets", [@"operator:wikidata"] = @"Q1280993", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"toilets", [@"operator"] = @"Flughafen Zürich AG", [@"operator:wikidata"] = @"Q1280993", },
            Terms: [@"flughafen zürich ag"]),
        new NsiItem(
            DisplayName: @"Grün Stadt Zürich",
            Id: @"grunstadtzurich-d2a83e",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator:wikidata"] = @"Q1551785", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"nature_reserve", [@"operator"] = @"Grün Stadt Zürich", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q1551785", },
            Terms: [@"grün stadt zürich"]),
        new NsiItem(
            DisplayName: @"Grün Stadt Zürich",
            Id: @"grunstadtzurich-265307",
            Tags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator:wikidata"] = @"Q1551785", },
            AddTags: new Dictionary<string, string> { [@"leisure"] = @"park", [@"operator"] = @"Grün Stadt Zürich", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q1551785", },
            Terms: [@"grün stadt zürich"]),
        new NsiItem(
            DisplayName: @"Stadtwerk Winterthur",
            Id: @"stadtwerkwinterthur-2e7079",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"street_cabinet", [@"operator:wikidata"] = @"Q2328402", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"street_cabinet", [@"operator"] = @"Stadtwerk Winterthur", [@"operator:wikidata"] = @"Q2328402", },
            Terms: [@"stadtwerk winterthur"]),
        new NsiItem(
            DisplayName: @"Axpo/EKZ",
            Id: @"axpoekz-42bdec",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q679525", [@"power"] = @"substation", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Axpo/EKZ", [@"operator:wikidata"] = @"Q679525", [@"power"] = @"substation", },
            Terms: [@"axpo/ekz"]),
        new NsiItem(
            DisplayName: @"Flughafen Zürich AG",
            Id: @"flughafenzurichag-42bdec",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q1280993", [@"power"] = @"substation", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Flughafen Zürich AG", [@"operator:wikidata"] = @"Q1280993", [@"power"] = @"substation", },
            Terms: [@"flughafen zürich ag"]),
        new NsiItem(
            DisplayName: @"Axpo/EKZ",
            Id: @"axpoekz-41d358",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q679525", [@"power"] = @"transformer", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Axpo/EKZ", [@"operator:wikidata"] = @"Q679525", [@"power"] = @"transformer", },
            Terms: [@"axpo/ekz"]),
        new NsiItem(
            DisplayName: @"Flughafen Zürich AG",
            Id: @"flughafenzurichag-41d358",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q1280993", [@"power"] = @"transformer", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Flughafen Zürich AG", [@"operator:wikidata"] = @"Q1280993", [@"power"] = @"transformer", },
            Terms: [@"flughafen zürich ag"]),
        new NsiItem(
            DisplayName: @"ZVV",
            Id: @"zvv-4793be",
            Tags: new Dictionary<string, string> { [@"ferry"] = @"yes", [@"network:wikidata"] = @"Q201977", [@"public_transport"] = @"station", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"ferry_terminal", [@"ferry"] = @"yes", [@"network"] = @"ZVV", [@"network:wikidata"] = @"Q201977", [@"public_transport"] = @"station", },
            Terms: [@"zürcher verkehrsverbund", @"zvv"]),
        new NsiItem(
            DisplayName: @"Tarifverbund Zug",
            Id: @"tarifverbundzug-18b67e",
            Tags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"network:wikidata"] = @"Q2394216", [@"public_transport"] = @"platform", },
            AddTags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"highway"] = @"bus_stop", [@"network"] = @"Tarifverbund Zug", [@"network:short"] = @"TVZG", [@"network:wikidata"] = @"Q2394216", [@"public_transport"] = @"platform", },
            Terms: [@"tarifverbund zug", @"tvzg", @"zugerpass"]),
        new NsiItem(
            DisplayName: @"ZVV",
            Id: @"zvv-605bfd",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q201977", [@"railway"] = @"tram_stop", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"ZVV", [@"network:wikidata"] = @"Q201977", [@"railway"] = @"tram_stop", },
            Terms: [@"zvv"]),
        new NsiItem(
            DisplayName: @"Tarifverbund Zug",
            Id: @"tarifverbundzug-5a9ef4",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q2394216", [@"route"] = @"bus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Tarifverbund Zug", [@"network:short"] = @"TVZG", [@"network:wikidata"] = @"Q2394216", [@"route"] = @"bus", [@"type"] = @"route", },
            Terms: [@"tarifverbund zug", @"tvzg", @"zugerpass"]),
        new NsiItem(
            DisplayName: @"ZVV",
            Id: @"zvv-2c211a",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q201977", [@"route"] = @"ferry", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"ZVV", [@"network:wikidata"] = @"Q201977", [@"route"] = @"ferry", [@"type"] = @"route", },
            Terms: [@"zürcher verkehrsverbund", @"zvv"]),
        new NsiItem(
            DisplayName: @"ZVV",
            Id: @"zvv-2c211a",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q201977", [@"route"] = @"ferry", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"ZVV", [@"network:wikidata"] = @"Q201977", [@"route"] = @"ferry", },
            Terms: [@"zürcher verkehrsverbund", @"zvv"]),
        new NsiItem(
            DisplayName: @"ZVV",
            Id: @"zvv-41185a",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q201977", [@"route"] = @"tram", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"ZVV", [@"network:wikidata"] = @"Q201977", [@"route"] = @"tram", [@"type"] = @"route", },
            Terms: [@"zvv"]),
        new NsiItem(
            DisplayName: @"ZVV",
            Id: @"zvv-e669dd",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q201977", [@"route"] = @"trolleybus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"ZVV", [@"network:wikidata"] = @"Q201977", [@"route"] = @"trolleybus", [@"type"] = @"route", },
            Terms: [@"zvv"]),
    ];
}
