// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'jp-tokai.geojson'.</summary>
public static class NsiRegion_JP_TOKAI_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"オークワ",
            Id: @"okuwa-51a621",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q11293166", [@"shop"] = @"supermarket", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"オークワ", [@"brand:en"] = @"Okuwa", [@"brand:ja"] = @"オークワ", [@"brand:wikidata"] = @"Q11293166", [@"name"] = @"オークワ", [@"name:en"] = @"Okuwa", [@"name:ja"] = @"オークワ", [@"shop"] = @"supermarket", },
            Terms: [@"okuwa", @"オークワ"]),
        new NsiItem(
            DisplayName: @"ヤマナカ",
            Id: @"yamanaka-b9af80",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q11345199", [@"shop"] = @"supermarket", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"ヤマナカ", [@"brand:en"] = @"Yamanaka", [@"brand:ja"] = @"ヤマナカ", [@"brand:wikidata"] = @"Q11345199", [@"name"] = @"ヤマナカ", [@"name:en"] = @"Yamanaka", [@"name:ja"] = @"ヤマナカ", [@"shop"] = @"supermarket", },
            Terms: [@"yamanaka", @"ヤマナカ"]),
    ];
}
