// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'ph-40-batangas_city.geojson'.</summary>
public static class NsiRegion_PH_40_BATANGAS_CITY_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"Coastal District",
            Id: @"coastaldistrict-1a45a4",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130491375", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Coastal District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130491375", },
            Terms: [@"coastal district", @"coastal district batangas city schools division, deped"]),
        new NsiItem(
            DisplayName: @"East District (Batangas City)",
            Id: @"eastdistrict-1a45a4",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130491377", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"East District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130491377", },
            Terms: [@"East District (Batangas City)", @"east district", @"east district batangas city schools division, deped"]),
        new NsiItem(
            DisplayName: @"North District (Batangas City)",
            Id: @"northdistrict-1a45a4",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130491378", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"North District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130491378", },
            Terms: [@"North District (Batangas City)", @"north district", @"north district batangas city schools division, deped"]),
        new NsiItem(
            DisplayName: @"South District (Batangas City)",
            Id: @"southdistrict-1a45a4",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130491379", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"South District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130491379", },
            Terms: [@"South District (Batangas City)", @"south district", @"south district batangas city schools division, deped"]),
        new NsiItem(
            DisplayName: @"West District (Batangas City)",
            Id: @"westdistrict-1a45a4",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q130491380", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"West District", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q130491380", },
            Terms: [@"West District (Batangas City)", @"west district", @"west district batangas city schools division, deped"]),
    ];
}
