// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'kg'.</summary>
public static class NsiRegion_KG
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"Газпромнефть",
            Id: @"0b910f-dec76e",
            Tags: new Dictionary<string, string> { [@"advertising"] = @"totem", [@"brand:wikidata"] = @"Q1461799", },
            AddTags: new Dictionary<string, string> { [@"advertising"] = @"totem", [@"brand"] = @"Газпромнефть", [@"brand:wikidata"] = @"Q1461799", },
            Terms: [@"газпром", @"газпромнефть"]),
        new NsiItem(
            DisplayName: @"Halyk Bank",
            Id: @"halykbank-bfa88b",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand:wikidata"] = @"Q1046186", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand"] = @"Halyk Bank", [@"brand:wikidata"] = @"Q1046186", [@"old_name"] = @"Народный банк", [@"operator"] = @"Halyk Bank", [@"operator:wikidata"] = @"Q1046186", },
            Terms: [@"halyk bank", @"казкоммерцбанк", @"народный банк"]),
        new NsiItem(
            DisplayName: @"Бакай банк",
            Id: @"27e679-03a30b",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand:wikidata"] = @"Q4075821", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand"] = @"Бакай банк", [@"brand:wikidata"] = @"Q4075821", [@"operator"] = @"Бакай банк", [@"operator:wikidata"] = @"Q4075821", },
            Terms: [@"бакай банк"]),
        new NsiItem(
            DisplayName: @"Halyk Bank",
            Id: @"halykbank-c4165a",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand:wikidata"] = @"Q1046186", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand"] = @"Halyk Bank", [@"brand:wikidata"] = @"Q1046186", [@"name"] = @"Halyk Bank", [@"name:en"] = @"Halyk Bank", [@"name:kk"] = @"Халық Банкі", [@"name:ru"] = @"Халык банк", [@"official_name:kk"] = @"«Қазақстан Халық Банкі» АҚ", [@"official_name:ru"] = @"АО «Народный Банк Казахстана»", [@"old_name"] = @"Народный банк", },
            Terms: [@"«қазақстан халық банкі» ақ", @"halyk bank", @"ао «народный банк казахстана»", @"казкоммерцбанк", @"народный банк", @"халык банк", @"халық банкі"]),
        new NsiItem(
            DisplayName: @"Бакай банк",
            Id: @"27e679-cf89ba",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand:wikidata"] = @"Q4075821", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand"] = @"Бакай банк", [@"brand:wikidata"] = @"Q4075821", [@"name"] = @"Бакай банк", },
            Terms: [@"бакай банк"]),
        new NsiItem(
            DisplayName: @"Coyote Ugly",
            Id: @"coyoteugly-163d6e",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bar", [@"brand:wikidata"] = @"Q4131558", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bar", [@"brand"] = @"Coyote Ugly Saloon", [@"brand:wikidata"] = @"Q4131558", [@"name"] = @"Coyote Ugly", },
            Terms: [@"Coyote Ugly", @"coyote ugly saloon"]),
        new NsiItem(
            DisplayName: @"ЧебурекМи",
            Id: @"0d6f84-ec2b4e",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"fast_food", [@"brand:wikidata"] = @"Q129419587", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"fast_food", [@"brand"] = @"ЧебурекМи", [@"brand:wikidata"] = @"Q129419587", [@"cuisine"] = @"coffee_shop;international", [@"name"] = @"ЧебурекМи", [@"takeaway"] = @"yes", },
            Terms: [@"чебурекми"]),
        new NsiItem(
            DisplayName: @"Газпромнефть",
            Id: @"0b910f-bb6729",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"fuel", [@"brand:wikidata"] = @"Q1461799", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"fuel", [@"brand"] = @"Газпромнефть", [@"brand:wikidata"] = @"Q1461799", [@"name"] = @"Газпромнефть", },
            Terms: [@"газпром", @"газпромнефть"]),
        new NsiItem(
            DisplayName: @"33 пингвина",
            Id: @"fd1d7e-3c9560",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"ice_cream", [@"brand:wikidata"] = @"Q110147993", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"ice_cream", [@"brand"] = @"33 пингвина", [@"brand:wikidata"] = @"Q110147993", [@"name"] = @"33 пингвина", },
            Terms: [@"33 пингвина"]),
        new NsiItem(
            DisplayName: @"СДЭК",
            Id: @"5ac048-c762cb",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"post_office", [@"brand:wikidata"] = @"Q28665980", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"post_office", [@"brand"] = @"СДЭК", [@"brand:wikidata"] = @"Q28665980", [@"name"] = @"СДЭК", },
            Terms: [@"сдэк", @"ук ""сдэк"""]),
        new NsiItem(
            DisplayName: @"Билайн",
            Id: @"beeline-f03186",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q402880", [@"office"] = @"telecommunication", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"Билайн", [@"brand:en"] = @"Beeline", [@"brand:ru"] = @"Билайн", [@"brand:wikidata"] = @"Q402880", [@"name"] = @"Билайн", [@"name:en"] = @"Beeline", [@"name:ru"] = @"Билайн", [@"office"] = @"telecommunication", },
            Terms: [@"beeline", @"билайн"]),
        new NsiItem(
            DisplayName: @"Sela",
            Id: @"sela-2d1caa",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q62075111", [@"shop"] = @"clothes", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"Sela", [@"brand:wikidata"] = @"Q62075111", [@"name"] = @"Sela", [@"shop"] = @"clothes", },
            Terms: [@"sela"]),
        new NsiItem(
            DisplayName: @"Магнит",
            Id: @"magnit-4e470f",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q940518", [@"shop"] = @"convenience", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"Магнит", [@"brand:en"] = @"Magnit", [@"brand:ru"] = @"Магнит", [@"brand:wikidata"] = @"Q940518", [@"name"] = @"Магнит", [@"name:en"] = @"Magnit", [@"name:ru"] = @"Магнит", [@"shop"] = @"convenience", },
            Terms: [@"magnit", @"магнит", @"магнит у дома"]),
        new NsiItem(
            DisplayName: @"Шатура",
            Id: @"shatura-56eb69",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q126596908", [@"shop"] = @"furniture", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"Шатура", [@"brand:en"] = @"Shatura", [@"brand:ru"] = @"Шатура", [@"brand:wikidata"] = @"Q126596908", [@"name"] = @"Шатура", [@"name:en"] = @"Shatura", [@"name:ru"] = @"Шатура", [@"shop"] = @"furniture", },
            Terms: [@"shatura", @"шатура"]),
        new NsiItem(
            DisplayName: @"Билайн",
            Id: @"beeline-3f097a",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q402880", [@"shop"] = @"mobile_phone", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"Билайн", [@"brand:en"] = @"Beeline", [@"brand:ru"] = @"Билайн", [@"brand:wikidata"] = @"Q402880", [@"name"] = @"Билайн", [@"name:en"] = @"Beeline", [@"name:ru"] = @"Билайн", [@"shop"] = @"mobile_phone", },
            Terms: [@"beeline", @"билайн"]),
        new NsiItem(
            DisplayName: @"Wildberries",
            Id: @"wildberries-f8825b",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q24933714", [@"shop"] = @"outpost", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"Wildberries", [@"brand:wikidata"] = @"Q24933714", [@"name"] = @"Wildberries", [@"shop"] = @"outpost", },
            Terms: [@"wildberries"]),
        new NsiItem(
            DisplayName: @"Магнит",
            Id: @"magnit-d9ae50",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q940518", [@"shop"] = @"supermarket", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"Магнит", [@"brand:en"] = @"Magnit", [@"brand:ru"] = @"Магнит", [@"brand:wikidata"] = @"Q940518", [@"name"] = @"Магнит", [@"name:en"] = @"Magnit", [@"name:ru"] = @"Магнит", [@"shop"] = @"supermarket", },
            Terms: [@"magnit", @"магнит"]),
        new NsiItem(
            DisplayName: @"Fix Price",
            Id: @"fixprice-b3b517",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q4038791", [@"shop"] = @"variety_store", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"Fix Price", [@"brand:wikidata"] = @"Q4038791", [@"name"] = @"Fix Price", [@"name:be"] = @"Фікс Прайс", [@"name:be-Latn"] = @"Fiks Prajs", [@"name:en"] = @"Fix Price", [@"name:ru"] = @"Фикс Прайс", [@"name:uk"] = @"Фікс Прайс", [@"shop"] = @"variety_store", },
            Terms: [@"fiks prajs", @"fix price", @"фикс прайс", @"фікс прайс"]),
        new NsiItem(
            DisplayName: @"СДЭК",
            Id: @"5ac048-6df28a",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"post_box", [@"operator:wikidata"] = @"Q28665980", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"post_box", [@"brand"] = @"СДЭК", [@"brand:wikidata"] = @"Q28665980", [@"operator"] = @"СДЭК", [@"operator:wikidata"] = @"Q28665980", },
            Terms: [@"сдэк", @"ук ""сдэк"""]),
    ];
}
