// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'de-hh.geojson'.</summary>
public static class NsiRegion_DE_HH_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"Sparda-Bank Hamburg",
            Id: @"spardabankhamburg-ff8f99",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand:wikidata"] = @"Q1231375", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand"] = @"Sparda-Bank Hamburg", [@"brand:wikidata"] = @"Q1231375", [@"operator"] = @"Sparda-Bank Hamburg", [@"operator:wikidata"] = @"Q1231375", },
            Terms: [@"sparda-bank", @"sparda-bank hamburg", @"sparda-bank hamburg eg"]),
        new NsiItem(
            DisplayName: @"Sparda-Bank Hamburg",
            Id: @"spardabankhamburg-b869bd",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand:wikidata"] = @"Q1231375", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand"] = @"Sparda-Bank Hamburg", [@"brand:wikidata"] = @"Q1231375", [@"name"] = @"Sparda-Bank Hamburg", },
            Terms: [@"sparda-bank", @"sparda-bank hamburg", @"sparda-bank hamburg eg"]),
        new NsiItem(
            DisplayName: @"AOK Rheinland/Hamburg",
            Id: @"aokrheinlandhamburg-2c6953",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q1000317", [@"office"] = @"insurance", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"AOK Rheinland/Hamburg", [@"brand:wikidata"] = @"Q1000317", [@"insurance"] = @"health", [@"name"] = @"AOK Rheinland/Hamburg", [@"office"] = @"insurance", },
            Terms: [@"aok hamburg", @"aok rheinland", @"aok rheinland/hamburg"]),
        new NsiItem(
            DisplayName: @"Barrique",
            Id: @"barrique-c5afd8",
            Tags: new Dictionary<string, string> { [@"brand:wikidata"] = @"Q114133164", [@"shop"] = @"alcohol", },
            AddTags: new Dictionary<string, string> { [@"brand"] = @"Barrique", [@"brand:wikidata"] = @"Q114133164", [@"name"] = @"Barrique", [@"shop"] = @"alcohol", },
            Terms: [@"barrique"]),
        new NsiItem(
            DisplayName: @"Hamburger Energiewerke",
            Id: @"henwmobil-43ccfe",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"charging_station", [@"operator:wikidata"] = @"Q107336926", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"charging_station", [@"operator"] = @"HEnW Mobil", [@"operator:wikidata"] = @"Q107336926", },
            Terms: [@"hamburger energiewerke", @"henw mobil", @"stromnetz hamburg"]),
        new NsiItem(
            DisplayName: @"Elbkinder Vereinigung Hamburger Kitas gGmbH",
            Id: @"elbkindervereinigunghamburgerkitasggmbh-595700",
            Tags: new Dictionary<string, string> { [@"education"] = @"kindergarten", [@"operator:wikidata"] = @"Q126896525", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"kindergarten", [@"education"] = @"kindergarten", [@"operator"] = @"Elbkinder Vereinigung Hamburger Kitas gGmbH", [@"operator:type"] = @"private", [@"operator:wikidata"] = @"Q126896525", },
            Terms: [@"elbkinder vereinigung hamburger kitas ggmbh", @"vereinigung hamburger kindertagesstätten"]),
        new NsiItem(
            DisplayName: @"Stiftung Hamburger Öffentliche Bücherhallen",
            Id: @"stiftunghamburgeroffentlichebucherhallen-bba292",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"library", [@"operator:wikidata"] = @"Q1573209", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"library", [@"operator"] = @"Stiftung Hamburger Öffentliche Bücherhallen", [@"operator:short"] = @"HÖB", [@"operator:type"] = @"public", [@"operator:wikidata"] = @"Q1573209", },
            Terms: [@"bücherhallen", @"hamburger bücherhallen", @"hamburger öffentliche bücherhallen", @"höb", @"stiftung hamburger öffentliche bücherhallen"]),
        new NsiItem(
            DisplayName: @"Universität Hamburg",
            Id: @"universitathamburg-bba292",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"library", [@"operator:wikidata"] = @"Q156725", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"library", [@"operator"] = @"Universität Hamburg", [@"operator:type"] = @"university", [@"operator:wikidata"] = @"Q156725", },
            Terms: [@"universität hamburg"]),
        new NsiItem(
            DisplayName: @"Landeskriminalamt Hamburg",
            Id: @"landeskriminalamthamburg-a93b62",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"police", [@"operator:wikidata"] = @"Q1802337", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"police", [@"operator"] = @"Landeskriminalamt Hamburg", [@"operator:short"] = @"LKA", [@"operator:wikidata"] = @"Q1802337", },
            Terms: [@"landeskriminalamt hamburg", @"lka"]),
        new NsiItem(
            DisplayName: @"Polizei Hamburg",
            Id: @"polizeihamburg-a93b62",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"police", [@"operator:wikidata"] = @"Q882239", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"police", [@"operator"] = @"Polizei Hamburg", [@"operator:wikidata"] = @"Q882239", },
            Terms: [@"polizei hamburg"]),
        new NsiItem(
            DisplayName: @"Stadtreinigung Hamburg",
            Id: @"stadtreinigunghamburg-d0aa76",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"recycling", [@"operator:wikidata"] = @"Q1532474", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"recycling", [@"operator"] = @"Stadtreinigung Hamburg", [@"operator:wikidata"] = @"Q1532474", },
            Terms: [@"stadtreinigung hamburg"]),
        new NsiItem(
            DisplayName: @"F&W",
            Id: @"fandw-dca067",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"social_facility", [@"operator:wikidata"] = @"Q133777809", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"social_facility", [@"operator"] = @"F&W", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q133777809", },
            Terms: [@"f & w fördern und wohnen aör", @"f&w"]),
        new NsiItem(
            DisplayName: @"Stadtreinigung Hamburg",
            Id: @"stadtreinigunghamburg-263841",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"toilets", [@"operator:wikidata"] = @"Q1532474", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"toilets", [@"operator"] = @"Stadtreinigung Hamburg", [@"operator:wikidata"] = @"Q1532474", },
            Terms: [@"stadtreinigung hamburg"]),
        new NsiItem(
            DisplayName: @"Feuerwehr Hamburg",
            Id: @"feuerwehrhamburg-cc534f",
            Tags: new Dictionary<string, string> { [@"emergency"] = @"ambulance_station", [@"operator:wikidata"] = @"Q1409871", },
            AddTags: new Dictionary<string, string> { [@"emergency"] = @"ambulance_station", [@"operator"] = @"Feuerwehr Hamburg", [@"operator:wikidata"] = @"Q1409871", },
            Terms: [@"feuerwehr hamburg"]),
        new NsiItem(
            DisplayName: @"Hamburger Energiewerke",
            Id: @"henwmobil-d99909",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"charge_point", [@"operator:wikidata"] = @"Q107336926", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"charge_point", [@"operator"] = @"HEnW Mobil", [@"operator:wikidata"] = @"Q107336926", },
            Terms: [@"hamburger energiewerke", @"henw mobil", @"stromnetz hamburg"]),
        new NsiItem(
            DisplayName: @"Hamburger Energienetze",
            Id: @"hamburgerenergienetze-c70552",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"street_cabinet", [@"operator:wikidata"] = @"Q130127016", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"street_cabinet", [@"operator"] = @"Hamburger Energienetze", [@"operator:wikidata"] = @"Q130127016", },
            Terms: [@"hamburger energienetze", @"stromnetz hamburg"]),
        new NsiItem(
            DisplayName: @"Hamburger Energienetze",
            Id: @"hamburgerenergienetze-840ea0",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q130127016", [@"power"] = @"line", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Hamburger Energienetze", [@"operator:wikidata"] = @"Q130127016", [@"power"] = @"line", },
            Terms: [@"hamburger energienetze", @"hamburger energienetze gmbh", @"stromnetz hamburg", @"stromnetz hamburg gmbh"]),
        new NsiItem(
            DisplayName: @"Hamburger Energienetze",
            Id: @"hamburgerenergienetze-6e3902",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q130127016", [@"power"] = @"minor_line", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Hamburger Energienetze", [@"operator:wikidata"] = @"Q130127016", [@"power"] = @"minor_line", },
            Terms: [@"hamburger energienetze", @"hamburger energienetze gmbh", @"stromnetz hamburg", @"stromnetz hamburg gmbh"]),
        new NsiItem(
            DisplayName: @"Hamburger Energienetze",
            Id: @"hamburgerenergienetze-e3db22",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q130127016", [@"power"] = @"pole", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Hamburger Energienetze", [@"operator:wikidata"] = @"Q130127016", [@"power"] = @"pole", },
            Terms: [@"hamburger energienetze", @"hamburger energienetze gmbh", @"stromnetz hamburg", @"stromnetz hamburg gmbh"]),
        new NsiItem(
            DisplayName: @"Hamburger Energienetze",
            Id: @"hamburgerenergienetze-de1365",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q130127016", [@"power"] = @"substation", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Hamburger Energienetze", [@"operator:wikidata"] = @"Q130127016", [@"power"] = @"substation", },
            Terms: [@"hamburger energienetze", @"hamburger energienetze gmbh", @"stromnetz hamburg"]),
        new NsiItem(
            DisplayName: @"Hamburger Energienetze",
            Id: @"hamburgerenergienetze-7db4f5",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q130127016", [@"power"] = @"tower", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Hamburger Energienetze", [@"operator:wikidata"] = @"Q130127016", [@"power"] = @"tower", },
            Terms: [@"hamburger energienetze", @"hamburger energienetze gmbh", @"stromnetz hamburg", @"stromnetz hamburg gmbh"]),
        new NsiItem(
            DisplayName: @"Hamburger Energienetze",
            Id: @"hamburgerenergienetze-eba937",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q130127016", [@"power"] = @"transformer", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Hamburger Energienetze", [@"operator:wikidata"] = @"Q130127016", [@"power"] = @"transformer", },
            Terms: [@"hamburger energienetze", @"hamburger energienetze gmbh", @"stromnetz hamburg"]),
        new NsiItem(
            DisplayName: @"Hamburger Energienetze",
            Id: @"hamburgerenergienetze-227083",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q130127016", [@"route"] = @"power", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Hamburger Energienetze", [@"operator:wikidata"] = @"Q130127016", [@"route"] = @"power", [@"type"] = @"route", },
            Terms: [@"hamburger energienetze", @"hamburger energienetze gmbh", @"stromnetz hamburg", @"stromnetz hamburg gmbh"]),
        new NsiItem(
            DisplayName: @"Hamburger Verkehrsverbund",
            Id: @"hamburgerverkehrsverbund-89299e",
            Tags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"network:wikidata"] = @"Q896916", [@"public_transport"] = @"platform", },
            AddTags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"highway"] = @"bus_stop", [@"network"] = @"Hamburger Verkehrsverbund", [@"network:short"] = @"HVV", [@"network:wikidata"] = @"Q896916", [@"public_transport"] = @"platform", },
            Terms: [@"hamburger verkehrsverbund", @"hvv"]),
        new NsiItem(
            DisplayName: @"Nahverkehrsverbund Schleswig-Holstein",
            Id: @"nahverkehrsverbundschleswigholstein-ccb756",
            Tags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"network:wikidata"] = @"Q15825147", [@"public_transport"] = @"platform", },
            AddTags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"highway"] = @"bus_stop", [@"network"] = @"Nahverkehrsverbund Schleswig-Holstein", [@"network:short"] = @"NAH.SH", [@"network:wikidata"] = @"Q15825147", [@"public_transport"] = @"platform", },
            Terms: [@"nah.sh", @"nahverkehrsverbund schleswig-holstein", @"verkehrsgemeinschaft rendsburg-eckernförde", @"vg rd-eck"]),
        new NsiItem(
            DisplayName: @"Hamburger Verkehrsverbund",
            Id: @"hamburgerverkehrsverbund-cae733",
            Tags: new Dictionary<string, string> { [@"light_rail"] = @"yes", [@"network:wikidata"] = @"Q896916", [@"public_transport"] = @"station", },
            AddTags: new Dictionary<string, string> { [@"light_rail"] = @"yes", [@"network"] = @"Hamburger Verkehrsverbund", [@"network:short"] = @"HVV", [@"network:wikidata"] = @"Q896916", [@"operator"] = @"S-Bahn Hamburg GmbH", [@"operator:wikidata"] = @"Q99869216", [@"public_transport"] = @"station", [@"railway"] = @"station", [@"station"] = @"light_rail", },
            Terms: [@"hamburger verkehrsverbund", @"hvv", @"s-bahn hamburg gmbh"]),
        new NsiItem(
            DisplayName: @"Hamburger Verkehrsverbund",
            Id: @"hamburgerverkehrsverbund-185a67",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q896916", [@"public_transport"] = @"station", [@"subway"] = @"yes", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Hamburger Verkehrsverbund", [@"network:short"] = @"HVV", [@"network:wikidata"] = @"Q896916", [@"operator"] = @"Hamburger Hochbahn", [@"operator:short"] = @"HHA", [@"operator:wikidata"] = @"Q6442", [@"public_transport"] = @"station", [@"railway"] = @"station", [@"station"] = @"subway", [@"subway"] = @"yes", },
            Terms: [@"hamburger hochbahn", @"hamburger verkehrsverbund", @"hha", @"hvv"]),
        new NsiItem(
            DisplayName: @"Hamburger Verkehrsverbund",
            Id: @"hamburgerverkehrsverbund-880c84",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q896916", [@"route"] = @"bus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Hamburger Verkehrsverbund", [@"network:short"] = @"HVV", [@"network:wikidata"] = @"Q896916", [@"route"] = @"bus", [@"type"] = @"route", },
            Terms: [@"hamburger verkehrsverbund", @"hvv"]),
        new NsiItem(
            DisplayName: @"Nahverkehrsverbund Schleswig-Holstein",
            Id: @"nahverkehrsverbundschleswigholstein-a48f5e",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q15825147", [@"route"] = @"bus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Nahverkehrsverbund Schleswig-Holstein", [@"network:short"] = @"NAH.SH", [@"network:wikidata"] = @"Q15825147", [@"route"] = @"bus", [@"type"] = @"route", },
            Terms: [@"nah.sh", @"nahverkehrsverbund schleswig-holstein", @"verkehrsgemeinschaft rendsburg-eckernförde", @"vg rd-eck"]),
        new NsiItem(
            DisplayName: @"Hamburger Verkehrsverbund",
            Id: @"hamburgerverkehrsverbund-03e6a5",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q896916", [@"route"] = @"light_rail", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Hamburger Verkehrsverbund", [@"network:short"] = @"HVV", [@"network:wikidata"] = @"Q896916", [@"operator"] = @"S-Bahn Hamburg GmbH", [@"operator:wikidata"] = @"Q99869216", [@"route"] = @"light_rail", [@"type"] = @"route", },
            Terms: [@"hamburger verkehrsverbund", @"hvv", @"s-bahn hamburg gmbh"]),
        new NsiItem(
            DisplayName: @"Hamburger Verkehrsverbund",
            Id: @"hamburgerverkehrsverbund-59fd3b",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q896916", [@"route"] = @"subway", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Hamburger Verkehrsverbund", [@"network:short"] = @"HVV", [@"network:wikidata"] = @"Q896916", [@"operator"] = @"Hamburger Hochbahn", [@"operator:short"] = @"HHA", [@"operator:wikidata"] = @"Q6442", [@"route"] = @"subway", [@"type"] = @"route", },
            Terms: [@"hamburger hochbahn", @"hamburger verkehrsverbund", @"hha", @"hvv"]),
    ];
}
