// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'at-3.geojson'.</summary>
public static class NsiRegion_AT_3_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"nextbike Niederösterreich",
            Id: @"nextbikeniederosterreich-17b656",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bicycle_rental", [@"brand:wikidata"] = @"Q121951638", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bicycle_rental", [@"brand"] = @"nextbike Niederösterreich", [@"brand:wikidata"] = @"Q121951638", [@"operator"] = @"Nextbike", [@"operator:type"] = @"private", [@"operator:wikidata"] = @"Q2351279", },
            Terms: [@"nextbike", @"nextbike niederösterreich"]),
        new NsiItem(
            DisplayName: @"Linz AG",
            Id: @"linzag-b99113",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"car_sharing", [@"operator:wikidata"] = @"Q1827148", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"car_sharing", [@"operator"] = @"Linz AG", [@"operator:type"] = @"private", [@"operator:wikidata"] = @"Q1827148", },
            Terms: [@"linz ag"]),
        new NsiItem(
            DisplayName: @"Linz AG",
            Id: @"linzag-6a71ec",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"charging_station", [@"operator:wikidata"] = @"Q1827148", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"charging_station", [@"operator"] = @"Linz AG", [@"operator:wikidata"] = @"Q1827148", },
            Terms: [@"linz ag"]),
        new NsiItem(
            DisplayName: @"Stadt Wien",
            Id: @"stadtwien-66c353",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"drinking_water", [@"operator:wikidata"] = @"Q1884195", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"drinking_water", [@"operator"] = @"Stadt Wien", [@"operator:wikidata"] = @"Q1884195", },
            Terms: [@"stadt wien"]),
        new NsiItem(
            DisplayName: @"Land Niederösterreich",
            Id: @"landniederosterreich-4694b0",
            Tags: new Dictionary<string, string> { [@"education"] = @"kindergarten", [@"operator:wikidata"] = @"Q33121933", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"kindergarten", [@"education"] = @"kindergarten", [@"operator"] = @"Land Niederösterreich", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q33121933", },
            Terms: [@"land niederösterreich"]),
        new NsiItem(
            DisplayName: @"Landespolizeidirektion Niederösterreich",
            Id: @"landespolizeidirektionniederosterreich-890ad1",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"police", [@"operator:wikidata"] = @"Q131363945", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"police", [@"operator"] = @"Landespolizeidirektion Niederösterreich", [@"operator:wikidata"] = @"Q131363945", },
            Terms: [@"landespolizeidirektion niederösterreich"]),
        new NsiItem(
            DisplayName: @"Stadt Krems",
            Id: @"stadtkrems-a48b14",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"recycling", [@"operator:wikidata"] = @"Q131266", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"recycling", [@"operator"] = @"Stadt Krems", [@"operator:wikidata"] = @"Q131266", },
            Terms: [@"stadt krems"]),
        new NsiItem(
            DisplayName: @"Stadt Wien",
            Id: @"stadtwien-f61c06",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q1884195", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"Stadt Wien", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q1884195", },
            Terms: [@"stadt wien"]),
        new NsiItem(
            DisplayName: @"Stadt Wien",
            Id: @"stadtwien-235e3c",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"toilets", [@"operator:wikidata"] = @"Q1884195", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"toilets", [@"operator"] = @"Stadt Wien", [@"operator:wikidata"] = @"Q1884195", },
            Terms: [@"stadt wien"]),
        new NsiItem(
            DisplayName: @"Österreichisches Rotes Kreuz, Landesverband Niederösterreich",
            Id: @"osterreichischesroteskreuzlandesverbandniederosterreich-d0862d",
            Tags: new Dictionary<string, string> { [@"emergency"] = @"ambulance_station", [@"operator:wikidata"] = @"Q61950913", },
            AddTags: new Dictionary<string, string> { [@"emergency"] = @"ambulance_station", [@"operator"] = @"Österreichisches Rotes Kreuz, Landesverband Niederösterreich", [@"operator:wikidata"] = @"Q61950913", },
            Terms: [@"österreichisches rotes kreuz, landesverband niederösterreich"]),
        new NsiItem(
            DisplayName: @"Linz AG",
            Id: @"linzag-081dfd",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"charge_point", [@"operator:wikidata"] = @"Q1827148", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"charge_point", [@"operator"] = @"Linz AG", [@"operator:wikidata"] = @"Q1827148", },
            Terms: [@"linz ag"]),
        new NsiItem(
            DisplayName: @"MA 31",
            Id: @"ma31-ac055c",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"pipeline", [@"operator:wikidata"] = @"Q262313", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"pipeline", [@"operator"] = @"MA 31", [@"operator:wikidata"] = @"Q262313", },
            Terms: [@"ma 31", @"ma31 magistrat der stadt wien, wiener wasser"]),
        new NsiItem(
            DisplayName: @"Stadt Wien",
            Id: @"stadtwien-f28f65",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"pipeline", [@"operator:wikidata"] = @"Q1884195", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"pipeline", [@"operator"] = @"Stadt Wien", [@"operator:wikidata"] = @"Q1884195", },
            Terms: [@"stadt wien"]),
        new NsiItem(
            DisplayName: @"Kabelplus",
            Id: @"kabelplus-5d0dd0",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"street_cabinet", [@"operator:wikidata"] = @"Q51711011", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"street_cabinet", [@"operator"] = @"Kabelplus", [@"operator:wikidata"] = @"Q51711011", },
            Terms: [@"kabelplus"]),
        new NsiItem(
            DisplayName: @"Linz AG",
            Id: @"linzag-d7b91d",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"street_cabinet", [@"operator:wikidata"] = @"Q1827148", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"street_cabinet", [@"operator"] = @"Linz AG", [@"operator:wikidata"] = @"Q1827148", },
            Terms: [@"linz ag"]),
        new NsiItem(
            DisplayName: @"Flughafen Wien AG",
            Id: @"flughafenwienag-6f6c15",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"surveillance", [@"operator:wikidata"] = @"Q1433222", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"surveillance", [@"operator"] = @"Flughafen Wien AG", [@"operator:wikidata"] = @"Q1433222", },
            Terms: [@"flughafen wien ag"]),
        new NsiItem(
            DisplayName: @"Novomatic AG",
            Id: @"novomaticag-063466",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"surveillance", [@"operator:wikidata"] = @"Q2003025", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"surveillance", [@"operator"] = @"Novomatic AG", [@"operator:wikidata"] = @"Q2003025", },
            Terms: [@"novomatic ag"]),
        new NsiItem(
            DisplayName: @"Stadt Wien",
            Id: @"stadtwien-063466",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"surveillance", [@"operator:wikidata"] = @"Q1884195", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"surveillance", [@"operator"] = @"Stadt Wien", [@"operator:wikidata"] = @"Q1884195", },
            Terms: [@"stadt wien"]),
        new NsiItem(
            DisplayName: @"Wiener Linien",
            Id: @"wienerlinien-063466",
            Tags: new Dictionary<string, string> { [@"man_made"] = @"surveillance", [@"operator:wikidata"] = @"Q668849", },
            AddTags: new Dictionary<string, string> { [@"man_made"] = @"surveillance", [@"operator"] = @"Wiener Linien", [@"operator:wikidata"] = @"Q668849", },
            Terms: [@"wiener linien"]),
        new NsiItem(
            DisplayName: @"MA 31",
            Id: @"ma31-70ce42",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q262313", [@"pipeline"] = @"substation", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"MA 31", [@"operator:wikidata"] = @"Q262313", [@"pipeline"] = @"substation", },
            Terms: [@"ma 31", @"ma31 magistrat der stadt wien, wiener wasser"]),
        new NsiItem(
            DisplayName: @"Stadt Wien",
            Id: @"stadtwien-a0dadd",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q1884195", [@"pipeline"] = @"substation", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Stadt Wien", [@"operator:wikidata"] = @"Q1884195", [@"pipeline"] = @"substation", },
            Terms: [@"stadt wien"]),
        new NsiItem(
            DisplayName: @"WEB Windenergie AG",
            Id: @"webwindenergieag-47fbc0",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q2537048", [@"power"] = @"generator", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"WEB Windenergie AG", [@"operator:wikidata"] = @"Q2537048", [@"power"] = @"generator", },
            Terms: [@"web windenergie ag"]),
        new NsiItem(
            DisplayName: @"Windkraft Simonsfeld",
            Id: @"windkraftsimonsfeld-4f665e",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q1423736", [@"power"] = @"generator", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Windkraft Simonsfeld", [@"operator:wikidata"] = @"Q1423736", [@"power"] = @"generator", },
            Terms: [@"windkraft simonsfeld"]),
        new NsiItem(
            DisplayName: @"Linz AG",
            Id: @"linzag-c1b8b3",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q1827148", [@"power"] = @"line", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Linz AG", [@"operator:wikidata"] = @"Q1827148", [@"power"] = @"line", },
            Terms: [@"linz ag", @"linz ag strom", @"linz netz", @"linz strom ag"]),
        new NsiItem(
            DisplayName: @"Linz AG",
            Id: @"linzag-c2c254",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q1827148", [@"power"] = @"minor_line", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Linz AG", [@"operator:wikidata"] = @"Q1827148", [@"power"] = @"minor_line", },
            Terms: [@"linz ag", @"linz ag strom", @"linz netz", @"linz strom ag"]),
        new NsiItem(
            DisplayName: @"Ennskraftwerke AG",
            Id: @"ennskraftwerkeag-228c1b",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q1343462", [@"power"] = @"plant", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Ennskraftwerke AG", [@"operator:wikidata"] = @"Q1343462", [@"power"] = @"plant", },
            Terms: [@"ennskraftwerke ag"]),
        new NsiItem(
            DisplayName: @"EVN Naturkraft",
            Id: @"evnnaturkraft-0c9556",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q2693541", [@"power"] = @"plant", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"EVN Naturkraft", [@"operator:wikidata"] = @"Q2693541", [@"power"] = @"plant", },
            Terms: [@"evn naturkraft"]),
        new NsiItem(
            DisplayName: @"Windkraft Simonsfeld",
            Id: @"windkraftsimonsfeld-b0af4a",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q1423736", [@"power"] = @"plant", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Windkraft Simonsfeld", [@"operator:wikidata"] = @"Q1423736", [@"power"] = @"plant", },
            Terms: [@"windkraft simonsfeld"]),
        new NsiItem(
            DisplayName: @"Linz AG",
            Id: @"linzag-72f362",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q1827148", [@"power"] = @"pole", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Linz AG", [@"operator:wikidata"] = @"Q1827148", [@"power"] = @"pole", },
            Terms: [@"linz ag", @"linz ag strom", @"linz netz", @"linz strom ag"]),
        new NsiItem(
            DisplayName: @"Linz AG",
            Id: @"linzag-91958b",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q1827148", [@"power"] = @"substation", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Linz AG", [@"operator:wikidata"] = @"Q1827148", [@"power"] = @"substation", },
            Terms: [@"linz ag", @"linz ag strom", @"linz netz", @"linz strom ag"]),
        new NsiItem(
            DisplayName: @"Linz AG",
            Id: @"linzag-e85d67",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q1827148", [@"power"] = @"tower", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Linz AG", [@"operator:wikidata"] = @"Q1827148", [@"power"] = @"tower", },
            Terms: [@"linz ag", @"linz ag strom", @"linz netz", @"linz strom ag"]),
        new NsiItem(
            DisplayName: @"Linz AG",
            Id: @"linzag-f02bb8",
            Tags: new Dictionary<string, string> { [@"operator:wikidata"] = @"Q1827148", [@"power"] = @"transformer", },
            AddTags: new Dictionary<string, string> { [@"operator"] = @"Linz AG", [@"operator:wikidata"] = @"Q1827148", [@"power"] = @"transformer", },
            Terms: [@"linz ag", @"linz ag strom", @"linz netz", @"linz strom ag"]),
        new NsiItem(
            DisplayName: @"IDS BK",
            Id: @"idsbk-896f36",
            Tags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"network:wikidata"] = @"Q4241634", [@"public_transport"] = @"platform", },
            AddTags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"highway"] = @"bus_stop", [@"network"] = @"IDS BK", [@"network:wikidata"] = @"Q4241634", [@"public_transport"] = @"platform", },
            Terms: [@"ids bk"]),
        new NsiItem(
            DisplayName: @"IDS JMK",
            Id: @"integrovanydopravnisystemjihomoravskehokraje-c1eab2",
            Tags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"network:wikidata"] = @"Q12020731", [@"public_transport"] = @"platform", },
            AddTags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"highway"] = @"bus_stop", [@"network"] = @"Integrovaný dopravní systém Jihomoravského kraje", [@"network:short"] = @"IDS JMK", [@"network:wikidata"] = @"Q12020731", [@"public_transport"] = @"platform", },
            Terms: [@"ids jmk", @"integrovaný dopravní systém jihomoravského kraje"]),
        new NsiItem(
            DisplayName: @"MHD Bratislava",
            Id: @"mhdbratislava-a92fd9",
            Tags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"network:wikidata"] = @"Q7258005", [@"public_transport"] = @"platform", },
            AddTags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"highway"] = @"bus_stop", [@"network"] = @"MHD Bratislava", [@"network:wikidata"] = @"Q7258005", [@"public_transport"] = @"platform", },
            Terms: [@"mhd bratislava"]),
        new NsiItem(
            DisplayName: @"Oberösterreichischer Verkehrsverbund",
            Id: @"oberosterreichischerverkehrsverbund-a33556",
            Tags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"network:wikidata"] = @"Q2011605", [@"public_transport"] = @"platform", },
            AddTags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"highway"] = @"bus_stop", [@"network"] = @"Oberösterreichischer Verkehrsverbund", [@"network:short"] = @"OÖVV", [@"network:wikidata"] = @"Q2011605", [@"public_transport"] = @"platform", },
            Terms: [@"oberösterreichischer verkehrsverbund", @"oövv"]),
        new NsiItem(
            DisplayName: @"VOR",
            Id: @"vor-f99475",
            Tags: new Dictionary<string, string> { [@"light_rail"] = @"yes", [@"network:wikidata"] = @"Q2516485", [@"public_transport"] = @"station", },
            AddTags: new Dictionary<string, string> { [@"light_rail"] = @"yes", [@"network"] = @"VOR", [@"network:wikidata"] = @"Q2516485", [@"public_transport"] = @"station", [@"railway"] = @"station", [@"station"] = @"light_rail", },
            Terms: [@"vor"]),
        new NsiItem(
            DisplayName: @"Oberösterreichischer Verkehrsverbund",
            Id: @"oberosterreichischerverkehrsverbund-cf536b",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q2011605", [@"railway"] = @"station", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Oberösterreichischer Verkehrsverbund", [@"network:short"] = @"OÖVV", [@"network:wikidata"] = @"Q2011605", [@"public_transport"] = @"station", [@"railway"] = @"station", [@"train"] = @"yes", },
            Terms: [@"oberösterreichischer verkehrsverbund", @"oövv"]),
        new NsiItem(
            DisplayName: @"IDS BK",
            Id: @"idsbk-c89aa8",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q4241634", [@"route"] = @"bus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"IDS BK", [@"network:wikidata"] = @"Q4241634", [@"route"] = @"bus", [@"type"] = @"route", },
            Terms: [@"ids bk"]),
        new NsiItem(
            DisplayName: @"IDS JMK",
            Id: @"integrovanydopravnisystemjihomoravskehokraje-3c8eb1",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q12020731", [@"route"] = @"bus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Integrovaný dopravní systém Jihomoravského kraje", [@"network:short"] = @"IDS JMK", [@"network:wikidata"] = @"Q12020731", [@"route"] = @"bus", [@"type"] = @"route", },
            Terms: [@"ids jmk", @"integrovaný dopravní systém jihomoravského kraje"]),
        new NsiItem(
            DisplayName: @"MHD Bratislava",
            Id: @"mhdbratislava-ce8ad1",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q7258005", [@"route"] = @"bus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"MHD Bratislava", [@"network:wikidata"] = @"Q7258005", [@"route"] = @"bus", [@"type"] = @"route", },
            Terms: [@"mhd bratislava"]),
        new NsiItem(
            DisplayName: @"Oberösterreichischer Verkehrsverbund",
            Id: @"oberosterreichischerverkehrsverbund-7c0334",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q2011605", [@"route"] = @"bus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Oberösterreichischer Verkehrsverbund", [@"network:short"] = @"OÖVV", [@"network:wikidata"] = @"Q2011605", [@"route"] = @"bus", [@"type"] = @"route", },
            Terms: [@"oberösterreichischer verkehrsverbund", @"oövv"]),
        new NsiItem(
            DisplayName: @"VOR",
            Id: @"vor-09cbaf",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q2516485", [@"route"] = @"light_rail", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"VOR", [@"network:wikidata"] = @"Q2516485", [@"route"] = @"light_rail", [@"type"] = @"route", },
            Terms: [@"vor"]),
        new NsiItem(
            DisplayName: @"Oberösterreichischer Verkehrsverbund",
            Id: @"oberosterreichischerverkehrsverbund-e51205",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q2011605", [@"route"] = @"train", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Oberösterreichischer Verkehrsverbund", [@"network:short"] = @"OÖVV", [@"network:wikidata"] = @"Q2011605", [@"route"] = @"train", [@"type"] = @"route", },
            Terms: [@"oberösterreichischer verkehrsverbund", @"oövv"]),
    ];
}
