// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'jp-35.geojson'.</summary>
public static class NsiRegion_JP_35_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"宇部市",
            Id: @"bfa512-dd5810",
            Tags: new Dictionary<string, string> { [@"education"] = @"school", [@"operator:wikidata"] = @"Q468765", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"school", [@"education"] = @"school", [@"operator"] = @"宇部市", [@"operator:type"] = @"government", [@"operator:wikidata"] = @"Q468765", },
            Terms: [@"宇部市"]),
        new NsiItem(
            DisplayName: @"サンデン交通",
            Id: @"sandenkotsu-2d0f06",
            Tags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"network:wikidata"] = @"Q11305725", [@"public_transport"] = @"platform", },
            AddTags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"highway"] = @"bus_stop", [@"network"] = @"サンデン交通", [@"network:en"] = @"Sanden Kotsu", [@"network:ja"] = @"サンデン交通", [@"network:wikidata"] = @"Q11305725", [@"public_transport"] = @"platform", },
            Terms: [@"sanden kotsu", @"サンデン交通"]),
        new NsiItem(
            DisplayName: @"防長線",
            Id: @"bocholine-2d0f06",
            Tags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"network:wikidata"] = @"Q11657125", [@"public_transport"] = @"platform", },
            AddTags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"highway"] = @"bus_stop", [@"network"] = @"防長線", [@"network:en"] = @"Bocho Line", [@"network:ja"] = @"防長線", [@"network:wikidata"] = @"Q11657125", [@"public_transport"] = @"platform", },
            Terms: [@"bocho line", @"防長線"]),
        new NsiItem(
            DisplayName: @"サンデン交通",
            Id: @"sandenkotsu-b1baf4",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q11305725", [@"route"] = @"bus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"サンデン交通", [@"network:en"] = @"Sanden Kotsu", [@"network:ja"] = @"サンデン交通", [@"network:wikidata"] = @"Q11305725", [@"route"] = @"bus", [@"type"] = @"route", },
            Terms: [@"sanden kotsu", @"サンデン交通"]),
        new NsiItem(
            DisplayName: @"防長線",
            Id: @"bocholine-b1baf4",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q11657125", [@"route"] = @"bus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"防長線", [@"network:en"] = @"Bocho Line", [@"network:ja"] = @"防長線", [@"network:wikidata"] = @"Q11657125", [@"route"] = @"bus", [@"type"] = @"route", },
            Terms: [@"bocho line", @"防長線"]),
    ];
}
