// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'ch-bs.geojson'.</summary>
public static class NsiRegion_CH_BS_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"Regio Verkehrsverbund Lörrach",
            Id: @"regioverkehrsverbundlorrach-e6eff2",
            Tags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"network:wikidata"] = @"Q2138145", [@"public_transport"] = @"platform", },
            AddTags: new Dictionary<string, string> { [@"bus"] = @"yes", [@"highway"] = @"bus_stop", [@"network"] = @"Regio Verkehrsverbund Lörrach", [@"network:short"] = @"RVL", [@"network:wikidata"] = @"Q2138145", [@"public_transport"] = @"platform", },
            Terms: [@"regio verkehrsverbund lörrach", @"rvl"]),
        new NsiItem(
            DisplayName: @"TNW",
            Id: @"tnw-de548b",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q1479394", [@"railway"] = @"tram_stop", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"TNW", [@"network:wikidata"] = @"Q1479394", [@"railway"] = @"tram_stop", },
            Terms: [@"tnw"]),
        new NsiItem(
            DisplayName: @"Regio Verkehrsverbund Lörrach",
            Id: @"regioverkehrsverbundlorrach-f049e9",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q2138145", [@"route"] = @"bus", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"Regio Verkehrsverbund Lörrach", [@"network:short"] = @"RVL", [@"network:wikidata"] = @"Q2138145", [@"route"] = @"bus", [@"type"] = @"route", },
            Terms: [@"regio verkehrsverbund lörrach", @"rvl"]),
        new NsiItem(
            DisplayName: @"TNW",
            Id: @"tnw-8c2b04",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q1479394", [@"route"] = @"tram", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"TNW", [@"network:wikidata"] = @"Q1479394", [@"route"] = @"tram", [@"type"] = @"route", },
            Terms: [@"tnw"]),
    ];
}
