// <auto-generated>
//   This file was generated by Alidade.OsmGen. Do not edit manually.
//   Run `dotnet run --project Alidade.OsmGen` to regenerate.
// </auto-generated>
#nullable enable
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
using Alidade.Osm.Models.Nsi;

namespace Alidade.Osm.NameSuggestions;

/// <summary>NSI entries for region 'jp-30.geojson'.</summary>
public static class NsiRegion_JP_30_GEOJSON
{
    public static IReadOnlyList<NsiItem> Items { get; } =
    [
        new NsiItem(
            DisplayName: @"池田泉州銀行",
            Id: @"5e336b-a3da5f",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand:wikidata"] = @"Q11551996", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand"] = @"池田泉州銀行", [@"brand:wikidata"] = @"Q11551996", [@"operator"] = @"池田泉州銀行", [@"operator:wikidata"] = @"Q11551996", },
            Terms: [@"池田泉州銀行"]),
        new NsiItem(
            DisplayName: @"関西みらい銀行",
            Id: @"kansaimiraibank-f1b6cb",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand:wikidata"] = @"Q62679053", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"atm", [@"brand"] = @"関西みらい銀行", [@"brand:en"] = @"Kansai Mirai Bank", [@"brand:ja"] = @"関西みらい銀行", [@"brand:wikidata"] = @"Q62679053", [@"operator"] = @"関西みらい銀行", [@"operator:wikidata"] = @"Q62679053", },
            Terms: [@"kansai mirai bank", @"関西みらい銀行"]),
        new NsiItem(
            DisplayName: @"池田泉州銀行",
            Id: @"5e336b-f4c94b",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand:wikidata"] = @"Q11551996", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand"] = @"池田泉州銀行", [@"brand:wikidata"] = @"Q11551996", [@"name"] = @"池田泉州銀行", },
            Terms: [@"池田泉州銀行"]),
        new NsiItem(
            DisplayName: @"関西みらい銀行",
            Id: @"kansaimiraibank-5fa824",
            Tags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand:wikidata"] = @"Q62679053", },
            AddTags: new Dictionary<string, string> { [@"amenity"] = @"bank", [@"brand"] = @"関西みらい銀行", [@"brand:en"] = @"Kansai Mirai Bank", [@"brand:ja"] = @"関西みらい銀行", [@"brand:wikidata"] = @"Q62679053", [@"name"] = @"関西みらい銀行", [@"name:en"] = @"Kansai Mirai Bank", [@"name:ja"] = @"関西みらい銀行", },
            Terms: [@"kansai mirai bank", @"関西みらい銀行"]),
        new NsiItem(
            DisplayName: @"南海電鉄",
            Id: @"nankaielectricrailway-304e14",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q1188230", [@"railway"] = @"station", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"南海電鉄", [@"network:en"] = @"Nankai Electric Railway", [@"network:ja"] = @"南海電鉄", [@"network:wikidata"] = @"Q1188230", [@"public_transport"] = @"station", [@"railway"] = @"station", [@"train"] = @"yes", },
            Terms: [@"nankai electric railway", @"南海", @"南海電鉄"]),
        new NsiItem(
            DisplayName: @"南海電鉄",
            Id: @"nankaielectricrailway-9cabf3",
            Tags: new Dictionary<string, string> { [@"network:wikidata"] = @"Q1188230", [@"route"] = @"train", [@"type"] = @"route", },
            AddTags: new Dictionary<string, string> { [@"network"] = @"南海電鉄", [@"network:en"] = @"Nankai Electric Railway", [@"network:ja"] = @"南海電鉄", [@"network:wikidata"] = @"Q1188230", [@"route"] = @"train", [@"type"] = @"route", },
            Terms: [@"nankai electric railway", @"南海", @"南海電鉄"]),
    ];
}
